"use client";

import { formatEuro } from "@/lib/format/es-es";
import { madridToday } from "@/lib/time/madrid";
import { useMemo, useState } from "react";
import type { ForecastOverview, ForecastSaved, ForecastSuggestion, ForecastPoint } from "@/lib/financial/forecast";

const dateFmt=new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",year:"numeric"});
const shortDate=new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short"});
const monthFmt=new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"});
const dateLabel=(value:string)=>dateFmt.format(new Date(`${value}T12:00:00`));
const monthLabel=(value:string)=>monthFmt.format(new Date(`${value}-15T12:00:00`));
const currentMonth=madridToday().slice(0,7);

function addMonths(month:string,offset:number){const [year,number]=month.split("-").map(Number);return new Date(Date.UTC(year,number-1+offset,1)).toISOString().slice(0,7)}
function monthEnd(month:string){const [year,number]=month.split("-").map(Number);const day=new Date(Date.UTC(year,number,0)).getUTCDate();return `${month}-${String(day).padStart(2,"0")}`}
function balanceBefore(points:ForecastPoint[],fallback:number,date:string){let value=fallback;for(const point of points){if(point.source==="current")continue;if(point.date>=date)break;value=point.balance}return value}
function balanceThrough(points:ForecastPoint[],fallback:number,date:string){let value=fallback;for(const point of points){if(point.source==="current")continue;if(point.date>date)break;value=point.balance}return value}
function suggestionTotals(items:ForecastSuggestion[],month:string){const matches=items.filter(item=>item.nextDate.startsWith(month));const income=matches.filter(item=>item.amount>0).reduce((sum,item)=>sum+item.amount,0);const expenses=Math.abs(matches.filter(item=>item.amount<0).reduce((sum,item)=>sum+item.amount,0));return{count:matches.length,income,expenses,net:income-expenses};}

type Editor={id?:string;title:string;date:string;direction:"expense"|"income";amount:string;category:string;subcategory:string;counterparty:string;recurrence:"once"|"monthly"|"bimonthly"|"quarterly"|"yearly";until:string;notes:string;confidence?:number;explanation?:Record<string,unknown>};
const emptyEditor=():Editor=>({title:"",date:madridToday(),direction:"expense",amount:"",category:"",subcategory:"",counterparty:"",recurrence:"once",until:"",notes:""});

function recurrenceName(saved:ForecastSaved){const r=saved.recurrence;if(!r)return "Una vez";if(r.frequency==="yearly")return "Anual";if(r.frequency==="weekly")return r.interval===1?"Semanal":`Cada ${r.interval} semanas`;if(r.interval===2)return "Bimestral";if(r.interval===3)return "Trimestral";return r.interval===1?"Mensual":`Cada ${r.interval} meses`;}
function editorRecurrence(saved:ForecastSaved):Editor["recurrence"]{const r=saved.recurrence;if(!r)return "once";if(r.frequency==="yearly")return "yearly";if(r.frequency==="monthly"&&r.interval===2)return "bimonthly";if(r.frequency==="monthly"&&r.interval===3)return "quarterly";return "monthly";}
function recurrenceLabel(item:ForecastSuggestion){if(item.recurrence.frequency==="yearly")return "anual";if(item.recurrence.interval===1)return "mensual";if(item.recurrence.interval===2)return "bimestral";if(item.recurrence.interval===3)return "trimestral";return `cada ${item.recurrence.interval} meses`;}

function ForecastChart({points}:{points:ForecastPoint[]}){
  if(points.length<2)return <div className="forecast-chart-empty">Aún no hay suficientes eventos confirmados para dibujar la proyección.</div>;
  const width=960,height=270,padX=34,padY=24;const values=points.map(p=>p.balance);const min=Math.min(...values),max=Math.max(...values);const span=Math.max(1,max-min);const step=(width-padX*2)/Math.max(1,points.length-1);
  const coords=points.map((p,i)=>({x:padX+i*step,y:padY+(max-p.balance)/span*(height-padY*2),p}));
  const line=coords.map(c=>`${c.x},${c.y}`).join(" ");
  return <div className="forecast-chart-wrap"><svg className="forecast-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Evolución del saldo previsto"><line className="forecast-grid-line" x1={padX} x2={width-padX} y1={height-padY} y2={height-padY}/><polyline className="forecast-line" points={line}/>{coords.map((c,i)=><circle key={`${c.p.date}-${i}`} className={c.p.source==="current"?"forecast-dot current":"forecast-dot"} cx={c.x} cy={c.y} r={i===0?5:3.5}><title>{`${dateLabel(c.p.date)} · ${formatEuro(c.p.balance)} · ${c.p.title}`}</title></circle>)}</svg><div className="forecast-chart-labels"><span>{dateLabel(points[0].date)}</span><span>{dateLabel(points[points.length-1].date)}</span></div></div>;
}

export function ForecastClient({initialData}:{initialData:ForecastOverview}){
  const [data,setData]=useState(initialData);const [loading,setLoading]=useState(false);const [feedback,setFeedback]=useState<string|null>(null);const [editor,setEditor]=useState<Editor|null>(null);const [selectedMonth,setSelectedMonth]=useState(currentMonth);
  const monthOptions=useMemo(()=>Array.from({length:12},(_,index)=>addMonths(currentMonth,index)),[]);
  const monthEvents=useMemo(()=>data.events.filter(event=>event.date.startsWith(selectedMonth)),[data.events,selectedMonth]);
  const monthSuggestions=useMemo(()=>data.suggestions.filter(item=>item.nextDate.startsWith(selectedMonth)),[data.suggestions,selectedMonth]);
  const monthExpenses=useMemo(()=>Math.abs(monthEvents.filter(event=>event.amount<0).reduce((sum,event)=>sum+event.amount,0)),[monthEvents]);
  const monthIncome=useMemo(()=>monthEvents.filter(event=>event.amount>0).reduce((sum,event)=>sum+event.amount,0),[monthEvents]);
  const suggestedIncome=useMemo(()=>monthSuggestions.filter(item=>item.amount>0).reduce((sum,item)=>sum+item.amount,0),[monthSuggestions]);
  const suggestedExpenses=useMemo(()=>Math.abs(monthSuggestions.filter(item=>item.amount<0).reduce((sum,item)=>sum+item.amount,0)),[monthSuggestions]);
  const suggestedNet=suggestedIncome-suggestedExpenses;
  const firstRelevantDate=selectedMonth===currentMonth?madridToday():`${selectedMonth}-01`;const lastRelevantDate=monthEnd(selectedMonth);
  const startBalance=selectedMonth===currentMonth?data.currentBalance:balanceBefore(data.balanceSeries,data.currentBalance,firstRelevantDate);
  const endBalance=balanceThrough(data.balanceSeries,startBalance,lastRelevantDate);
  const selectedPoints=data.balanceSeries.filter(point=>point.source!=="current"&&point.date>=firstRelevantDate&&point.date<=lastRelevantDate);
  const lowestSelected=Math.min(startBalance,...selectedPoints.map(point=>point.balance));
  const monthNet=monthIncome-monthExpenses;const isCurrent=selectedMonth===currentMonth;
  const monthWindow=isCurrent?`Desde hoy, ${dateLabel(madridToday())}, hasta ${dateLabel(lastRelevantDate)}`:`Del ${dateLabel(`${selectedMonth}-01`)} al ${dateLabel(lastRelevantDate)}`;

  async function load(){setLoading(true);setFeedback(null);try{const response=await fetch(`/api/forecast?days=365`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error||"No se ha podido cargar la previsión");setData(json);}catch(error){setFeedback(error instanceof Error?error.message:"Error al cargar la previsión");}finally{setLoading(false);}}
  function openSaved(item:ForecastSaved){setEditor({id:item.id,title:item.title,date:item.date,direction:item.amount>=0?"income":"expense",amount:Math.abs(item.amount).toFixed(2).replace(".",","),category:item.category||"",subcategory:item.subcategory||"",counterparty:item.counterparty||"",recurrence:editorRecurrence(item),until:item.recurrence?.until||"",notes:item.notes||"",confidence:item.confidence});setFeedback(null);}
  async function postForecast(payload:any,message:string){setLoading(true);setFeedback(null);try{const response=await fetch("/api/forecast",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const json=await response.json();if(!response.ok)throw new Error(json.error||"No se ha podido guardar la previsión");setEditor(null);await load();setFeedback(message);}catch(error){setFeedback(error instanceof Error?error.message:"No se ha podido guardar");setLoading(false);}}
  async function saveEditor(){if(!editor)return;const amount=Math.abs(Number(editor.amount.replace(",",".")));if(!editor.title.trim()||!editor.date||!Number.isFinite(amount)||amount<=0){setFeedback("Indica título, fecha e importe válidos.");return;}let recurrence:any=null;if(editor.recurrence!=="once"){if(editor.recurrence==="yearly")recurrence={frequency:"yearly",interval:1};else recurrence={frequency:"monthly",interval:editor.recurrence==="bimonthly"?2:editor.recurrence==="quarterly"?3:1};if(editor.until)recurrence.until=editor.until;}await postForecast({id:editor.id||null,title:editor.title,date:editor.date,amount:editor.direction==="expense"?-amount:amount,category:editor.category||null,subcategory:editor.subcategory||null,counterparty:editor.counterparty||null,recurrence,notes:editor.notes||null,confidence:editor.confidence??1,explanation:editor.explanation||{source:"manual"}},editor.id?"Previsión actualizada.":"Previsión guardada.");}
  async function acceptSuggestion(item:ForecastSuggestion){await postForecast({title:item.title,date:item.nextDate,amount:item.amount,category:item.category,subcategory:item.subcategory,counterparty:item.counterparty,recurrence:item.recurrence,notes:"Aceptada desde sugerencia automática",confidence:item.confidence,explanation:item.explanation},"Sugerencia convertida en previsión confirmada y ya incluida en el cálculo.");}
  async function cancelForecast(id:string){if(!window.confirm("¿Cancelar esta previsión? Los movimientos reales no se modifican."))return;setLoading(true);setFeedback(null);try{const response=await fetch(`/api/forecast?id=${encodeURIComponent(id)}`,{method:"DELETE"});const json=await response.json();if(!response.ok)throw new Error(json.error||"No se ha podido cancelar");await load();setFeedback("Previsión cancelada.");}catch(error){setFeedback(error instanceof Error?error.message:"No se ha podido cancelar");setLoading(false);}}

  return <div className={`forecast-module ${loading?"is-loading":""}`}>
    <section className="forecast-philosophy"><div><p className="eyebrow">QUÉ SIGNIFICA PREVISIÓN</p><h2>La app propone desde tu historial y tú decides</h2><p>Primero detectamos cargos e ingresos que podrían repetirse. <strong>Nada modifica tu saldo hasta que lo confirmes.</strong></p></div><div className="forecast-philosophy-rules"><article><strong>Cuenta en el cálculo</strong><span>Previsiones que has confirmado y sus próximos vencimientos.</span></article><article><strong>Posible, pendiente de confirmar</strong><span>Patrones detectados automáticamente en tus movimientos históricos.</span></article></div></section>

    <div className="forecast-toolbar"><label className="forecast-month-selector"><span>Mes que quieres revisar</span><select value={selectedMonth} onChange={event=>setSelectedMonth(event.target.value)}>{monthOptions.map(month=><option key={month} value={month}>{monthLabel(month)}</option>)}</select><small>{monthWindow}</small></label><button className="primary-action" onClick={()=>setEditor(emptyEditor())}>+ Añadir gasto o ingreso previsto</button></div>
    {feedback&&<div className="forecast-feedback" role="status">{feedback}</div>}
    {monthSuggestions.length>0&&<div className="forecast-feedback" role="status"><strong>Según tu historial:</strong> podrían quedar {formatEuro(suggestedIncome)} de ingresos y {formatEuro(suggestedExpenses)} de gastos en {monthLabel(selectedMonth)}. Son posibilidades pendientes de tu confirmación y todavía no cambian el saldo.</div>}

    <section className="forecast-month-summary" aria-label={`Resumen de ${monthLabel(selectedMonth)}`}>
      <article><span>{isCurrent?"Saldo actual":"Saldo al iniciar el mes"}</span><strong>{formatEuro(startBalance)}</strong><small>{isCurrent?"Hoy":"Después de los meses anteriores"}</small></article>
      <article><span>Ingresos confirmados</span><strong className="positive">{formatEuro(monthIncome)}</strong><small>{suggestedIncome>0?`${formatEuro(suggestedIncome)} posibles sin confirmar`:`${monthEvents.filter(event=>event.amount>0).length} cobros confirmados`}</small></article>
      <article><span>Gastos confirmados</span><strong className="negative">{formatEuro(monthExpenses)}</strong><small>{suggestedExpenses>0?`${formatEuro(suggestedExpenses)} posibles sin confirmar`:`${monthEvents.filter(event=>event.amount<0).length} pagos confirmados`}</small></article>
      <article className={monthNet<0?"warning":"good"}><span>Saldo confirmado al terminar</span><strong>{formatEuro(endBalance)}</strong><small>{monthSuggestions.length?`Si confirmaras todo: ${formatEuro(endBalance+suggestedNet)}`:`Impacto neto del mes: ${formatEuro(monthNet)}`}</small></article>
      <article className={lowestSelected<0?"danger":"good"}><span>Saldo mínimo confirmado</span><strong>{formatEuro(lowestSelected)}</strong><small>{lowestSelected<0?"Hay riesgo de saldo negativo":"Sin saldo negativo confirmado"}</small></article>
    </section>

    <div className="forecast-grid forecast-month-grid">
      <section className="forecast-panel"><div className="forecast-panel-head"><div><p className="eyebrow">{monthLabel(selectedMonth).toUpperCase()}</p><h2>Qué está confirmado</h2><p>Solo estos movimientos forman el saldo oficial previsto del mes.</p></div><span className="pill">{monthEvents.length}</span></div>{!monthEvents.length?<div className="forecast-empty"><strong>No hay movimientos confirmados para este mes.</strong><p>Mira las sugerencias de la derecha: puedes aceptar las que esperes realmente.</p></div>:<div className="forecast-events">{monthEvents.map(event=><article key={event.id}><div className="forecast-event-date"><strong>{shortDate.format(new Date(`${event.date}T12:00:00`))}</strong><span>Confirmado</span></div><div><strong>{event.title}</strong><span>{event.category||"Sin categoría"}{event.subcategory?` · ${event.subcategory}`:""}</span></div><div className="forecast-event-right"><b className={event.amount<0?"negative":"positive"}>{formatEuro(event.amount)}</b><small>{event.amount<0?"Gasto":"Ingreso"}</small></div></article>)}</div>}</section>

      <aside className="forecast-panel forecast-suggestion-panel"><div className="forecast-panel-head"><div><p className="eyebrow">DETECTADO EN TU HISTORIAL</p><h2>Podría ocurrir en {monthLabel(selectedMonth)}</h2><p>La app proyecta patrones anteriores durante los próximos 12 meses. Confirma solo los que sigan vigentes.</p></div><span className="pill">{monthSuggestions.length}</span></div>{!monthSuggestions.length?<div className="forecast-empty compact"><strong>No se ha detectado ningún patrón pendiente para este mes.</strong></div>:<div className="forecast-suggestions">{monthSuggestions.map(item=><article key={item.id}><div className="forecast-suggestion-head"><div><strong>{item.title}</strong><span>{dateLabel(item.nextDate)} · {recurrenceLabel(item)}</span></div><b className={item.amount<0?"negative":"positive"}>{formatEuro(item.amount)}</b></div><div className="confidence-row"><span><i style={{width:`${Math.round(item.confidence*100)}%`}}/></span><b>{Math.round(item.confidence*100)}%</b></div><p>{String(item.explanation.reason||"Patrón detectado en tu historial")}. {Number(item.explanation.observations||0)} observación{Number(item.explanation.observations||0)===1?"":"es"}{item.explanation.medianIntervalDays?` · intervalo típico ${Number(item.explanation.medianIntervalDays).toLocaleString("es-ES")} días`:""}.</p><button className="text-button" onClick={()=>acceptSuggestion(item)} disabled={loading}>Sí, espero que ocurra · confirmar</button></article>)}</div>}</aside>
    </div>

    <article className="panel forecast-main-panel"><div className="panel-head"><div><p className="eyebrow">VISTA A 12 MESES</p><h2>Confirmado frente a lo que podría ocurrir</h2><p>La curva sigue siendo conservadora y solo usa lo confirmado. Cada tarjeta mensual añade debajo el escenario posible detectado en tu historial.</p></div><span className="pill">Hasta {dateLabel(data.endDate)}</span></div><ForecastChart points={data.balanceSeries}/><div className="forecast-months forecast-month-buttons">{monthOptions.map(month=>{const summary=data.monthly.find(item=>item.month===month);const possible=suggestionTotals(data.suggestions,month);const confirmedNet=summary?.net||0;const scenarioNet=confirmedNet+possible.net;return <button type="button" key={month} className={month===selectedMonth?"active":""} onClick={()=>setSelectedMonth(month)}><span>{monthLabel(month)}</span><b className={scenarioNet<0?"negative":"positive"}>{formatEuro(scenarioNet)}</b><small>{formatEuro(confirmedNet)} confirmado · {possible.count?`${formatEuro(possible.net)} posible (${possible.count})`:"sin sugerencias"}</small></button>})}</div></article>

    <section className="forecast-panel saved-forecasts"><div className="forecast-panel-head"><div><p className="eyebrow">REGLAS CONFIRMADAS</p><h2>Qué alimenta tu previsión</h2><p>Cada regla genera sus próximos vencimientos. Cuando aparece el movimiento real, ese vencimiento se consolida para no contarlo dos veces.</p></div><span className="pill">{data.savedForecasts.length}</span></div>{!data.savedForecasts.length?<div className="forecast-empty compact"><strong>Aún no has confirmado ninguna previsión.</strong><p>Elige una sugerencia histórica o añade una previsión manual.</p></div>:<div className="saved-forecast-list">{data.savedForecasts.map(item=><article key={item.id}><div><strong>{item.title}</strong><span>{dateLabel(item.date)} · {recurrenceName(item)}</span><small>{item.category||"Sin categoría"}{item.counterparty?` · ${item.counterparty}`:""}</small></div><b className={item.amount<0?"negative":"positive"}>{formatEuro(item.amount)}</b><button className="text-button" onClick={()=>openSaved(item)}>Editar</button></article>)}</div>}</section>

    <aside className="forecast-rule-note"><strong>Regla simple</strong><p><b>El historial propone.</b> <b>Tú confirmas.</b> <b>Solo lo confirmado modifica el saldo.</b> Si cambia un pagador, un recibo deja de llegar o una cantidad ya no es válida, simplemente no confirmes esa sugerencia.</p></aside>

    {editor&&<div className="forecast-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEditor(null);}}><section className="forecast-modal" role="dialog" aria-modal="true" aria-labelledby="forecast-editor-title"><div className="forecast-modal-head"><div><p className="eyebrow">{editor.id?"EDITAR":"NUEVA PREVISIÓN"}</p><h2 id="forecast-editor-title">Movimiento futuro</h2></div><button className="icon-button" onClick={()=>setEditor(null)} aria-label="Cerrar">×</button></div><div className="forecast-form">
      <label className="wide">Título<input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})} placeholder="Ej. Seguro del coche"/></label>
      <label>Fecha<input type="date" value={editor.date} onChange={e=>setEditor({...editor,date:e.target.value})}/></label>
      <label>Tipo<select value={editor.direction} onChange={e=>setEditor({...editor,direction:e.target.value as Editor["direction"]})}><option value="expense">Gasto</option><option value="income">Ingreso</option></select></label>
      <label>Importe (€)<input inputMode="decimal" value={editor.amount} onChange={e=>setEditor({...editor,amount:e.target.value})} placeholder="0,00"/></label>
      <label>Recurrencia<select value={editor.recurrence} onChange={e=>setEditor({...editor,recurrence:e.target.value as Editor["recurrence"]})}><option value="once">Una vez</option><option value="monthly">Mensual</option><option value="bimonthly">Bimestral</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option></select></label>
      {editor.recurrence!=="once"&&<label>Hasta <small>Opcional</small><input type="date" value={editor.until} onChange={e=>setEditor({...editor,until:e.target.value})}/></label>}
      <label>Categoría<input value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})} placeholder="Opcional"/></label><label>Subcategoría<input value={editor.subcategory} onChange={e=>setEditor({...editor,subcategory:e.target.value})} placeholder="Opcional"/></label>
      <label className="wide">Comercio o contraparte<input value={editor.counterparty} onChange={e=>setEditor({...editor,counterparty:e.target.value})} placeholder="Ayuda a consolidar con el movimiento real"/></label>
      <label className="wide">Notas<textarea rows={3} value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})} placeholder="Opcional"/></label>
    </div><div className="forecast-modal-actions">{editor.id&&<button className="danger-button" onClick={()=>cancelForecast(editor.id!)} disabled={loading}>Cancelar previsión</button>}<div/><button className="ghost" onClick={()=>setEditor(null)}>Cerrar</button><button className="primary-action" onClick={saveEditor} disabled={loading}>{loading?"Guardando…":"Guardar"}</button></div></section></div>}
  </div>;
}
