export const WORKSPACE_EXPORT_CONTRACT = {
  contractVersion: 1,
  format: "financial-app-workspace-json",
  locale: "es-ES",
  currency: "EUR",
  timeZone: "Europe/Madrid",
  includedDatasets: [
    "accounts",
    "accountSourceMappings",
    "categories",
    "merchants",
    "merchantAliases",
    "categorizationRules",
    "transactionSourceRecords",
    "transactions",
    "transactionOverrides",
    "transactionDuplicateReviews",
    "recurrences",
    "budgets",
    "forecastItems",
    "documents",
    "documentTransactionAssociations",
    "syncRuns",
    "syncCursors",
    "syncIssues",
    "auditChanges",
    "googleSourcePolicy",
  ],
  excludedSensitiveSources: [
    "google_oauth_connections",
    "authorized_users",
    "vault.secrets",
    "platform_tokens_and_secrets",
    "schema_meta",
  ],
  limitations: [
    "document_binaries_not_included",
    "oauth_credentials_not_included",
    "platform_access_controls_not_included",
    "vault_secrets_not_included",
  ],
  previewProductionAccess: "forbidden",
} as const;

export type WorkspaceExportDataset = (typeof WORKSPACE_EXPORT_CONTRACT.includedDatasets)[number];
