'use client';

import { ChangeEvent, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { BackupHistoryItem, BackupPreview, PrivateBackupPayload } from '../../src/private-data/backup';

function countLabel(counts:Record<string,number>={}){ return Object.values(counts).reduce((sum,value)=>sum+Number(value||0),0); }
function downloadBlob(blob:Blob,name:string){ const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }

export default function BackupManager({initialHistory,currentChecksum,currentRows}:{initialHistory:BackupHistoryItem[];currentChecksum:string;currentRows:number}){
  const router=useRouter();
  const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [imported,setImported]=useState<PrivateBackupPayload|null>(null); const [preview,setPreview]=useState<BackupPreview|null>(null); const [confirmation,setConfirmation]=useState('');
  const canRestore=Boolean(imported&&preview?.safe&&confirmation==='RESTAURAR');
  const totalItems=useMemo(()=>preview?countLabel(preview.counts):0,[preview]);

  async function exportCurrent(){ setBusy(true);setError('');try{ const response=await fetch('/api/private/backup?mode=export',{cache:'no-store'}); if(!response.ok)throw new Error('export-failed'); const blob=await response.blob(); downloadBlob(blob,`finanzas-private-backup-${new Date().toISOString().slice(0,10)}.json`); setMessage('Copia privada descargada.'); }catch{setError('No se ha podido exportar la copia privada.');}finally{setBusy(false);} }
  async function capture(){ setBusy(true);setError('');try{ const response=await fetch('/api/private/backup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'capture',note})}); const body=await response.json().catch(()=>({})); if(!response.ok||!body.ok)throw new Error(body.error||'capture-failed'); setMessage('Checkpoint privado guardado correctamente.'); setNote(''); router.refresh(); }catch{setError('No se ha podido guardar el checkpoint.');}finally{setBusy(false);} }
  async function chooseFile(event:ChangeEvent<HTMLInputElement>){ const file=event.target.files?.[0]; setImported(null);setPreview(null);setConfirmation('');setError('');setMessage(''); if(!file)return; try{ if(file.size>5_000_000)throw new Error('too-large'); const parsed=JSON.parse(await file.text()) as PrivateBackupPayload; const response=await fetch('/api/private/backup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'preview',backup:parsed})}); const body=await response.json().catch(()=>({})); if(!response.ok||!body.ok)throw new Error(body.error||'preview-failed'); setImported(parsed);setPreview(body as BackupPreview); }catch{setError('El archivo no es una copia válida o no se ha podido verificar. No se ha modificado ningún dato.');} finally{event.target.value='';} }
  async function restore(){ if(!canRestore||!imported||!preview)return; if(!window.confirm('La restauración sustituirá únicamente tu capa privada de trabajo por la contenida en esta copia. La fuente bancaria original no se tocará. ¿Continuar?'))return; setBusy(true);setError('');try{ const response=await fetch('/api/private/backup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'restore',backup:imported,expectedChecksum:preview.currentChecksum,confirmation})}); const body=await response.json().catch(()=>({})); if(!response.ok||!body.ok)throw new Error(body.error||'restore-failed'); setMessage('Capa privada restaurada y verificada.');setImported(null);setPreview(null);setConfirmation('');router.refresh(); }catch{setError('La restauración se ha bloqueado. No se ha aplicado una restauración parcial.');}finally{setBusy(false);} }

  return <>
    <section className="grid grid-2">
      <article className="card backup-card"><div className="eyebrow">Exportar</div><h2 className="section-title">Copia portátil</h2><p className="metric-note">Descarga categorías manuales, conciliación, divisiones, presupuestos, recurrentes, objetivos, eventos, escenarios, cierres y reglas. La fuente bancaria no se incluye.</p><div className="backup-actions"><button className="primary-inline-button" type="button" onClick={exportCurrent} disabled={busy}>Descargar JSON</button></div><div className="backup-fingerprint"><span>Checksum de fuente</span><code>{currentChecksum.slice(0,16)}…</code><span>{currentRows.toLocaleString('es-ES')} movimientos</span></div></article>
      <article className="card backup-card"><div className="eyebrow">Checkpoint interno</div><h2 className="section-title">Guardar punto de recuperación</h2><label className="form-field"><span>Nota opcional</span><input className="control" value={note} onChange={(e)=>setNote(e.target.value)} placeholder="Ej. Antes de cambiar reglas" maxLength={1000}/></label><div className="backup-actions"><button className="secondary-button" type="button" onClick={capture} disabled={busy}>Guardar checkpoint</button></div></article>
    </section>

    <section className="card section-gap"><div className="card-heading-row"><div><div className="eyebrow">Restaurar</div><h2 className="section-title">Verificar antes de sustituir</h2></div><span className="badge">Transacción atómica</span></div><p className="metric-note">Selecciona un JSON exportado por Finanzas. Primero se valida formato, checksum, número de filas y referencias a movimientos. Hasta que todo sea compatible no se habilita la restauración.</p><label className="backup-file"><input type="file" accept="application/json,.json" onChange={chooseFile} disabled={busy}/><span>Seleccionar copia JSON</span></label>
      {preview&&<div className={`status-panel ${preview.safe?'status-ok':'status-danger'} backup-preview`}><div><div className="status-title">{preview.safe?'Copia compatible':'Restauración bloqueada'}</div><div className="status-copy">Formato {preview.schemaCompatible?'correcto':'incompatible'} · checksum {preview.checksumCompatible?'coincide':'no coincide'} · referencias inválidas {preview.invalidMovementRefs} · {totalItems} registros privados.</div></div></div>}
      {preview?.safe&&<div className="backup-confirm"><label className="form-field"><span>Escribe RESTAURAR para habilitar el reemplazo</span><input className="control" value={confirmation} onChange={(e)=>setConfirmation(e.target.value)} autoComplete="off"/></label><button type="button" className="danger-button" disabled={!canRestore||busy} onClick={restore}>Restaurar capa privada</button></div>}
      {error&&<div className="form-error" role="alert">{error}</div>}{message&&<div className="status-panel status-ok"><div><div className="status-title">{message}</div></div></div>}
    </section>

    <section className="card section-gap"><div className="card-heading-row"><div><div className="eyebrow">Historial</div><h2 className="section-title">Checkpoints guardados</h2></div><span className="badge">{initialHistory.length}</span></div>{initialHistory.length===0?<div className="empty compact-empty">Todavía no hay puntos de recuperación guardados.</div>:<div className="backup-history">{initialHistory.map((item)=><article key={item.id}><div><strong>{new Date(item.captured_at).toLocaleString('es-ES')}</strong><p>{item.note||'Sin nota'} · {item.source_rows.toLocaleString('es-ES')} filas</p></div><code>{(item.source_checksum||'—').slice(0,12)}</code></article>)}</div>}</section>
  </>;
}
