import { inferDocumentMetadata, normalizeOcrText, preserveOcrLayout, parseEuroValue, type DocumentTypeHint, type DocumentMetadata, type ImageOcrResult } from "./ticket-ocr";
export { inferDocumentMetadata, normalizeOcrText, preserveOcrLayout, parseEuroValue };
export type { DocumentTypeHint, DocumentMetadata, ImageOcrResult };

type Recognition={data?:{text?:string;confidence?:number;tsv?:string}};
type Worker={setParameters?:(p:Record<string,string>)=>Promise<unknown>;recognize:(i:File|HTMLCanvasElement,o?:Record<string,unknown>,out?:Record<string,boolean>)=>Promise<Recognition>};
type Word={text:string;conf:number;left:number;top:number;width:number;key:string};
const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
const repair=(s:string)=>s.replace(/(\d)\s*[:;]\s*(\d{2})(?=\b)/g,"$1.$2").replace(/(\bTOTAL\b[^\d]{0,12})(\d{1,4})\s+(\d{2})(?=\s*(?:€|EUR)\b)/gi,"$1$2,$3").trimEnd();

export function reconstructTsvReceipt(tsv:string){
  if(!tsv.trim())return null;const words:Word[]=[];
  for(const row of tsv.replace(/\r/g,"").split("\n").slice(1)){const c=row.split("\t");if(c.length<12||Number(c[0])!==5)continue;const text=c.slice(11).join("\t").trim(),conf=Number(c[10]);if(!text||!Number.isFinite(conf)||conf<28)continue;const visible=text.replace(/\s/g,""),ok=(visible.match(/[\p{L}\d€%.,:()/-]/gu)||[]).length;if(visible.length&&ok/visible.length<.55)continue;words.push({text,conf,left:Number(c[6]),top:Number(c[7]),width:Number(c[8]),key:`${c[2]}:${c[3]}:${c[4]}`})}
  const groups=new Map<string,Word[]>();for(const w of words){const g=groups.get(w.key)||[];g.push(w);groups.set(w.key,g)}
  const lines=[...groups.values()].map(g=>{g.sort((a,b)=>a.left-b.left);const mean=g.reduce((s,w)=>s+w.conf,0)/g.length,plain=repair(g.map(w=>w.text).join(" ")),strong=/\b(total|iva|base|fecha|hora|mesa|precio|importe|pendiente)\b/i.test(plain)||/\d+[.,:]\d{2}/.test(plain);if(mean<38&&!strong)return null;const widths=g.map(w=>w.width/Math.max(1,w.text.length)).filter(Number.isFinite).sort((a,b)=>a-b),cw=Math.max(5,widths[Math.floor(widths.length/2)]||9),left=g[0].left;let layout="";for(const w of g){const col=Math.max(0,Math.round((w.left-left)/cw));if(layout.length<col)layout+=" ".repeat(col-layout.length);else if(layout&&!layout.endsWith(" "))layout+=" ";layout+=w.text}return{top:Math.min(...g.map(w=>w.top)),plain,layout:repair(layout)}}).filter((x):x is {top:number;plain:string;layout:string}=>Boolean(x)).sort((a,b)=>a.top-b.top);
  return lines.length?{text:lines.map(x=>x.plain).join("\n"),layoutText:lines.map(x=>x.layout).join("\n")}:null;
}

function bounds(data:ImageData,w:number,h:number){const step=Math.max(4,Math.floor(Math.max(w,h)/650)),rows=Math.ceil(h/step),cols=Math.ceil(w/step),minHits=Math.max(4,Math.round(cols*.16)),spans:{y:number;l:number;r:number}[]=[];for(let gy=0;gy<rows;gy++){const y=Math.min(h-1,gy*step);let hits=0,l=w,r=0;for(let gx=0;gx<cols;gx++){const x=Math.min(w-1,gx*step),o=(y*w+x)*4,R=data.data[o],G=data.data[o+1],B=data.data[o+2],hi=Math.max(R,G,B),lo=Math.min(R,G,B),lum=R*.2126+G*.7152+B*.0722;if(lum>=142&&hi-lo<=72&&G>=R-38&&B>=R-38){hits++;l=Math.min(l,x);r=Math.max(r,x)}}if(hits>=minHits)spans.push({y,l,r})}if(spans.length<rows*.22)return null;const med=(a:number[])=>a.sort((x,y)=>x-y)[Math.floor(a.length/2)],l=med(spans.map(x=>x.l)),r=med(spans.map(x=>x.r)),t=spans[0].y,b=spans.at(-1)!.y;let rw=r-l,rh=b-t;if(rw<w*.38||rh<h*.42)return null;const mx=rw*.06,my=rh*.08,x=Math.max(0,Math.round(l-mx)),y=Math.max(0,Math.round(t-my));rw=Math.min(w-x,Math.round(rw+mx*2));rh=Math.min(h-y,Math.round(rh+my*2));return{x,y,w:rw,h:rh}}

async function variants(file:File){const bm=await createImageBitmap(file);try{let s=Math.max(1,2100/Math.max(1,bm.width));if(bm.width*s>2800)s=2800/bm.width;if(bm.height*s>5200)s=Math.min(s,5200/bm.height);const fw=Math.round(bm.width*s),fh=Math.round(bm.height*s),base=document.createElement("canvas");base.width=fw;base.height=fh;const bc=base.getContext("2d",{willReadFrequently:true});if(!bc)throw new Error("Canvas no disponible");bc.drawImage(bm,0,0,fw,fh);const bd=bounds(bc.getImageData(0,0,fw,fh),fw,fh),src=document.createElement("canvas");if(bd){src.width=bd.w;src.height=bd.h;src.getContext("2d")?.drawImage(base,bd.x,bd.y,bd.w,bd.h,0,0,bd.w,bd.h)}else{src.width=fw;src.height=fh;src.getContext("2d")?.drawImage(base,0,0)}const w=src.width,h=src.height,c=src.getContext("2d",{willReadFrequently:true});if(!c)throw new Error("Canvas no disponible");const d=c.getImageData(0,0,w,h),gray=new Uint8ClampedArray(d.data.length);for(let o=0;o<d.data.length;o+=4){const v=Math.round(d.data[o]*.2126+d.data[o+1]*.7152+d.data[o+2]*.0722);gray[o]=gray[o+1]=gray[o+2]=v;gray[o+3]=255}const enhanced=document.createElement("canvas");enhanced.width=w;enhanced.height=h;enhanced.getContext("2d")?.putImageData(new ImageData(gray,w,h),0,0);const adaptive=new Uint8ClampedArray(gray),bs=Math.max(64,Math.round(Math.min(w,h)/18));for(let by=0;by<h;by+=bs)for(let bx=0;bx<w;bx+=bs){const ex=Math.min(w,bx+bs),ey=Math.min(h,by+bs);let sum=0,n=0;for(let y=by;y<ey;y+=2)for(let x=bx;x<ex;x+=2){sum+=gray[(y*w+x)*4];n++}const th=clamp(Math.round(sum/Math.max(1,n))-18,118,220);for(let y=by;y<ey;y++)for(let x=bx;x<ex;x++){const o=(y*w+x)*4,v=gray[o]<th?0:255;adaptive[o]=adaptive[o+1]=adaptive[o+2]=v;adaptive[o+3]=255}}const bin=document.createElement("canvas");bin.width=w;bin.height=h;bin.getContext("2d")?.putImageData(new ImageData(adaptive,w,h),0,0);return{enhanced,adaptive:bin}}finally{bm.close()}}

async function read(worker:Worker,input:HTMLCanvasElement|File,psm:string){await worker.setParameters?.({tessedit_pageseg_mode:psm,preserve_interword_spaces:"1",user_defined_dpi:"300"});const r=await worker.recognize(input,{}, {text:true,tsv:true}),raw=String(r.data?.text||""),structured=reconstructTsvReceipt(String(r.data?.tsv||""));return{text:repair(structured?.text||normalizeOcrText(raw)),layoutText:structured?.layoutText||preserveOcrLayout(raw),confidence:Number.isFinite(r.data?.confidence)?Number(r.data?.confidence):null}}
function score(text:string,confidence:number|null,hint:DocumentTypeHint){const m=inferDocumentMetadata(repair(text),hint);let s=confidence??0;if(m.documentDate)s+=18;if(m.amount!==null)s+=24;if(m.merchant)s+=14;if(/\bTOTAL\b/i.test(text))s+=7;s+=Math.min(18,text.length/60);return s}

export async function recognizeTicketImage(file:File,worker:Worker,onProgress:(value:number,label:string)=>void,hint:DocumentTypeHint=null):Promise<ImageOcrResult>{const passes:Array<{variant:string;text:string;layoutText:string;confidence:number|null;score:number}>=[];try{onProgress(.08,"Detectando el papel del ticket");const v=await variants(file);onProgress(.25,"Escaneando ticket · contraste adaptativo");const a=await read(worker,v.adaptive,"6");passes.push({variant:"adaptive_tsv",...a,score:score(a.text,a.confidence,hint)});onProgress(.55,"Escaneando ticket · columnas y precios");const b=await read(worker,v.enhanced,"4");passes.push({variant:"columns_tsv",...b,score:score(b.text,b.confidence,hint)});const best=passes.reduce((x,y)=>y.score>x.score?y:x),m=inferDocumentMetadata(best.text,hint);if(!m.documentDate||m.amount===null||!m.merchant){onProgress(.8,"Afinando caracteres dudosos");const c=await read(worker,v.enhanced,"6");passes.push({variant:"block_tsv",...c,score:score(c.text,c.confidence,hint)})}}catch{onProgress(.7,"Leyendo imagen original");const a=await read(worker,file,"6");passes.push({variant:"original_tsv",...a,score:score(a.text,a.confidence,hint)})}const best=passes.reduce((x,y)=>y.score>x.score?y:x);onProgress(.97,"Validando comercio, fecha e importe");return{text:best.text,layoutText:best.layoutText,confidence:best.confidence,method:`image_ocr_receipt_v305:${best.variant}`,passes:passes.map(({variant,confidence,score})=>({variant,confidence,score:Math.round(score*10)/10}))}}
