import { inferDocumentMetadata, normalizeOcrText, preserveOcrLayout, parseEuroValue, type DocumentTypeHint, type DocumentMetadata, type ImageOcrResult } from "./ticket-ocr";
export { inferDocumentMetadata, normalizeOcrText, preserveOcrLayout, parseEuroValue };
export type { DocumentTypeHint, DocumentMetadata, ImageOcrResult };

type Recognition={data?:{text?:string;confidence?:number;tsv?:string}};
type Worker={setParameters?:(p:Record<string,string>)=>Promise<unknown>;recognize:(i:File|HTMLCanvasElement,o?:Record<string,unknown>,out?:Record<string,boolean>)=>Promise<Recognition>};
type Word={text:string;conf:number;left:number;top:number;width:number;key:string};
type PaperGeometry={top:number;bottom:number;topLeft:number;topRight:number;bottomLeft:number;bottomRight:number};
const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
const repair=(s:string)=>s.replace(/(\d)\s*[:;]\s*(\d{2})(?=\b)/g,"$1.$2").replace(/(\bTOTAL\b[^\d]{0,12})(\d{1,4})\s+(\d{2})(?=\s*(?:€|EUR)\b)/gi,"$1$2,$3").trimEnd();
const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.floor(sorted.length/2)]};

export function reconstructTsvReceipt(tsv:string){
  if(!tsv.trim())return null;const words:Word[]=[];
  for(const row of tsv.replace(/\r/g,"").split("\n").slice(1)){const c=row.split("\t");if(c.length<12||Number(c[0])!==5)continue;const text=c.slice(11).join("\t").trim(),conf=Number(c[10]);if(!text||!Number.isFinite(conf)||conf<28)continue;const visible=text.replace(/\s/g,""),ok=(visible.match(/[\p{L}\d€%.,:()/-]/gu)||[]).length;if(visible.length&&ok/visible.length<.55)continue;words.push({text,conf,left:Number(c[6]),top:Number(c[7]),width:Number(c[8]),key:`${c[2]}:${c[3]}:${c[4]}`})}
  const groups=new Map<string,Word[]>();for(const w of words){const g=groups.get(w.key)||[];g.push(w);groups.set(w.key,g)}
  const lines=[...groups.values()].map(g=>{g.sort((a,b)=>a.left-b.left);const mean=g.reduce((s,w)=>s+w.conf,0)/g.length,plain=repair(g.map(w=>w.text).join(" ")),strong=/\b(total|iva|base|fecha|hora|mesa|precio|importe|pendiente)\b/i.test(plain)||/\d+[.,:]\d{2}/.test(plain);if(mean<38&&!strong)return null;const widths=g.map(w=>w.width/Math.max(1,w.text.length)).filter(Number.isFinite).sort((a,b)=>a-b),cw=Math.max(5,widths[Math.floor(widths.length/2)]||9),left=g[0].left;let layout="";for(const w of g){const col=Math.max(0,Math.round((w.left-left)/cw));if(layout.length<col)layout+=" ".repeat(col-layout.length);else if(layout&&!layout.endsWith(" "))layout+=" ";layout+=w.text}return{top:Math.min(...g.map(w=>w.top)),plain,layout:repair(layout)}}).filter((x):x is {top:number;plain:string;layout:string}=>Boolean(x)).sort((a,b)=>a.top-b.top);
  return lines.length?{text:lines.map(x=>x.plain).join("\n"),layoutText:lines.map(x=>x.layout).join("\n")}:null;
}

export function estimateDeskewFromSamples(samples:Array<{x:number;y:number}>,width:number,height:number){
  if(samples.length<80)return 0;let bestAngle=0,bestScore=-Infinity;const step=Math.max(2,Math.round(height/420));
  for(let angle=-7;angle<=7;angle+=.5){const rad=angle*Math.PI/180,c=Math.cos(rad),s=Math.sin(rad),bins=new Uint32Array(Math.ceil((height+Math.abs(width*s))/step)+8);for(const p of samples){const projected=p.y*c-p.x*s+Math.abs(width*s)+step*2;const index=Math.floor(projected/step);if(index>=0&&index<bins.length)bins[index]++}let score=0;for(let i=1;i<bins.length-1;i++){const value=bins[i]*2+bins[i-1]+bins[i+1];score+=value*value}if(score>bestScore){bestScore=score;bestAngle=angle}}
  return Math.abs(bestAngle)<.45?0:Math.round(bestAngle*2)/2;
}

function paperGeometry(data:ImageData,w:number,h:number):PaperGeometry|null{const step=Math.max(4,Math.floor(Math.max(w,h)/650)),rows=Math.ceil(h/step),cols=Math.ceil(w/step),minHits=Math.max(4,Math.round(cols*.16)),spans:{y:number;l:number;r:number}[]=[];for(let gy=0;gy<rows;gy++){const y=Math.min(h-1,gy*step);let hits=0,l=w,r=0;for(let gx=0;gx<cols;gx++){const x=Math.min(w-1,gx*step),o=(y*w+x)*4,R=data.data[o],G=data.data[o+1],B=data.data[o+2],hi=Math.max(R,G,B),lo=Math.min(R,G,B),lum=R*.2126+G*.7152+B*.0722;if(lum>=142&&hi-lo<=72&&G>=R-38&&B>=R-38){hits++;l=Math.min(l,x);r=Math.max(r,x)}}if(hits>=minHits&&r>l)spans.push({y,l,r})}if(spans.length<rows*.22)return null;const top=spans[0].y,bottom=spans.at(-1)!.y;if(bottom-top<h*.42)return null;const band=Math.max(4,Math.round(spans.length*.16)),topBand=spans.slice(0,band),bottomBand=spans.slice(-band),topLeft=median(topBand.map(x=>x.l)),topRight=median(topBand.map(x=>x.r)),bottomLeft=median(bottomBand.map(x=>x.l)),bottomRight=median(bottomBand.map(x=>x.r));const topWidth=topRight-topLeft,bottomWidth=bottomRight-bottomLeft;if(Math.min(topWidth,bottomWidth)<w*.34)return null;return{top,bottom,topLeft,topRight,bottomLeft,bottomRight}}

function rectify(base:HTMLCanvasElement,g:PaperGeometry|null){if(!g){const copy=document.createElement("canvas");copy.width=base.width;copy.height=base.height;copy.getContext("2d")?.drawImage(base,0,0);return{canvas:copy,perspective:false}}const height=Math.max(1,g.bottom-g.top),topWidth=g.topRight-g.topLeft,bottomWidth=g.bottomRight-g.bottomLeft,targetWidth=Math.max(1,Math.round((topWidth+bottomWidth)/2)),mx=Math.round(targetWidth*.06),my=Math.round(height*.06),out=document.createElement("canvas");out.width=targetWidth+mx*2;out.height=height+my*2;const ctx=out.getContext("2d");if(!ctx)throw new Error("Canvas no disponible");ctx.fillStyle="#fff";ctx.fillRect(0,0,out.width,out.height);const strip=Math.max(1,Math.round(height/900));for(let dy=0;dy<height;dy+=strip){const ratio=dy/Math.max(1,height-1),left=g.topLeft+(g.bottomLeft-g.topLeft)*ratio,right=g.topRight+(g.bottomRight-g.topRight)*ratio,srcY=g.top+dy,srcH=Math.min(strip,height-dy);ctx.drawImage(base,left,srcY,Math.max(1,right-left),srcH,mx,my+dy,targetWidth,srcH)}return{canvas:out,perspective:Math.abs(topWidth-bottomWidth)>Math.max(12,targetWidth*.025)||Math.abs(g.topLeft-g.bottomLeft)>Math.max(12,targetWidth*.025)}}

function deskew(src:HTMLCanvasElement){const maxSide=900,scale=Math.min(1,maxSide/Math.max(src.width,src.height)),w=Math.max(1,Math.round(src.width*scale)),h=Math.max(1,Math.round(src.height*scale)),sample=document.createElement("canvas");sample.width=w;sample.height=h;const sc=sample.getContext("2d",{willReadFrequently:true});if(!sc)return{canvas:src,angle:0};sc.drawImage(src,0,0,w,h);const data=sc.getImageData(0,0,w,h),points:Array<{x:number;y:number}>=[],stride=Math.max(1,Math.round(Math.max(w,h)/700));for(let y=0;y<h;y+=stride)for(let x=0;x<w;x+=stride){const o=(y*w+x)*4,lum=data.data[o]*.2126+data.data[o+1]*.7152+data.data[o+2]*.0722;if(lum<155)points.push({x,y})}if(points.length>18000){const every=Math.ceil(points.length/18000);for(let i=points.length-1;i>=0;i--)if(i%every!==0)points.splice(i,1)}const angle=estimateDeskewFromSamples(points,w,h);if(!angle)return{canvas:src,angle:0};const rad=-angle*Math.PI/180,c=Math.abs(Math.cos(rad)),s=Math.abs(Math.sin(rad)),out=document.createElement("canvas");out.width=Math.ceil(src.width*c+src.height*s);out.height=Math.ceil(src.height*c+src.width*s);const ctx=out.getContext("2d");if(!ctx)return{canvas:src,angle:0};ctx.fillStyle="#fff";ctx.fillRect(0,0,out.width,out.height);ctx.translate(out.width/2,out.height/2);ctx.rotate(rad);ctx.drawImage(src,-src.width/2,-src.height/2);return{canvas:out,angle}}

async function variants(file:File){const bm=await createImageBitmap(file);try{let s=Math.max(1,2100/Math.max(1,bm.width));if(bm.width*s>2800)s=2800/bm.width;if(bm.height*s>5200)s=Math.min(s,5200/bm.height);const fw=Math.round(bm.width*s),fh=Math.round(bm.height*s),base=document.createElement("canvas");base.width=fw;base.height=fh;const bc=base.getContext("2d",{willReadFrequently:true});if(!bc)throw new Error("Canvas no disponible");bc.fillStyle="#fff";bc.fillRect(0,0,fw,fh);bc.drawImage(bm,0,0,fw,fh);const geometry=paperGeometry(bc.getImageData(0,0,fw,fh),fw,fh),rectified=rectify(base,geometry),straight=deskew(rectified.canvas),src=straight.canvas,w=src.width,h=src.height,c=src.getContext("2d",{willReadFrequently:true});if(!c)throw new Error("Canvas no disponible");const d=c.getImageData(0,0,w,h),gray=new Uint8ClampedArray(d.data.length);for(let o=0;o<d.data.length;o+=4){const v=Math.round(d.data[o]*.2126+d.data[o+1]*.7152+d.data[o+2]*.0722);gray[o]=gray[o+1]=gray[o+2]=v;gray[o+3]=255}const enhanced=document.createElement("canvas");enhanced.width=w;enhanced.height=h;enhanced.getContext("2d")?.putImageData(new ImageData(gray,w,h),0,0);const adaptive=new Uint8ClampedArray(gray),bs=Math.max(64,Math.round(Math.min(w,h)/18));for(let by=0;by<h;by+=bs)for(let bx=0;bx<w;bx+=bs){const ex=Math.min(w,bx+bs),ey=Math.min(h,by+bs);let sum=0,n=0;for(let y=by;y<ey;y+=2)for(let x=bx;x<ex;x+=2){sum+=gray[(y*w+x)*4];n++}const th=clamp(Math.round(sum/Math.max(1,n))-18,118,220);for(let y=by;y<ey;y++)for(let x=bx;x<ex;x++){const o=(y*w+x)*4,v=gray[o]<th?0:255;adaptive[o]=adaptive[o+1]=adaptive[o+2]=v;adaptive[o+3]=255}}const bin=document.createElement("canvas");bin.width=w;bin.height=h;bin.getContext("2d")?.putImageData(new ImageData(adaptive,w,h),0,0);return{enhanced,adaptive:bin,deskewAngle:straight.angle,perspectiveCorrected:rectified.perspective}}finally{bm.close()}}

async function read(worker:Worker,input:HTMLCanvasElement|File,psm:string){await worker.setParameters?.({tessedit_pageseg_mode:psm,preserve_interword_spaces:"1",user_defined_dpi:"300"});const r=await worker.recognize(input,{}, {text:true,tsv:true}),raw=String(r.data?.text||""),structured=reconstructTsvReceipt(String(r.data?.tsv||""));return{text:repair(structured?.text||normalizeOcrText(raw)),layoutText:structured?.layoutText||preserveOcrLayout(raw),confidence:Number.isFinite(r.data?.confidence)?Number(r.data?.confidence):null}}
function score(text:string,confidence:number|null,hint:DocumentTypeHint){const m=inferDocumentMetadata(repair(text),hint);let s=confidence??0;if(m.documentDate)s+=18;if(m.amount!==null)s+=24;if(m.merchant)s+=14;if(/\bTOTAL\b/i.test(text))s+=7;s+=Math.min(18,text.length/60);return s}

export async function recognizeTicketImage(file:File,worker:Worker,onProgress:(value:number,label:string)=>void,hint:DocumentTypeHint=null):Promise<ImageOcrResult>{const passes:Array<{variant:string;text:string;layoutText:string;confidence:number|null;score:number}>=[];let deskewAngle=0,perspectiveCorrected=false;try{onProgress(.06,"Detectando bordes del ticket");const v=await variants(file);deskewAngle=v.deskewAngle;perspectiveCorrected=v.perspectiveCorrected;onProgress(.2,perspectiveCorrected||deskewAngle?"Corrigiendo perspectiva y giro":"Preparando contraste del ticket");onProgress(.32,"Escaneando ticket · contraste adaptativo");const a=await read(worker,v.adaptive,"6");passes.push({variant:"adaptive_rectified_tsv",...a,score:score(a.text,a.confidence,hint)});onProgress(.62,"Escaneando ticket · columnas y precios");const b=await read(worker,v.enhanced,"4");passes.push({variant:"columns_rectified_tsv",...b,score:score(b.text,b.confidence,hint)});const best=passes.reduce((x,y)=>y.score>x.score?y:x),m=inferDocumentMetadata(best.text,hint);if(!m.documentDate||m.amount===null||!m.merchant){onProgress(.82,"Afinando caracteres dudosos");const c=await read(worker,v.enhanced,"6");passes.push({variant:"block_rectified_tsv",...c,score:score(c.text,c.confidence,hint)})}}catch{onProgress(.72,"Leyendo imagen original");const a=await read(worker,file,"6");passes.push({variant:"original_tsv",...a,score:score(a.text,a.confidence,hint)})}const best=passes.reduce((x,y)=>y.score>x.score?y:x);onProgress(.97,"Validando comercio, fecha e importe");const result={text:best.text,layoutText:best.layoutText,confidence:best.confidence,method:`image_ocr_receipt_v306:${best.variant}`,passes:passes.map(({variant,confidence,score})=>({variant,confidence,score:Math.round(score*10)/10}))} as ImageOcrResult & {deskewAngle?:number;perspectiveCorrected?:boolean};result.deskewAngle=deskewAngle;result.perspectiveCorrected=perspectiveCorrected;return result}
