"use client";

import { useMemo,useState } from "react";
import type { BudgetItem,BudgetMonth,BudgetStatus,UnbudgetedItem } from "@/lib/financial/budget";

const money=new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"});
const monthName=new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric"});
const statusLabel:Record<BudgetStatus,string>={correct:"Correcto",attention:"Atención",exceeded:"Excedido"};
function moveMonth(month:string,offset:number){const [year,value]=month.split("-").map(Number);const d=new Date(year,value-1+offset,1,12);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;}
function labelMonth(month:string){return monthName.format(new Date(`${month}-01T12:00:00`));}
type Editor={id?:string;category:string;subcategory:string;amount:string;carryover:boolean;notes:string};
const emptyEditor:Editor={category:"",subcategory:"",amount:"",carryover:false,notes:""};

export function BudgetClient({initialData}:{initialData:BudgetMonth}){
 const [data,setData]=useState(initialData);const [loading,setLoading]=useState(false);const [editor,setEditor]=useState<Editor|null>(null);const [feedback,setFeedback]=useState<string|null>(null);
 const totalSpent=data.spent+data.unbudgetedSpent;const coverage=totalSpent>0?Math.round(data.spent/totalSpent*100):100;const monthLabel=useMemo(()=>labelMonth(data.month),[data.month]);
 const attentionCount=data.budgets.filter(x=>x.status==="attention").length;const exceededCount=data.budgets.filter(x=>x.status==="exceeded").length;
 async function loadMonth(month:string){setLoading(true);setFeedback(null);try{const r=await fetch(`/api/budget?month=${encodeURIComponent(month)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se ha podido cargar el presupuesto");setData(j);}catch(e){setFeedback(e instanceof Error?e.message:"Error al cargar el presupuesto");}finally{setLoading(false);}}
 function openEdit(item:BudgetItem){setEditor({id:item.id,category:item.category,subcategory:item.subcategory||"",amount:String(item.assigned).replace(".",","),carryover:item.carryover,notes:item.notes||""});setFeedback(null);}
 function openFromUnbudgeted(item:UnbudgetedItem){const amount=item.suggestion>0?item.suggestion:item.spent;setEditor({category:item.category,subcategory:item.subcategory||"",amount:amount.toFixed(2).replace(".",","),carryover:false,notes:""});setFeedback(null);}
 async function saveBudget(){if(!editor)return;const amount=Number(editor.amount.replace(",","."));if(!editor.category.trim()||!Number.isFinite(amount)||amount<0){setFeedback("Indica una categoría y un importe válido.");return;}setLoading(true);setFeedback(null);try{const r=await fetch("/api/budget",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...editor,amount,month:data.month})});const j=await r.json();if(!r.ok)throw new Error(j.error?.includes("already_exists")?"Ya existe un presupuesto para esa categoría y subcategoría en este mes.":j.error||"No se ha podido guardar");setEditor(null);await loadMonth(data.month);setFeedback("Presupuesto guardado.");}catch(e){setFeedback(e instanceof Error?e.message:"No se ha podido guardar");setLoading(false);}}
 async function removeBudget(id:string){if(!window.confirm("¿Quitar este presupuesto del mes? Los movimientos no se modifican."))return;setLoading(true);setFeedback(null);try{const r=await fetch(`/api/budget?id=${encodeURIComponent(id)}`,{method:"DELETE"});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se ha podido quitar");setEditor(null);await loadMonth(data.month);setFeedback("Presupuesto retirado del mes.");}catch(e){setFeedback(e instanceof Error?e.message:"No se ha podido quitar");setLoading(false);}}
 return <div className={`budget-module ${loading?"is-loading":""}`}>
  <div className="budget-toolbar"><div className="month-switcher"><button className="ghost" type="button" onClick={()=>loadMonth(moveMonth(data.month,-1))} disabled={loading} aria-label="Mes anterior">←</button><div><span>Presupuesto mensual</span><strong>{monthLabel}</strong></div><button className="ghost" type="button" onClick={()=>loadMonth(moveMonth(data.month,1))} disabled={loading} aria-label="Mes siguiente">→</button></div><button className="primary-action" type="button" onClick={()=>setEditor({...emptyEditor})}>+ Añadir presupuesto</button></div>
  {feedback&&<div className="budget-feedback" role="status">{feedback}</div>}
  <section className="budget-summary" aria-label="Resumen del presupuesto">
   <article><span>Asignado</span><strong>{money.format(data.assigned)}</strong><small>{data.budgets.length} partidas presupuestadas</small></article>
   <article><span>Gasto total del mes</span><strong>{money.format(totalSpent)}</strong><small>{coverage}% cubierto por partidas activas</small></article>
   <article className={data.available<0?"danger":"good"}><span>Disponible presupuestado</span><strong>{data.assigned>0?money.format(data.available):"—"}</strong><small>{data.assigned>0?`${exceededCount} excedidas · ${attentionCount} en atención`:"Sin límites asignados"}</small></article>
   <article className={attentionCount||exceededCount?"warning":"good"}><span>Cierre proyectado</span><strong>{data.assigned>0?money.format(data.projection.projectedSpent):"—"}</strong><small>{data.calendar.daysRemaining} días restantes · ritmo actual</small></article>
   <article><span>Sin presupuesto</span><strong>{money.format(data.unbudgetedSpent)}</strong><small>{data.unbudgeted.length} partidas con gasto real</small></article>
  </section>

  <div className="budget-layout"><section className="budget-panel"><div className="budget-panel-head"><div><p className="eyebrow">PLAN DEL MES</p><h2>Partidas presupuestadas</h2></div><span className="pill">{data.calendar.daysRemaining} días restantes</span></div>
   {!data.budgets.length?<div className="budget-empty"><strong>Aún no has asignado límites para {monthLabel}.</strong><p>El gasto real del mes es {money.format(totalSpent)}. No se inventa ningún presupuesto: puedes convertir una partida de gasto real en presupuesto cuando quieras.</p></div>:<div className="budget-list">{data.budgets.map(item=>{const denom=item.assigned+item.carryIn;const percent=denom>0?Math.min(100,Math.max(0,item.spent/denom*100)):item.spent>0?100:0;return <article key={item.id} className={`budget-row status-${item.status}`}>
    <div className="budget-row-main"><div><strong>{item.category}</strong><span>{item.subcategory||"Toda la categoría"}{item.carryover?` · arrastre ${money.format(item.carryIn)}`:""}</span></div><div className="budget-row-actions"><span className={`budget-status ${item.status}`}>{statusLabel[item.status]}</span><button className="text-button" type="button" onClick={()=>openEdit(item)}>Editar</button></div></div>
    <div className="budget-values four"><div><span>Asignado</span><strong>{money.format(item.assigned)}</strong></div><div><span>Gastado</span><strong>{money.format(item.spent)}</strong></div><div><span>Cierre proyectado</span><strong>{item.projectedSpend==null?"—":money.format(item.projectedSpend)}</strong></div><div><span>Disponible</span><strong className={item.available<0?"negative":"positive"}>{money.format(item.available)}</strong></div></div>
    <div className="budget-progress"><span style={{width:`${percent}%`}}/></div><div className="budget-row-foot"><span>{item.movements} movimientos</span><span>Media 3 meses: {money.format(item.suggestion)}</span><span>{item.percent.toLocaleString("es-ES",{maximumFractionDigits:1})}% consumido</span><span>{item.projectedDifference==null?"Sin proyección":`Diferencia prevista ${money.format(item.projectedDifference)}`}</span></div>
   </article>})}</div>}
  </section><aside className="budget-panel unbudgeted-panel"><div className="budget-panel-head"><div><p className="eyebrow">POR CONTROLAR</p><h2>Gasto sin presupuesto</h2></div><span className="pill">{money.format(data.unbudgetedSpent)}</span></div>{!data.unbudgeted.length?<div className="budget-empty compact"><strong>Todo el gasto del mes está cubierto.</strong></div>:<div className="unbudgeted-list">{data.unbudgeted.map((item,index)=><div className="unbudgeted-row" key={`${item.category}-${item.subcategory||"all"}-${index}`}><div><strong>{item.category}</strong><span>{item.subcategory||"Sin subcategoría"} · {item.movements} mov.</span><small>Media 3 meses {money.format(item.suggestion)}</small></div><div><b>{money.format(item.spent)}</b><button className="text-button" type="button" onClick={()=>openFromUnbudgeted(item)}>Presupuestar</button></div></div>)}</div>}</aside></div>

  <section className="budget-panel annual-budget-panel"><div className="budget-panel-head"><div><p className="eyebrow">VISIÓN ANUAL · {data.annual.year}</p><h2>Presupuesto frente a gasto real</h2></div><span className="pill">12 meses</span></div><div className="annual-budget-summary"><div><span>Presupuesto asignado</span><strong>{data.annual.assigned>0?money.format(data.annual.assigned):"—"}</strong></div><div><span>Gasto cubierto por presupuesto</span><strong>{money.format(data.annual.budgetedSpent)}</strong></div><div><span>Gasto real total</span><strong>{money.format(data.annual.totalSpent)}</strong></div><div><span>Diferencia anual</span><strong className={(data.annual.difference??0)<0?"negative":"positive"}>{data.annual.difference==null?"—":money.format(data.annual.difference)}</strong></div></div><div className="annual-budget-months">{data.annual.months.map(m=><div key={m.month}><span>{m.month}</span><div><i className="annual-spend" style={{width:`${Math.min(100,m.totalSpent>0?100:0)}%`}}/><i className="annual-assigned" style={{width:`${m.assigned>0&&m.totalSpent>0?Math.min(100,m.assigned/m.totalSpent*100):m.assigned>0?100:0}%`}}/></div><small>{m.assigned>0?`${money.format(m.assigned)} presupuesto · `:""}${money.format(m.totalSpent)} gasto</small></div>)}</div>{data.annual.assigned===0&&<p className="annual-budget-note">No existen presupuestos asignados en {data.annual.year}. El gasto anual se muestra como dato real, sin convertirlo en un presupuesto ficticio.</p>}</section>

  <aside className="budget-rule-note"><strong>Cómo se calcula</strong><p>El presupuesto usa gasto personal real de cuentas operativas. Ahorro, traspasos internos, duplicados y origen ausente no consumen presupuesto. “Atención” aparece al 80% o cuando el ritmo actual proyecta un exceso; “Excedido” solo cuando el gasto real supera el disponible.</p></aside>
  {editor&&<div className="budget-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEditor(null)}}><section className="budget-modal" role="dialog" aria-modal="true" aria-labelledby="budget-editor-title"><div className="budget-modal-head"><div><p className="eyebrow">{editor.id?"EDITAR":"NUEVA PARTIDA"}</p><h2 id="budget-editor-title">Presupuesto de {monthLabel}</h2></div><button className="icon-button" type="button" onClick={()=>setEditor(null)} aria-label="Cerrar">×</button></div><div className="budget-form"><label>Categoría<select value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}><option value="">Selecciona una categoría</option>{data.categories.map(category=><option value={category} key={category}>{category}</option>)}</select></label><label>Subcategoría <small>Opcional; vacío = toda la categoría</small><input value={editor.subcategory} onChange={e=>setEditor({...editor,subcategory:e.target.value})} placeholder="Ej. Combustible"/></label><label>Importe asignado (€)<input inputMode="decimal" value={editor.amount} onChange={e=>setEditor({...editor,amount:e.target.value})} placeholder="0,00"/></label><label className="carryover-control"><input type="checkbox" checked={editor.carryover} onChange={e=>setEditor({...editor,carryover:e.target.checked})}/><span>Arrastrar al mes siguiente el disponible positivo</span></label><label>Notas<textarea rows={3} value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})} placeholder="Opcional"/></label></div><div className="budget-modal-actions">{editor.id&&<button className="danger-button" type="button" onClick={()=>removeBudget(editor.id!)} disabled={loading}>Quitar</button>}<div/><button className="ghost" type="button" onClick={()=>setEditor(null)}>Cancelar</button><button className="primary-action" type="button" onClick={saveBudget} disabled={loading}>{loading?"Guardando…":"Guardar"}</button></div></section></div>}
 </div>;
}
