"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "./dashboard.module.css";

type TransactionKind = "income" | "expense" | "transfer" | "refund" | "adjustment";
type AccountBalance = { id:string; name:string; type:string; lifecycle:"active"|"archived"; balanceCents:number; balanceSource:"bank_explicit"|"reconstructed"; explicitBalanceDate:string|null; reconstructionDeltaCents:number|null };
type FinancialSnapshot = { period:{ dateFrom:string|null; dateTo:string|null; incomeCents:number; expenseCents:number; operatingNetCents:number; savingsCents:number; savingsRateBps:number|null; transfers:{grossCents:number}; quality:{suspectedDuplicateRows:number; signMismatchRows:number} }; balances:{ asOfDate:string|null; activeBalanceCents:number; quality:{accounts:number; explicitBalanceAccounts:number; reconstructedBalanceAccounts:number; integrityDeltaAccounts:number}; accounts:AccountBalance[] }; principles:{ bankSource:"read_only"; transfersExcludedFromSavings:boolean; explicitBankBalancePreferred:boolean } };
type MonthlyRow = { monthStart:string; incomeCents:number; expenseCents:number; operatingNetCents:number };
type MonthlyResponse = { dateFrom:string|null; dateTo:string|null; rows:MonthlyRow[] };
type BudgetItem = { categoryId:string|null; categoryName:string|null; effectiveAmountCents:number; actualExpenseCents:number; remainingCents:number; progressBps:number|null; status:"empty"|"unfunded"|"on_track"|"over" };
type BudgetSnapshot = { month:string; total:BudgetItem; categories:BudgetItem[] };
type ForecastItem = { id:string; date:string; concept:string; amountCents:number; origin:"known"|"recurring"|"budget"|"manual"|"inferred"; confidence:"high"|"medium"|"low"; status:"planned"|"excluded"|"confirmed"; affectsProjection:boolean };
type ForecastSnapshot = { period:{dateFrom:string;dateTo:string;accountId:string|null}; summary:{openingBalanceCents:number;projectedIncomeCents:number;projectedExpenseCents:number;projectedNetCents:number;projectedClosingBalanceCents:number;plannedItems:number;excludedItems:number;confirmedItems:number}; items:ForecastItem[] };
type TransactionRow = { id:string; bankDate:string; amountCents:number; account:{id:string;name:string}; concept:{effective:string}; category:{effectiveName:string|null}; kind:{effective:TransactionKind}; duplicateState:"none"|"suspected"|"confirmed"; excludedFromAnalytics:boolean };
type TransactionsResponse = { rows:TransactionRow[]; totalCount:number };
type DashboardData = { financial:FinancialSnapshot; monthly:MonthlyResponse; budgets:BudgetSnapshot; forecast:ForecastSnapshot; transactions:TransactionsResponse };

const money = new Intl.NumberFormat("es-ES", { style:"currency", currency:"EUR", minimumFractionDigits:2, maximumFractionDigits:2, useGrouping:"always" });
const percent = new Intl.NumberFormat("es-ES", { maximumFractionDigits:1 });
const dateFormatter = new Intl.DateTimeFormat("es-ES", { day:"2-digit", month:"short", timeZone:"Europe/Madrid" });
const monthFormatter = new Intl.DateTimeFormat("es-ES", { month:"short", timeZone:"Europe/Madrid" });
function formatMoney(cents:number){ return money.format(cents/100); }
function madridToday(){ const parts=new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Europe/Madrid"}).formatToParts(new Date()); const value=Object.fromEntries(parts.map((part)=>[part.type,part.value])); return `${value.year}-${value.month}-${value.day}`; }
function addDays(date:string,days:number){ const parsed=new Date(`${date}T12:00:00Z`); parsed.setUTCDate(parsed.getUTCDate()+days); return parsed.toISOString().slice(0,10); }
function formatDate(date:string|null){ return date?dateFormatter.format(new Date(`${date}T12:00:00Z`)).replace(".",""):"Sin fecha"; }
function formatMonth(date:string){ return monthFormatter.format(new Date(`${date}T12:00:00Z`)).replace(".",""); }
function monthLabel(month:string){ const [year,monthNumber]=month.split("-").map(Number); return new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric",timeZone:"Europe/Madrid"}).format(new Date(Date.UTC(year,monthNumber-1,15,12))); }
async function readJson<T>(url:string):Promise<T>{ const response=await fetch(url,{cache:"no-store"}); if(!response.ok) throw new Error(`request_failed_${response.status}`); return response.json() as Promise<T>; }
function accountType(type:string){ return ({checking:"Cuenta corriente",savings:"Ahorro",credit:"Crédito",cash:"Efectivo",investment:"Inversión",other:"Cuenta"} as Record<string,string>)[type]??"Cuenta"; }
function kindLabel(kind:TransactionKind){ if(kind==="income")return "Ingreso"; if(kind==="expense")return "Gasto"; if(kind==="transfer")return "Transferencia"; if(kind==="refund")return "Devolución"; return "Ajuste"; }
function forecastOrigin(origin:ForecastItem["origin"]){ return ({known:"Conocido",recurring:"Recurrente",budget:"Presupuesto",manual:"Manual",inferred:"Inferido"} as Record<ForecastItem["origin"],string>)[origin]; }
function Icon({name}:{name:"wallet"|"balance"|"chart"|"budget"|"future"|"activity"|"arrow"}){ const paths={ wallet:<><path d="M3.5 7h16v11h-16a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h13v3"/><path d="M15 11h7v4h-7a2 2 0 1 1 0-4Z"/></>, balance:<><path d="M12 3v18M5 7h14M7 7l-4 7h8L7 7Zm10 0-4 7h8l-4-7Z"/></>, chart:<><path d="M4 19V5M4 19h17"/><path d="m7 15 4-5 3 3 5-7"/></>, budget:<><path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5"/></>, future:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, activity:<path d="M3 12h4l2-5 4 10 2-5h6"/>, arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></> } as const; return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>; }

export default function DashboardClient({phaseLabel}:{phaseLabel:string}){
  const [data,setData]=useState<DashboardData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{ let cancelled=false; const today=madridToday(); const month=today.slice(0,7); const monthStart=`${month}-01`; const yearStart=`${today.slice(0,4)}-01-01`; const forecastTo=addDays(today,30); setLoading(true); setError(""); Promise.all([
    readJson<FinancialSnapshot>(`/api/financial?mode=snapshot&dateFrom=${monthStart}&dateTo=${today}`),
    readJson<MonthlyResponse>(`/api/financial?mode=monthly&dateFrom=${yearStart}&dateTo=${today}`),
    readJson<BudgetSnapshot>(`/api/budgets?month=${month}`),
    readJson<ForecastSnapshot>(`/api/forecast?dateFrom=${today}&dateTo=${forecastTo}`),
    readJson<TransactionsResponse>("/api/transactions?limit=6"),
  ]).then(([financial,monthly,budgets,forecast,transactions])=>{ if(!cancelled)setData({financial,monthly,budgets,forecast,transactions}); }).catch(()=>{ if(!cancelled)setError("No se ha podido construir el resumen con los motores centrales."); }).finally(()=>{ if(!cancelled)setLoading(false); }); return()=>{cancelled=true}; },[]);
  const topBudgetCategories=useMemo(()=>data?.budgets.categories.filter((item)=>item.categoryName&&item.actualExpenseCents>0).sort((a,b)=>b.actualExpenseCents-a.actualExpenseCents).slice(0,4)??[],[data]);
  const upcomingItems=useMemo(()=>data?.forecast.items.filter((item)=>item.affectsProjection&&item.status==="planned").slice(0,4)??[],[data]);
  const monthlyScale=useMemo(()=>Math.max(1,...(data?.monthly.rows.flatMap((row)=>[row.incomeCents,row.expenseCents])??[1])),[data]);
  if(loading)return <main className={styles.shell} aria-busy="true"><section className={styles.loadingCard}><span className={styles.loadingPulse}/><p>Construyendo tu resumen desde los motores validados…</p></section></main>;
  if(!data||error)return <main className={styles.shell}><section className={styles.errorCard} role="alert"><p className={styles.eyebrow}>Financial App</p><h1>No puedo mostrar Inicio ahora mismo</h1><p>{error||"Los datos centrales no están disponibles."}</p><Link href="/accounts" className={styles.primaryLink}>Abrir Cuentas</Link></section></main>;
  const {financial,monthly,budgets,forecast,transactions}=data; const activeAccounts=financial.balances.accounts.filter((account)=>account.lifecycle==="active"); const savingsRate=financial.period.savingsRateBps===null?"Sin dato":`${percent.format(financial.period.savingsRateBps/100)} %`; const budgetProgress=budgets.total.progressBps===null?0:Math.min(100,budgets.total.progressBps/100);
  return <main className={styles.shell}>
    <header className={styles.hero}><div><p className={styles.eyebrow}>FINANCIAL APP · {phaseLabel}</p><h1>Tu dinero, claro en segundos.</h1><p className={styles.heroText}>Lo importante de hoy, sin repetir información ni recalcular lo que ya saben los motores financieros.</p></div><div className={styles.heroBalance} aria-label="Disponible total"><span>Disponible total</span><strong>{formatMoney(financial.balances.activeBalanceCents)}</strong><small>Fuente bancaria preferente · {formatDate(financial.balances.asOfDate)}</small></div></header>
    <nav className={styles.quickNav} aria-label="Accesos principales"><Link href="/transactions">Movimientos</Link><Link href="/accounts">Cuentas</Link><Link href="/budgets">Presupuestos</Link><Link href="/forecast">Previsión</Link><Link href="/documents">Documentos</Link><Link href="/configuration">Configuración</Link></nav>
    <section className={styles.grid} aria-label="Resumen financiero">
      <article className={`${styles.panel} ${styles.panorama}`}><div className={styles.panelHeader}><div className={styles.iconBox}><Icon name="wallet"/></div><div><span className={styles.kicker}>Panorama</span><h2>Tus cuentas</h2></div><Link href="/accounts" className={styles.iconLink} aria-label="Abrir Cuentas"><Icon name="arrow"/></Link></div><div className={styles.accountList}>{activeAccounts.map((account)=><div className={styles.accountRow} key={account.id}><div><strong>{account.name}</strong><span>{accountType(account.type)} · {account.balanceSource==="bank_explicit"?"saldo bancario":"reconstruido"}</span></div><strong>{formatMoney(account.balanceCents)}</strong></div>)}</div>{financial.balances.quality.integrityDeltaAccounts>0&&<p className={styles.notice}>Hay cuentas con diferencia de reconstrucción; prevalece el saldo bancario explícito.</p>}</article>
      <article className={`${styles.panel} ${styles.monthBalance}`}><div className={styles.panelHeader}><div className={styles.iconBox}><Icon name="balance"/></div><div><span className={styles.kicker}>Este mes</span><h2>Balance</h2></div></div><div className={styles.metricGrid}><div><span>Ingresos</span><strong>{formatMoney(financial.period.incomeCents)}</strong></div><div><span>Gastos</span><strong>{formatMoney(financial.period.expenseCents)}</strong></div><div><span>Balance neto</span><strong>{formatMoney(financial.period.operatingNetCents)}</strong></div><div><span>Tasa de ahorro</span><strong>{savingsRate}</strong></div></div><p className={styles.panelFoot}>Transferencias internas ({formatMoney(financial.period.transfers.grossCents)}) no computan como ahorro.</p></article>
      <article className={`${styles.panel} ${styles.evolution}`}><div className={styles.panelHeader}><div className={styles.iconBox}><Icon name="chart"/></div><div><span className={styles.kicker}>Año actual</span><h2>Evolución financiera</h2></div></div>{monthly.rows.length?<div className={styles.chart} aria-label="Ingresos y gastos por mes">{monthly.rows.map((row)=><div className={styles.chartColumn} key={row.monthStart}><div className={styles.bars}><span className={styles.incomeBar} style={{height:`${Math.max(4,row.incomeCents/monthlyScale*100)}%`}} title={`Ingresos ${formatMoney(row.incomeCents)}`}/><span className={styles.expenseBar} style={{height:`${Math.max(4,row.expenseCents/monthlyScale*100)}%`}} title={`Gastos ${formatMoney(row.expenseCents)}`}/></div><small>{formatMonth(row.monthStart)}</small></div>)}</div>:<p className={styles.empty}>Aún no hay meses con actividad para representar.</p>}<div className={styles.legend}><span><i className={styles.incomeDot}/>Ingresos</span><span><i className={styles.expenseDot}/>Gastos</span></div></article>
      <article className={`${styles.panel} ${styles.budget}`}><div className={styles.panelHeader}><div className={styles.iconBox}><Icon name="budget"/></div><div><span className={styles.kicker}>{monthLabel(budgets.month)}</span><h2>Gasto y presupuesto</h2></div><Link href="/budgets" className={styles.iconLink} aria-label="Abrir Presupuestos"><Icon name="arrow"/></Link></div><div className={styles.budgetSummary}><div><span>Gastado</span><strong>{formatMoney(budgets.total.actualExpenseCents)}</strong></div><div><span>Disponible</span><strong>{formatMoney(budgets.total.remainingCents)}</strong></div></div><div className={styles.progressTrack} aria-label={`Presupuesto consumido ${percent.format(budgetProgress)} %`}><span style={{width:`${budgetProgress}%`}}/></div><div className={styles.categoryList}>{topBudgetCategories.length?topBudgetCategories.map((item)=><div key={item.categoryId??item.categoryName} className={styles.categoryRow}><span>{item.categoryName}</span><strong>{formatMoney(item.actualExpenseCents)}</strong></div>):<p className={styles.empty}>Sin categorías de gasto este mes.</p>}</div></article>
      <article className={`${styles.panel} ${styles.future}`}><div className={styles.panelHeader}><div className={styles.iconBox}><Icon name="future"/></div><div><span className={styles.kicker}>Próximos 30 días</span><h2>Qué viene ahora</h2></div><Link href="/forecast" className={styles.iconLink} aria-label="Abrir Previsión"><Icon name="arrow"/></Link></div><div className={styles.futureBalance}><span>Saldo previsto al final</span><strong>{formatMoney(forecast.summary.projectedClosingBalanceCents)}</strong><small>Variación prevista {formatMoney(forecast.summary.projectedNetCents)}</small></div><div className={styles.futureList}>{upcomingItems.length?upcomingItems.map((item)=><div key={item.id} className={styles.futureRow}><div><strong>{item.concept}</strong><span>{formatDate(item.date)} · {forecastOrigin(item.origin)}</span></div><strong>{formatMoney(item.amountCents)}</strong></div>):<p className={styles.empty}>No hay movimientos previstos que afecten a la proyección.</p>}</div></article>
      <article className={`${styles.panel} ${styles.activity}`}><div className={styles.panelHeader}><div className={styles.iconBox}><Icon name="activity"/></div><div><span className={styles.kicker}>Últimos movimientos</span><h2>Actividad reciente</h2></div><Link href="/transactions" className={styles.iconLink} aria-label="Abrir Movimientos"><Icon name="arrow"/></Link></div><div className={styles.transactionList}>{transactions.rows.map((transaction)=><div className={styles.transactionRow} key={transaction.id}><div><strong>{transaction.concept.effective}</strong><span>{formatDate(transaction.bankDate)} · {transaction.category.effectiveName??kindLabel(transaction.kind.effective)}</span></div><strong className={styles[`kind_${transaction.kind.effective}`]}>{formatMoney(transaction.amountCents)}</strong></div>)}{!transactions.rows.length&&<p className={styles.empty}>No hay actividad reciente.</p>}</div></article>
    </section>
    <footer className={styles.footerNote}><span>Fuente bancaria: solo lectura</span><span>{financial.principles.transfersExcludedFromSavings?"Transferencias excluidas del ahorro":"Revisar criterio de transferencias"}</span><span>{financial.balances.quality.explicitBalanceAccounts} saldos bancarios explícitos</span></footer>
  </main>;
}
