"use client";

import { useEffect,useMemo,useState } from "react";
import { formatEuro,formatPercent,formatSignedPercent } from "@/lib/format/es-es";
import type { AnalysisCategory,AnalysisDeviation,AnalysisMerchant,AnalysisMonth } from "@/lib/financial/analysis";
import type { AnalysisInsights } from "@/lib/financial/analysis-insights";

type ChartId=
  |"monthly-flow"|"net-trend"|"savings-rate"|"cumulative-net"|"category-donut"|"category-bars"|"merchant-bars"|"year-compare"|"deviations"|"monthly-heatmap"
  |"income-trend"|"expense-trend"|"income-prior"|"expense-prior"|"expense-ratio"|"net-diverging"|"expense-average"|"income-average"|"rolling-expenses"|"rolling-net"
  |"category-pareto"|"merchant-pareto"|"category-treemap"|"annual-waterfall";

type Props={months:AnalysisMonth[];categories:AnalysisCategory[];merchants:AnalysisMerchant[];deviations:AnalysisDeviation[];insights:AnalysisInsights;year:number;comparisonYear:number;income:number;expenses:number;net:number;priorIncome:number;priorExpenses:number;priorNet:number};

const STORAGE_KEY="financial-app.analysis.visual-layout.v2";
const DEFAULT_ORDER:ChartId[]=[
  "monthly-flow","net-trend","income-trend","expense-trend","savings-rate","expense-ratio","cumulative-net","net-diverging",
  "income-prior","expense-prior","year-compare","annual-waterfall","rolling-expenses","rolling-net","expense-average","income-average",
  "category-donut","category-bars","category-treemap","category-pareto","merchant-bars","merchant-pareto","deviations","monthly-heatmap",
];
const LABELS:Record<ChartId,string>={
  "monthly-flow":"Ingresos y gastos por mes","net-trend":"Evolución del Cash Flow","income-trend":"Evolución de ingresos","expense-trend":"Evolución de gastos",
  "savings-rate":"Tasa de ahorro mensual","expense-ratio":"Peso del gasto sobre ingresos","cumulative-net":"Cash Flow acumulado","net-diverging":"Meses positivos y negativos",
  "income-prior":"Ingresos frente al año anterior","expense-prior":"Gastos frente al año anterior","year-compare":"Comparativa anual resumida","annual-waterfall":"Puente ingresos → gastos → Cash Flow",
  "rolling-expenses":"Media móvil de gasto · 3 meses","rolling-net":"Media móvil de Cash Flow · 3 meses","expense-average":"Gasto frente a su media mensual","income-average":"Ingresos frente a su media mensual",
  "category-donut":"Distribución del gasto","category-bars":"Ranking de categorías","category-treemap":"Mapa de categorías","category-pareto":"Pareto de categorías",
  "merchant-bars":"Principales comercios","merchant-pareto":"Pareto de comercios","deviations":"Desviaciones de gasto","monthly-heatmap":"Mapa de intensidad mensual",
};

const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const avg=(values:number[])=>values.length?values.reduce((s,v)=>s+v,0)/values.length:0;
const pct=(current:number,previous:number)=>previous>0?((current-previous)/previous)*100:null;
const available=(months:AnalysisMonth[])=>months.filter(m=>m.available);
const rolling=(values:number[],width=3)=>values.map((_,i)=>avg(values.slice(Math.max(0,i-width+1),i+1)));
const points=(values:number[],width:number,height:number,pad=26,domain?:{min:number;max:number})=>{
  if(!values.length)return "";
  const min=domain?.min??Math.min(0,...values),max=domain?.max??Math.max(0,...values);const span=Math.max(1,max-min);
  return values.map((v,i)=>{const x=pad+(i*(width-pad*2))/Math.max(1,values.length-1);const y=pad+((max-v)/span)*(height-pad*2);return `${x},${y}`}).join(" ");
};

function ChartCard({id,title,subtitle,children,onMove,onHide,index,total}:{id:ChartId;title:string;subtitle:string;children:React.ReactNode;onMove:(id:ChartId,offset:number)=>void;onHide:(id:ChartId)=>void;index:number;total:number}){
  return <article className="analysis-viz-card" draggable onDragStart={e=>e.dataTransfer.setData("text/plain",id)} data-chart-id={id}>
    <div className="analysis-viz-head"><div><span>{title}</span><small>{subtitle}</small></div><div className="analysis-viz-actions"><button className="icon-button" type="button" onClick={()=>onMove(id,-1)} disabled={index===0} aria-label={`Mover ${title} antes`}>←</button><button className="icon-button" type="button" onClick={()=>onMove(id,1)} disabled={index===total-1} aria-label={`Mover ${title} después`}>→</button><button className="icon-button" type="button" onClick={()=>onHide(id)} aria-label={`Ocultar ${title}`}>×</button></div></div>
    <div className="analysis-viz-body">{children}</div>
  </article>;
}

function MonthlyFlowChart({months}:{months:AnalysisMonth[]}){const shown=available(months);const max=Math.max(1,...shown.flatMap(m=>[m.income,m.expenses]));return <div className="analysis-bar-chart" role="img" aria-label="Ingresos y gastos mensuales">{shown.map(m=><div className="analysis-bar-group" key={m.month}><div className="analysis-bar-pair"><i className="income" style={{height:`${clamp(m.income/max*100,2,100)}%`}} title={`${m.label}: ingresos ${formatEuro(m.income)}`}/><i className="expense" style={{height:`${clamp(m.expenses/max*100,2,100)}%`}} title={`${m.label}: gastos ${formatEuro(m.expenses)}`}/></div><span>{m.label.slice(0,3)}</span></div>)}</div>}

function LineChart({values,secondary,labels,aria,percent=false}:{values:number[];secondary?:number[];labels:string[];aria:string;percent?:boolean}){
  const width=720,height=230;const all=secondary?[...values,...secondary]:values;const domain={min:Math.min(0,...all),max:Math.max(0,...all)};const primary=points(values,width,height,26,domain);const second=secondary?points(secondary,width,height,26,domain):"";const zeroY=26+((domain.max-0)/Math.max(1,domain.max-domain.min))*(height-52);
  return <div className="analysis-svg-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={aria}><line className="viz-zero" x1="26" x2={width-26} y1={zeroY} y2={zeroY}/>{secondary&&<polyline className="viz-line-secondary" points={second}/>}<polyline className="viz-line-primary" points={primary}/>{values.map((v,i)=>{const [x,y]=(primary.split(" ")[i]||"0,0").split(",");return <circle key={`${aria}-${i}`} className="viz-point" cx={x} cy={y} r="4"><title>{`${labels[i]} · ${percent?formatPercent(v,1):formatEuro(v)}`}</title></circle>})}</svg></div>;
}

function SavingsRateChart({months}:{months:AnalysisMonth[]}){const shown=available(months);const rates=shown.map(m=>m.income>0?(m.net/m.income)*100:0);const width=720,height=230;const line=points(rates,width,height);const poly=line?`26,${height-26} ${line} ${width-26},${height-26}`:"";return <div className="analysis-svg-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Tasa de ahorro mensual"><polygon className="viz-area" points={poly}/><polyline className="viz-line-primary" points={line}/>{rates.map((v,i)=>{const [x,y]=(line.split(" ")[i]||"0,0").split(",");return <circle key={shown[i]?.month} className="viz-point" cx={x} cy={y} r="4"><title>{`${shown[i]?.label}: ${formatPercent(v,1)}`}</title></circle>})}</svg></div>}
function CumulativeNetChart({months}:{months:AnalysisMonth[]}){const shown=available(months);let total=0;const values=shown.map(m=>(total+=m.net));return <LineChart values={values} labels={shown.map(m=>m.label)} aria="Cash Flow acumulado"/>}
function MetricTrend({months,metric,prior=false}:{months:AnalysisMonth[];metric:"income"|"expenses";prior?:boolean}){const shown=available(months);const priorKey=metric==="income"?"priorIncome":"priorExpenses";return <LineChart values={shown.map(m=>m[metric])} secondary={prior?shown.map(m=>Number(m[priorKey]||0)):undefined} labels={shown.map(m=>m.label)} aria={`${metric==="income"?"Ingresos":"Gastos"}${prior?" frente al año anterior":" mensuales"}`}/>}
function ExpenseRatio({months}:{months:AnalysisMonth[]}){const shown=available(months);const values=shown.map(m=>m.income>0?m.expenses/m.income*100:0);return <LineChart values={values} labels={shown.map(m=>m.label)} aria="Peso del gasto sobre ingresos" percent/>}
function RollingMetric({months,metric}:{months:AnalysisMonth[];metric:"expenses"|"net"}){const shown=available(months);return <LineChart values={rolling(shown.map(m=>m[metric]))} labels={shown.map(m=>m.label)} aria={`Media móvil de ${metric==="expenses"?"gasto":"Cash Flow"} de tres meses`}/>}

function CategoryDonut({categories}:{categories:AnalysisCategory[]}){const shown=categories.slice(0,6);const total=shown.reduce((s,c)=>s+c.amount,0);let offset=0;return <div className="analysis-donut-layout"><svg className="analysis-donut" viewBox="0 0 42 42" role="img" aria-label="Distribución del gasto por categorías"><circle className="donut-base" cx="21" cy="21" r="15.9"/>{shown.map((c,i)=>{const share=total?c.amount/total*100:0;const dash=`${share} ${100-share}`;const node=<circle key={c.category} className={`donut-segment segment-${i+1}`} cx="21" cy="21" r="15.9" strokeDasharray={dash} strokeDashoffset={-offset}><title>{`${c.category}: ${formatEuro(c.amount)} · ${formatPercent(c.share,1)}`}</title></circle>;offset+=share;return node})}<text x="21" y="20.5" textAnchor="middle" className="donut-center-value">{formatPercent(shown.reduce((s,c)=>s+c.share,0),0)}</text><text x="21" y="24" textAnchor="middle" className="donut-center-label">top 6</text></svg><ol className="analysis-mini-legend">{shown.map((c,i)=><li key={c.category}><i className={`segment-${i+1}`}/><span>{c.category}</span><strong>{formatEuro(c.amount)}</strong></li>)}</ol></div>}
function RankingBars({items,kind}:{items:{label:string;value:number;meta:string}[];kind:"category"|"merchant"}){const max=Math.max(1,...items.map(i=>i.value));return <div className={`analysis-ranking-bars ${kind}`}>{items.map(item=><div key={item.label}><div><span>{item.label}</span><strong>{formatEuro(item.value)}</strong></div><div className="analysis-ranking-track"><i style={{width:`${clamp(item.value/max*100,1,100)}%`}}/></div><small>{item.meta}</small></div>)}</div>}
function YearCompare({year,comparisonYear,income,expenses,net,priorIncome,priorExpenses,priorNet}:Pick<Props,"year"|"comparisonYear"|"income"|"expenses"|"net"|"priorIncome"|"priorExpenses"|"priorNet">){const rows=[{label:"Ingresos",current:income,prior:priorIncome},{label:"Gastos",current:expenses,prior:priorExpenses},{label:"Cash Flow",current:Math.abs(net),prior:Math.abs(priorNet)}];const max=Math.max(1,...rows.flatMap(r=>[r.current,r.prior]));return <div className="analysis-year-bars">{rows.map(r=><div key={r.label}><span>{r.label}</span><div className="analysis-year-pair"><i className="current" style={{width:`${r.current/max*100}%`}} title={`${year}: ${formatEuro(r.current)}`}/><i className="prior" style={{width:`${r.prior/max*100}%`}} title={`${comparisonYear}: ${formatEuro(r.prior)}`}/></div><small>{year}: {formatEuro(r.current)} · {comparisonYear}: {formatEuro(r.prior)}</small></div>)}</div>}
function DeviationsChart({deviations}:{deviations:AnalysisDeviation[]}){const shown=deviations.slice(0,8);const max=Math.max(1,...shown.flatMap(d=>[d.current,d.previous3MonthAverage]));return <div className="analysis-deviation-bars">{shown.map(d=><div key={d.category}><div><span>{d.category}</span><strong className={d.changePercent!=null&&d.changePercent>0?"negative":"positive"}>{d.changePercent==null?"Nuevo":formatSignedPercent(d.changePercent,1)}</strong></div><div className="analysis-deviation-pair"><i className="current" style={{width:`${d.current/max*100}%`}} title={`Actual ${formatEuro(d.current)}`}/><i className="baseline" style={{width:`${d.previous3MonthAverage/max*100}%`}} title={`Media 3 meses ${formatEuro(d.previous3MonthAverage)}`}/></div></div>)}</div>}
function Heatmap({months}:{months:AnalysisMonth[]}){const max=Math.max(1,...months.map(m=>m.expenses));return <div className="analysis-heatmap" role="img" aria-label="Intensidad de gasto por mes">{months.map(m=><div key={m.month} className={m.available?"available":"empty"} style={{"--heat":String(clamp(m.expenses/max,0,1))} as React.CSSProperties} title={`${m.label}: ${formatEuro(m.expenses)}`}><span>{m.label.slice(0,3)}</span><strong>{m.available?formatEuro(m.expenses):"—"}</strong></div>)}</div>}

function DivergingNet({months}:{months:AnalysisMonth[]}){const shown=available(months);const max=Math.max(1,...shown.map(m=>Math.abs(m.net)));return <div className="analysis-diverging">{shown.map(m=>{const w=clamp(Math.abs(m.net)/max*48,1,48);return <div key={m.month}><span>{m.label.slice(0,3)}</span><div className="analysis-diverging-track"><i className={m.net>=0?"positive-bar":"negative-bar"} style={m.net>=0?{left:"50%",width:`${w}%`}:{right:"50%",width:`${w}%`}} title={`${m.label}: ${formatEuro(m.net)}`}/></div><strong className={m.net<0?"negative":"positive"}>{formatEuro(m.net)}</strong></div>})}</div>}
function AverageDeviation({months,metric}:{months:AnalysisMonth[];metric:"expenses"|"income"}){const shown=available(months);const mean=avg(shown.map(m=>m[metric]));const deltas=shown.map(m=>mean>0?(m[metric]-mean)/mean*100:0);const max=Math.max(1,...deltas.map(Math.abs));return <div className="analysis-average-deviation">{shown.map((m,i)=>{const d=deltas[i];const w=clamp(Math.abs(d)/max*48,1,48);return <div key={m.month}><span>{m.label.slice(0,3)}</span><div><i className={d>=0?"above":"below"} style={d>=0?{left:"50%",width:`${w}%`}:{right:"50%",width:`${w}%`}} title={`${formatSignedPercent(d,1)} frente a la media`}/></div><small>{formatSignedPercent(d,1)}</small></div>})}</div>}
function Pareto({items,aria}:{items:{label:string;value:number}[];aria:string}){const shown=items.slice(0,8);const total=Math.max(1,shown.reduce((s,i)=>s+i.value,0));const max=Math.max(1,...shown.map(i=>i.value));let cumulative=0;const width=720,height=250,pad=30,innerW=width-pad*2,innerH=height-70,step=innerW/Math.max(1,shown.length),barW=Math.max(12,step*.45);const pts=shown.map((item,i)=>{cumulative+=item.value;const x=pad+step*(i+.5),y=20+(1-cumulative/total)*innerH;return `${x},${y}`}).join(" ");return <div className="analysis-pareto"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={aria}>{shown.map((item,i)=>{const h=item.value/max*innerH,x=pad+step*(i+.5)-barW/2;return <g key={item.label}><rect x={x} y={20+innerH-h} width={barW} height={h} rx="4"><title>{`${item.label}: ${formatEuro(item.value)}`}</title></rect><text x={pad+step*(i+.5)} y={height-12} textAnchor="middle">{item.label.slice(0,8)}</text></g>})}<polyline points={pts}/></svg></div>}
function CategoryTreemap({categories}:{categories:AnalysisCategory[]}){const shown=categories.slice(0,10);return <div className="analysis-treemap" role="img" aria-label="Mapa proporcional del gasto por categorías">{shown.map((c,i)=><div key={c.category} className={`segment-${(i%6)+1}`} style={{flexGrow:Math.max(1,c.share),flexBasis:`${Math.max(110,c.share*8)}px`}} title={`${c.category}: ${formatEuro(c.amount)} · ${formatPercent(c.share,1)}`}><span>{c.category}</span><strong>{formatPercent(c.share,1)}</strong></div>)}</div>}
function AnnualWaterfall({income,expenses,net}:{income:number;expenses:number;net:number}){const width=720,height=250,pad=34;const max=Math.max(1,income,expenses,Math.abs(net));const scale=(v:number)=>Math.abs(v)/max*(height-70);const incomeH=scale(income),expenseH=scale(expenses),netH=scale(net);const base=height-32;const expenseTop=base-incomeH;const expenseBottom=expenseTop+expenseH;return <div className="analysis-waterfall"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Puente anual desde ingresos hasta Cash Flow"><line x1={pad} x2={width-pad} y1={base} y2={base}/><rect className="wf-income" x="80" y={base-incomeH} width="120" height={incomeH} rx="6"><title>{`Ingresos ${formatEuro(income)}`}</title></rect><rect className="wf-expense" x="300" y={expenseTop} width="120" height={expenseH} rx="6"><title>{`Gastos -${formatEuro(expenses)}`}</title></rect><rect className={net>=0?"wf-net-positive":"wf-net-negative"} x="520" y={net>=0?base-netH:base} width="120" height={netH} rx="6"><title>{`Cash Flow ${formatEuro(net)}`}</title></rect><line className="wf-bridge" x1="200" x2="300" y1={base-incomeH} y2={base-incomeH}/><line className="wf-bridge" x1="420" x2="520" y1={expenseBottom} y2={expenseBottom}/><text x="140" y={height-10} textAnchor="middle">Ingresos</text><text x="360" y={height-10} textAnchor="middle">Gastos</text><text x="580" y={height-10} textAnchor="middle">Cash Flow</text></svg></div>}

export function AnalysisVisualDashboard(props:Props){
  const [order,setOrder]=useState<ChartId[]>(DEFAULT_ORDER);const [hidden,setHidden]=useState<ChartId[]>([]);const [customizing,setCustomizing]=useState(false);const [status,setStatus]=useState("");const [hydrated,setHydrated]=useState(false);
  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const saved=JSON.parse(raw) as {order?:ChartId[];hidden?:ChartId[]};if(Array.isArray(saved.order)){const valid=saved.order.filter(id=>DEFAULT_ORDER.includes(id));setOrder([...valid,...DEFAULT_ORDER.filter(id=>!valid.includes(id))])}if(Array.isArray(saved.hidden))setHidden(saved.hidden.filter(id=>DEFAULT_ORDER.includes(id)))}}catch{setStatus("No se pudo recuperar la personalización guardada.")}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify({order,hidden}))}catch{setStatus("La personalización no se pudo guardar en este dispositivo.")}},[hydrated,order,hidden]);
  const visible=order.filter(id=>!hidden.includes(id));
  const reports=useMemo(()=>{const complete=props.months.filter(m=>m.available&&m.complete&&!m.partial);const last=complete.at(-1);const last3=complete.slice(-3);const avg3=last3.length?last3.reduce((s,m)=>s+m.expenses,0)/last3.length:0;const incomeChange=pct(props.income,props.priorIncome);const expenseChange=pct(props.expenses,props.priorExpenses);return [
    {label:"Último mes cerrado",value:last?formatEuro(last.net):"—",detail:last?`${last.label}: ${formatEuro(last.income)} ingresos · ${formatEuro(last.expenses)} gastos`:"Aún no hay un mes completo."},
    {label:"Media últimos 3 meses",value:last3.length?formatEuro(avg3):"—",detail:"Gasto mensual medio de los últimos meses completos disponibles."},
    {label:"Ingresos vs año anterior",value:incomeChange==null?"—":formatSignedPercent(incomeChange,1),detail:`Periodo homogéneo frente a ${props.comparisonYear}.`},
    {label:"Gastos vs año anterior",value:expenseChange==null?"—":formatSignedPercent(expenseChange,1),detail:`Periodo homogéneo frente a ${props.comparisonYear}.`},
    {label:"Tasa de ahorro media",value:formatPercent(props.insights.savingsRatePercent,1),detail:`Calculada con ${props.insights.sampleMonths} meses comparables.`},
    {label:"Concentración top 3",value:formatPercent(props.insights.top3CategorySharePercent,1),detail:"Peso de las tres categorías de mayor gasto."},
  ]},[props]);
  const move=(id:ChartId,offset:number)=>setOrder(current=>{const from=current.indexOf(id),to=from+offset;if(from<0||to<0||to>=current.length)return current;const copy=[...current];copy.splice(from,1);copy.splice(to,0,id);setStatus("Orden de gráficos actualizado.");return copy});
  const hide=(id:ChartId)=>{setHidden(v=>v.includes(id)?v:[...v,id]);setStatus(`${LABELS[id]} ocultado.`)};
  const restore=(id:ChartId)=>{setHidden(v=>v.filter(x=>x!==id));setStatus(`${LABELS[id]} visible de nuevo.`)};
  const reset=()=>{setOrder([...DEFAULT_ORDER]);setHidden([]);setStatus("Diseño de Análisis restablecido.")};
  const drop=(target:ChartId,source:ChartId)=>{if(source===target)return;setOrder(current=>{const copy=current.filter(id=>id!==source);copy.splice(copy.indexOf(target),0,source);return copy});setStatus("Orden de gráficos actualizado.")};
  const render=(id:ChartId)=>{switch(id){
    case "monthly-flow":return <MonthlyFlowChart months={props.months}/>;case "net-trend":return <LineChart values={available(props.months).map(m=>m.net)} secondary={available(props.months).map(m=>m.priorNet||0)} labels={available(props.months).map(m=>m.label)} aria={`Cash Flow mensual ${props.year} frente a ${props.comparisonYear}`}/>;
    case "income-trend":return <MetricTrend months={props.months} metric="income"/>;case "expense-trend":return <MetricTrend months={props.months} metric="expenses"/>;case "savings-rate":return <SavingsRateChart months={props.months}/>;case "expense-ratio":return <ExpenseRatio months={props.months}/>;
    case "cumulative-net":return <CumulativeNetChart months={props.months}/>;case "net-diverging":return <DivergingNet months={props.months}/>;case "income-prior":return <MetricTrend months={props.months} metric="income" prior/>;case "expense-prior":return <MetricTrend months={props.months} metric="expenses" prior/>;
    case "year-compare":return <YearCompare {...props}/>;case "annual-waterfall":return <AnnualWaterfall income={props.income} expenses={props.expenses} net={props.net}/>;case "rolling-expenses":return <RollingMetric months={props.months} metric="expenses"/>;case "rolling-net":return <RollingMetric months={props.months} metric="net"/>;
    case "expense-average":return <AverageDeviation months={props.months} metric="expenses"/>;case "income-average":return <AverageDeviation months={props.months} metric="income"/>;case "category-donut":return <CategoryDonut categories={props.categories}/>;case "category-bars":return <RankingBars kind="category" items={props.categories.slice(0,8).map(c=>({label:c.category,value:c.amount,meta:`${formatPercent(c.share,1)} · ${c.movements} movimientos`}))}/>;
    case "category-treemap":return <CategoryTreemap categories={props.categories}/>;case "category-pareto":return <Pareto aria="Pareto de categorías" items={props.categories.map(c=>({label:c.category,value:c.amount}))}/>;case "merchant-bars":return <RankingBars kind="merchant" items={props.merchants.slice(0,8).map(m=>({label:m.merchant,value:m.amount,meta:`${m.movements} movimientos`}))}/>;
    case "merchant-pareto":return <Pareto aria="Pareto de comercios" items={props.merchants.map(m=>({label:m.merchant,value:m.amount}))}/>;case "deviations":return <DeviationsChart deviations={props.deviations}/>;case "monthly-heatmap":return <Heatmap months={props.months}/>;
  }};
  return <section className="analysis-visual-section" aria-labelledby="analysis-visual-title">
    <div className="panel-head analysis-visual-toolbar"><div><p className="eyebrow">PANEL VISUAL</p><h2 id="analysis-visual-title">24 gráficos e informes rápidos</h2><p>La pantalla prioriza exploración visual: 24 gráficos calculados sobre la misma base financiera canónica, sin duplicar el motor de datos. Puedes ocultarlos y reordenarlos; tu diseño se conserva en este dispositivo.</p></div><div><button className="ghost" type="button" onClick={()=>setCustomizing(v=>!v)}>{customizing?"Cerrar personalización":"Personalizar gráficos"}</button><button className="ghost" type="button" onClick={reset}>Restablecer</button></div></div>
    {customizing&&<div className="analysis-viz-customizer" aria-label="Seleccionar gráficos">{DEFAULT_ORDER.map(id=><label key={id}><input type="checkbox" checked={!hidden.includes(id)} onChange={e=>e.target.checked?restore(id):hide(id)}/><span>{LABELS[id]}</span></label>)}</div>}
    <div className="analysis-quick-reports" aria-label="Informes rápidos">{reports.map(report=><article key={report.label}><span>{report.label}</span><strong>{report.value}</strong><small>{report.detail}</small></article>)}</div>
    <div className="analysis-viz-grid" onDragOver={e=>e.preventDefault()}>{visible.map((id,index)=><div key={id} onDrop={e=>{e.preventDefault();const source=e.dataTransfer.getData("text/plain") as ChartId;if(DEFAULT_ORDER.includes(source))drop(id,source)}}><ChartCard id={id} title={LABELS[id]} subtitle={id.includes("prior")||id==="net-trend"||id==="year-compare"?`${props.year} frente a ${props.comparisonYear}`:id==="deviations"?"Actual frente a media comparable de 3 meses":id.startsWith("rolling")?"Media móvil de 3 meses":"Lectura visual del periodo seleccionado"} onMove={move} onHide={hide} index={index} total={visible.length}>{render(id)}</ChartCard></div>)}</div>
    {hidden.length>0&&<div className="analysis-hidden-note"><span>{hidden.length} gráfico{hidden.length===1?"":"s"} oculto{hidden.length===1?"":"s"}.</span><button className="ghost" type="button" onClick={()=>setHidden([])}>Mostrar todos</button></div>}
    <p className="sr-only" role="status" aria-live="polite">{status}</p>
  </section>;
}
