-- Financial App 1.7.0 · arquitectura de carga, diagnóstico y backup portable
-- Migración aplicada como financial_app_17_architecture_foundation.

create or replace function financial_app.home_overview_core()
returns jsonb language plpgsql stable security definer
set search_path='pg_catalog','financial_app','auth'
as $$
declare v_email text;v_dashboard jsonb;v_accounts jsonb;v_budget jsonb;v_forecast jsonb;v_analysis jsonb;v_reconciliation jsonb;v_control jsonb;v_month date;v_year int;
begin
  v_email:=financial_app.authorized_email();if v_email is null then raise exception 'forbidden' using errcode='42501';end if;
  v_month:=date_trunc('month',current_date)::date;v_year:=extract(year from current_date)::int;
  v_dashboard:=financial_app.dashboard_rpc(v_month);v_accounts:=financial_app.accounts_core();v_budget:=financial_app.budget_month_core(v_month);v_forecast:=financial_app.forecast_overview_core(current_date,30);v_analysis:=financial_app.analysis_overview_core(v_year);v_reconciliation:=financial_app.reconciliation_overview_core();v_control:=financial_app.control_center_core(v_month);
  return jsonb_build_object('version',financial_app.current_app_version(),'dashboard',v_dashboard,'accounts',v_accounts,'budget',v_budget,'forecast',v_forecast,'analysis',v_analysis,'reconciliation',v_reconciliation,'controlSummary',jsonb_build_object('visibleAlerts',coalesce(jsonb_array_length(v_control->'alerts'),0),'hiddenAlerts',coalesce((v_control->>'hiddenAlertCount')::int,0),'closeReady',coalesce((v_control->'snapshot'->>'closeReady')::boolean,false),'closeBlockers',coalesce((v_control->'snapshot'->>'closeBlockers')::int,0),'closeWarnings',coalesce((v_control->'snapshot'->>'closeWarnings')::int,0)));
end$$;
create or replace function public.financial_app_home_overview() returns jsonb language sql stable set search_path='pg_catalog','financial_app','auth' as $$select financial_app.home_overview_core()$$;
revoke all on function public.financial_app_home_overview() from public,anon;grant execute on function public.financial_app_home_overview() to authenticated,service_role;
revoke all on function financial_app.home_overview_core() from public,anon;grant execute on function financial_app.home_overview_core() to authenticated,service_role;

create or replace function financial_app.portable_backup_core()
returns jsonb language plpgsql stable security definer set search_path='pg_catalog','financial_app','auth'
as $$
declare v_email text;v_source jsonb;
begin
  v_email:=financial_app.authorized_email();if v_email is null then raise exception 'forbidden' using errcode='42501';end if;select value into v_source from financial_app.app_meta where key='source';
  return jsonb_build_object('format','financial-app-private-backup','formatVersion',1,'appVersion',financial_app.current_app_version(),'createdAt',now(),'sourceFileId',v_source->>'file_id',
  'transactionOverrides',coalesce((select jsonb_agg(jsonb_build_object('sourceId',source_id,'categoryOverride',category_override,'subcategoryOverride',subcategory_override,'typeOverride',type_override,'normalizedConceptOverride',normalized_concept_override,'counterpartyOverride',counterparty_override,'descriptionOverride',description_override,'effectiveDate',effective_date,'cashFlowOverride',cash_flow_override,'isInternalTransfer',is_internal_transfer,'isDuplicate',is_duplicate,'isReconciled',is_reconciled,'needsReview',needs_review,'isRecurring',is_recurring,'tags',tags,'notes',notes,'personalAmountOverride',personal_amount_override)) from financial_app.transactions where category_override is not null or subcategory_override is not null or type_override is not null or normalized_concept_override is not null or counterparty_override is not null or description_override is not null or effective_date is not null or cash_flow_override is not null or is_internal_transfer or is_duplicate or is_reconciled is not null or needs_review or is_recurring is not null or cardinality(tags)>0 or notes is not null or personal_amount_override is not null),'[]'::jsonb),
  'splits',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.transaction_splits x),'[]'::jsonb),'budgets',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.budgets x),'[]'::jsonb),'forecasts',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.forecasts x),'[]'::jsonb),'netWorthItems',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.net_worth_items x),'[]'::jsonb),'goals',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.goals x),'[]'::jsonb),'rules',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.transaction_rules x),'[]'::jsonb),'reconciliationPairs',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.reconciliation_pairs x),'[]'::jsonb),'preferences',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.preferences x),'[]'::jsonb),'controlAlertStates',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.control_alert_states x),'[]'::jsonb),'monthCloses',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.month_closes x),'[]'::jsonb),'documents',coalesce((select jsonb_agg(to_jsonb(x)-'ocr_text') from financial_app.documents x),'[]'::jsonb),'transactionDocuments',coalesce((select jsonb_agg(to_jsonb(x)) from financial_app.transaction_documents x),'[]'::jsonb),'audit',jsonb_build_object('transactionHistoryRows',(select count(*) from financial_app.transaction_history),'ruleHistoryRows',(select count(*) from financial_app.transaction_rule_history)));
end$$;
create or replace function financial_app.validate_portable_backup_core(p_backup jsonb) returns jsonb language plpgsql stable security definer set search_path='pg_catalog','financial_app','auth' as $$declare v_email text;v_source jsonb;v_errors jsonb:='[]'::jsonb;v_sections text[]:=array['transactionOverrides','splits','budgets','forecasts','netWorthItems','goals','rules','reconciliationPairs','preferences','controlAlertStates','monthCloses','documents','transactionDocuments'];v_key text;begin v_email:=financial_app.authorized_email();if v_email is null then raise exception 'forbidden' using errcode='42501';end if;select value into v_source from financial_app.app_meta where key='source';if coalesce(p_backup->>'format','')<>'financial-app-private-backup' then v_errors:=v_errors||jsonb_build_array('invalid_format');end if;if coalesce((p_backup->>'formatVersion')::int,0)<>1 then v_errors:=v_errors||jsonb_build_array('unsupported_format_version');end if;if coalesce(p_backup->>'sourceFileId','') is distinct from coalesce(v_source->>'file_id','') then v_errors:=v_errors||jsonb_build_array('source_file_mismatch');end if;foreach v_key in array v_sections loop if jsonb_typeof(p_backup->v_key) is distinct from 'array' then v_errors:=v_errors||jsonb_build_array('invalid_section:'||v_key);end if;end loop;return jsonb_build_object('ok',jsonb_array_length(v_errors)=0,'errors',v_errors,'formatVersion',p_backup->>'formatVersion','backupAppVersion',p_backup->>'appVersion','currentAppVersion',financial_app.current_app_version(),'sourceMatches',coalesce(p_backup->>'sourceFileId','')=coalesce(v_source->>'file_id',''));end$$;
create or replace function public.financial_app_backup_export() returns jsonb language sql stable set search_path='pg_catalog','financial_app','auth' as $$select financial_app.portable_backup_core()$$;
create or replace function public.financial_app_backup_validate(p_backup jsonb) returns jsonb language sql stable set search_path='pg_catalog','financial_app','auth' as $$select financial_app.validate_portable_backup_core(p_backup)$$;
revoke all on function public.financial_app_backup_export() from public,anon;revoke all on function public.financial_app_backup_validate(jsonb) from public,anon;grant execute on function public.financial_app_backup_export() to authenticated,service_role;grant execute on function public.financial_app_backup_validate(jsonb) to authenticated,service_role;
