-- Financial App 0.8.0 · versionado dinámico del panel
create or replace function financial_app.dashboard_rpc(p_month date default date_trunc('month',now())::date) returns jsonb language plpgsql stable security definer set search_path='pg_catalog','financial_app','auth' as $$
declare v_start date:=date_trunc('month',p_month)::date;v_end date:=(date_trunc('month',p_month)+interval '1 month')::date;v_accounts jsonb;v_total numeric:=0;v_income numeric:=0;v_expenses numeric:=0;v_cash_flow numeric:=0;v_review integer:=0;v_review_source integer:=0;v_movements integer:=0;v_last_date date;v_sync jsonb;v_version text:='0.8.0';
begin
  if financial_app.authorized_email() is null then raise exception 'forbidden' using errcode='42501';end if;
  select coalesce(value #>> '{}','0.8.0') into v_version from financial_app.app_meta where key='schema_version';
  with account_balances as(select a.id,a.name,a.external_identifier,a.account_role,a.cash_flow_enabled,b.source_balance balance,b.source_date balance_date from financial_app.accounts a left join lateral(select t.source_balance,t.source_date from financial_app.transactions t where t.source_identifier=a.external_identifier and t.source_missing=false and t.source_balance is not null order by t.source_date desc nulls last,t.source_time desc nulls last,t.source_id desc limit 1)b on true where a.active=true) select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'identifier',external_identifier,'role',account_role,'cashFlowEnabled',cash_flow_enabled,'balance',balance,'balanceDate',balance_date) order by case when account_role='operating' then 0 when account_role='savings' then 1 else 2 end,name),'[]'::jsonb),coalesce(sum(balance),0) into v_accounts,v_total from account_balances;
  with eligible as(select t.source_amount from financial_app.transactions t join financial_app.accounts a on a.id=t.account_id where coalesce(t.effective_date,t.source_date)>=v_start and coalesce(t.effective_date,t.source_date)<v_end and t.source_missing=false and t.is_duplicate=false and t.is_internal_transfer=false and a.account_role<>'savings' and a.cash_flow_enabled=true and t.cash_flow_override is distinct from false) select coalesce(sum(source_amount) filter(where source_amount>0),0),coalesce(abs(sum(source_amount) filter(where source_amount<0)),0),coalesce(sum(source_amount),0) into v_income,v_expenses,v_cash_flow from eligible;
  select count(*),count(*) filter(where needs_review=true),count(*) filter(where status='review_source'),max(coalesce(effective_date,source_date)) into v_movements,v_review,v_review_source,v_last_date from financial_app.transactions;
  select jsonb_build_object('id',id,'startedAt',started_at,'finishedAt',finished_at,'sourceFileId',source_file_id,'sourceModifiedAt',source_modified_at,'status',status,'newCount',new_count,'updatedCount',updated_count,'reviewCount',review_count,'error',error_message) into v_sync from financial_app.sync_runs where source_file_id is not null order by started_at desc limit 1;
  return jsonb_build_object('version',v_version,'month',to_char(v_start,'YYYY-MM'),'accounts',v_accounts,'totalAvailable',v_total,'income',v_income,'expenses',v_expenses,'cashFlow',v_cash_flow,'movementsTotal',v_movements,'needsReview',v_review,'reviewSource',v_review_source,'lastMovementDate',v_last_date,'sync',v_sync);
end $$;
