-- Financial App 1.6.0 · motor privado de reglas automáticas y reversibles
-- Estado canónico reproducible. Nunca modifica las columnas source_* del origen bancario.

create table if not exists financial_app.transaction_rules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  active boolean not null default true,
  priority integer not null default 100 check(priority between 1 and 9999),
  match_counterparty text,
  counterparty_operator text not null default 'contains' check(counterparty_operator in ('contains','equals')),
  match_concept text,
  concept_operator text not null default 'contains' check(concept_operator in ('contains','equals')),
  match_type text,
  match_category text,
  match_account_id uuid references financial_app.accounts(id) on delete set null,
  amount_min numeric check(amount_min is null or amount_min>=0),
  amount_max numeric check(amount_max is null or amount_max>=0),
  direction text not null default 'any' check(direction in ('any','income','expense')),
  set_category text,
  set_subcategory text,
  add_tags text[] not null default array[]::text[],
  set_recurring boolean,
  stop_processing boolean not null default true,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(amount_min is null or amount_max is null or amount_min<=amount_max),
  check(nullif(btrim(coalesce(match_counterparty,'')),'') is not null or nullif(btrim(coalesce(match_concept,'')),'') is not null or nullif(btrim(coalesce(match_type,'')),'') is not null or nullif(btrim(coalesce(match_category,'')),'') is not null or match_account_id is not null or amount_min is not null or amount_max is not null or direction<>'any'),
  check(nullif(btrim(coalesce(set_category,'')),'') is not null or nullif(btrim(coalesce(set_subcategory,'')),'') is not null or cardinality(add_tags)>0 or set_recurring is not null)
);

create table if not exists financial_app.transaction_rule_history (
  id bigint generated by default as identity primary key,
  rule_id uuid not null references financial_app.transaction_rules(id) on delete cascade,
  action text not null check(action in ('created','updated','deactivated','reactivated')),
  before_state jsonb,
  after_state jsonb,
  changed_by text,
  changed_at timestamptz not null default now()
);

create table if not exists financial_app.transaction_rule_applications (
  id bigint generated by default as identity primary key,
  rule_id uuid not null references financial_app.transaction_rules(id) on delete cascade,
  transaction_id uuid not null references financial_app.transactions(id) on delete cascade,
  changes jsonb not null,
  application_origin text not null check(application_origin in ('rule_auto','rule_manual')),
  applied_by text,
  applied_at timestamptz not null default now(),
  reverted_at timestamptz,
  reverted_by text,
  revert_result jsonb
);

alter table financial_app.transaction_rules enable row level security;
alter table financial_app.transaction_rule_history enable row level security;
alter table financial_app.transaction_rule_applications enable row level security;
revoke all on financial_app.transaction_rules,financial_app.transaction_rule_history,financial_app.transaction_rule_applications from anon,authenticated;

create index if not exists transaction_rules_active_priority_idx on financial_app.transaction_rules(active,priority,created_at);
create index if not exists transaction_rule_history_rule_idx on financial_app.transaction_rule_history(rule_id,changed_at desc);
create index if not exists transaction_rule_applications_rule_idx on financial_app.transaction_rule_applications(rule_id,applied_at desc);
create index if not exists transaction_rule_applications_transaction_idx on financial_app.transaction_rule_applications(transaction_id,applied_at desc);
create unique index if not exists transaction_rule_applications_active_unique on financial_app.transaction_rule_applications(rule_id,transaction_id) where reverted_at is null;

create or replace function financial_app.normalize_rule_definition_core(p_rule jsonb)
returns jsonb language plpgsql stable security definer
set search_path to 'pg_catalog','financial_app'
as $$
declare
  v_name text:=nullif(btrim(coalesce(p_rule->>'name','')),'');
  v_priority int:=coalesce(nullif(p_rule->>'priority','')::int,100);
  v_counterparty text:=nullif(btrim(coalesce(p_rule->>'match_counterparty','')),'');
  v_counterparty_operator text:=lower(coalesce(nullif(btrim(p_rule->>'counterparty_operator'),''),'contains'));
  v_concept text:=nullif(btrim(coalesce(p_rule->>'match_concept','')),'');
  v_concept_operator text:=lower(coalesce(nullif(btrim(p_rule->>'concept_operator'),''),'contains'));
  v_type text:=nullif(btrim(coalesce(p_rule->>'match_type','')),'');
  v_category text:=nullif(btrim(coalesce(p_rule->>'match_category','')),'');
  v_account uuid:=case when nullif(btrim(coalesce(p_rule->>'match_account_id','')),'') is null then null else (p_rule->>'match_account_id')::uuid end;
  v_min numeric:=case when p_rule->>'amount_min' is null or btrim(p_rule->>'amount_min')='' then null else (p_rule->>'amount_min')::numeric end;
  v_max numeric:=case when p_rule->>'amount_max' is null or btrim(p_rule->>'amount_max')='' then null else (p_rule->>'amount_max')::numeric end;
  v_direction text:=lower(coalesce(nullif(btrim(p_rule->>'direction'),''),'any'));
  v_set_category text:=nullif(btrim(coalesce(p_rule->>'set_category','')),'');
  v_set_subcategory text:=nullif(btrim(coalesce(p_rule->>'set_subcategory','')),'');
  v_tags text[]:=array[]::text[];
  v_recurring boolean:=case when not (p_rule ? 'set_recurring') or p_rule->'set_recurring'='null'::jsonb then null else (p_rule->>'set_recurring')::boolean end;
  v_stop boolean:=coalesce((p_rule->>'stop_processing')::boolean,true);
begin
  if v_name is null then raise exception 'rule_name_required'; end if;
  if char_length(v_name)>120 then raise exception 'rule_name_too_long'; end if;
  if v_priority<1 or v_priority>9999 then raise exception 'rule_priority_invalid'; end if;
  if v_counterparty_operator not in ('contains','equals') then raise exception 'counterparty_operator_invalid'; end if;
  if v_concept_operator not in ('contains','equals') then raise exception 'concept_operator_invalid'; end if;
  if v_direction not in ('any','income','expense') then raise exception 'rule_direction_invalid'; end if;
  if v_min is not null and v_min<0 then raise exception 'amount_min_invalid'; end if;
  if v_max is not null and v_max<0 then raise exception 'amount_max_invalid'; end if;
  if v_min is not null and v_max is not null and v_min>v_max then raise exception 'amount_range_invalid'; end if;
  if p_rule ? 'add_tags' and p_rule->'add_tags'<>'null'::jsonb then
    if jsonb_typeof(p_rule->'add_tags')<>'array' then raise exception 'rule_tags_invalid'; end if;
    select coalesce(array_agg(distinct btrim(value) order by btrim(value)),array[]::text[]) into v_tags
    from jsonb_array_elements_text(p_rule->'add_tags') where nullif(btrim(value),'') is not null;
  end if;
  if v_counterparty is null and v_concept is null and v_type is null and v_category is null and v_account is null and v_min is null and v_max is null and v_direction='any' then raise exception 'rule_condition_required'; end if;
  if v_set_category is null and v_set_subcategory is null and cardinality(v_tags)=0 and v_recurring is null then raise exception 'rule_action_required'; end if;
  return jsonb_build_object('name',v_name,'priority',v_priority,'match_counterparty',v_counterparty,'counterparty_operator',v_counterparty_operator,'match_concept',v_concept,'concept_operator',v_concept_operator,'match_type',v_type,'match_category',v_category,'match_account_id',v_account,'amount_min',v_min,'amount_max',v_max,'direction',v_direction,'set_category',v_set_category,'set_subcategory',v_set_subcategory,'add_tags',to_jsonb(v_tags),'set_recurring',to_jsonb(v_recurring),'stop_processing',v_stop);
end$$;

create or replace function financial_app.rule_matches_transaction_core(p_rule jsonb,p_tx financial_app.transactions)
returns boolean language plpgsql stable security definer
set search_path to 'pg_catalog','financial_app'
as $$
declare
  v_counterparty text:=coalesce(nullif(p_tx.counterparty_override,''),nullif(p_tx.source_counterparty,''),nullif(p_tx.normalized_concept_override,''),nullif(p_tx.source_normalized_concept,''),nullif(p_tx.source_original_concept,''),'');
  v_concept text:=coalesce(nullif(p_tx.normalized_concept_override,''),nullif(p_tx.source_normalized_concept,''),nullif(p_tx.source_original_concept,''),'');
  v_type text:=coalesce(nullif(p_tx.type_override,''),nullif(p_tx.source_transaction_type,''),'');
  v_category text:=coalesce(nullif(p_tx.category_override,''),nullif(p_tx.source_category,''),'');
  v_amount numeric:=abs(coalesce(p_tx.source_amount,0));v_expected text;
begin
  if p_tx.source_missing or p_tx.is_duplicate then return false; end if;
  if nullif(p_rule->>'match_account_id','') is not null and p_tx.account_id is distinct from (p_rule->>'match_account_id')::uuid then return false; end if;
  if nullif(p_rule->>'match_counterparty','') is not null then v_expected:=lower(p_rule->>'match_counterparty');if p_rule->>'counterparty_operator'='equals' then if lower(v_counterparty)<>v_expected then return false;end if;elsif position(v_expected in lower(v_counterparty))=0 then return false;end if;end if;
  if nullif(p_rule->>'match_concept','') is not null then v_expected:=lower(p_rule->>'match_concept');if p_rule->>'concept_operator'='equals' then if lower(v_concept)<>v_expected then return false;end if;elsif position(v_expected in lower(v_concept))=0 then return false;end if;end if;
  if nullif(p_rule->>'match_type','') is not null and lower(v_type)<>lower(p_rule->>'match_type') then return false; end if;
  if nullif(p_rule->>'match_category','') is not null and lower(v_category)<>lower(p_rule->>'match_category') then return false; end if;
  if p_rule->>'amount_min' is not null and v_amount<(p_rule->>'amount_min')::numeric then return false; end if;
  if p_rule->>'amount_max' is not null and v_amount>(p_rule->>'amount_max')::numeric then return false; end if;
  if p_rule->>'direction'='income' and coalesce(p_tx.source_amount,0)<=0 then return false; end if;
  if p_rule->>'direction'='expense' and coalesce(p_tx.source_amount,0)>=0 then return false; end if;
  return true;
end$$;

create or replace function financial_app.rule_candidate_changes_core(p_rule jsonb,p_tx financial_app.transactions)
returns jsonb language plpgsql stable security definer
set search_path to 'pg_catalog','financial_app'
as $$
declare v_changes jsonb:='{}'::jsonb;v_after_tags text[];v_set text;
begin
  v_set:=nullif(p_rule->>'set_category','');
  if v_set is not null and p_tx.category_override is null and coalesce(p_tx.source_category,'') is distinct from v_set then v_changes:=v_changes||jsonb_build_object('category',jsonb_build_object('before',to_jsonb(p_tx.category_override),'after',to_jsonb(v_set),'origin',to_jsonb(p_tx.source_category)));end if;
  v_set:=nullif(p_rule->>'set_subcategory','');
  if v_set is not null and p_tx.subcategory_override is null and coalesce(p_tx.source_subcategory,'') is distinct from v_set then v_changes:=v_changes||jsonb_build_object('subcategory',jsonb_build_object('before',to_jsonb(p_tx.subcategory_override),'after',to_jsonb(v_set),'origin',to_jsonb(p_tx.source_subcategory)));end if;
  if p_rule->'add_tags' is not null and jsonb_array_length(coalesce(p_rule->'add_tags','[]'::jsonb))>0 then select coalesce(array_agg(distinct x order by x),array[]::text[]) into v_after_tags from unnest(coalesce(p_tx.tags,array[]::text[])||array(select jsonb_array_elements_text(p_rule->'add_tags'))) x where nullif(btrim(x),'') is not null;if v_after_tags is distinct from p_tx.tags then v_changes:=v_changes||jsonb_build_object('tags',jsonb_build_object('before',to_jsonb(p_tx.tags),'after',to_jsonb(v_after_tags),'origin','null'::jsonb));end if;end if;
  if p_rule ? 'set_recurring' and p_rule->'set_recurring'<>'null'::jsonb and p_tx.is_recurring is null then v_changes:=v_changes||jsonb_build_object('isRecurring',jsonb_build_object('before',to_jsonb(p_tx.is_recurring),'after',to_jsonb((p_rule->>'set_recurring')::boolean),'origin','null'::jsonb));end if;
  return v_changes;
end$$;

create or replace function financial_app.apply_rule_to_transaction_internal(p_rule_id uuid,p_transaction_id uuid,p_origin text,p_actor text)
returns jsonb language plpgsql security definer
set search_path to 'pg_catalog','financial_app'
as $$
declare v_rule financial_app.transaction_rules%rowtype;v_tx financial_app.transactions%rowtype;v_def jsonb;v_changes jsonb;v_item record;v_tags text[];
begin
  select * into v_rule from financial_app.transaction_rules where id=p_rule_id;if not found then return jsonb_build_object('matched',false,'applied',false,'reason','rule_not_found');end if;
  select * into v_tx from financial_app.transactions where id=p_transaction_id for update;if not found then return jsonb_build_object('matched',false,'applied',false,'reason','transaction_not_found');end if;
  v_def:=jsonb_build_object('name',v_rule.name,'priority',v_rule.priority,'match_counterparty',v_rule.match_counterparty,'counterparty_operator',v_rule.counterparty_operator,'match_concept',v_rule.match_concept,'concept_operator',v_rule.concept_operator,'match_type',v_rule.match_type,'match_category',v_rule.match_category,'match_account_id',v_rule.match_account_id,'amount_min',v_rule.amount_min,'amount_max',v_rule.amount_max,'direction',v_rule.direction,'set_category',v_rule.set_category,'set_subcategory',v_rule.set_subcategory,'add_tags',to_jsonb(v_rule.add_tags),'set_recurring',to_jsonb(v_rule.set_recurring),'stop_processing',v_rule.stop_processing);
  if not financial_app.rule_matches_transaction_core(v_def,v_tx) then return jsonb_build_object('matched',false,'applied',false,'reason','no_match');end if;
  if exists(select 1 from financial_app.transaction_rule_applications where rule_id=p_rule_id and transaction_id=p_transaction_id and reverted_at is null) then return jsonb_build_object('matched',true,'applied',false,'reason','already_applied');end if;
  v_changes:=financial_app.rule_candidate_changes_core(v_def,v_tx);if v_changes='{}'::jsonb then return jsonb_build_object('matched',true,'applied',false,'reason','no_changes');end if;
  if v_changes ? 'category' then v_tx.category_override:=v_changes#>>'{category,after}';end if;if v_changes ? 'subcategory' then v_tx.subcategory_override:=v_changes#>>'{subcategory,after}';end if;if v_changes ? 'tags' then select array_agg(value order by value) into v_tags from jsonb_array_elements_text(v_changes#>'{tags,after}');v_tx.tags:=coalesce(v_tags,array[]::text[]);end if;if v_changes ? 'isRecurring' then v_tx.is_recurring:=(v_changes#>>'{isRecurring,after}')::boolean;end if;
  update financial_app.transactions set category_override=v_tx.category_override,subcategory_override=v_tx.subcategory_override,tags=v_tx.tags,is_recurring=v_tx.is_recurring,updated_at=now() where id=p_transaction_id;
  for v_item in select key,value from jsonb_each(v_changes) loop insert into financial_app.transaction_history(transaction_id,field_name,value_origin,value_before,value_after,change_origin,changed_by) values(p_transaction_id,'app.'||v_item.key,v_item.value->'origin',v_item.value->'before',v_item.value->'after',p_origin,p_actor);end loop;
  insert into financial_app.transaction_rule_applications(rule_id,transaction_id,changes,application_origin,applied_by) values(p_rule_id,p_transaction_id,v_changes,p_origin,p_actor);
  return jsonb_build_object('matched',true,'applied',true,'changes',v_changes,'stopProcessing',v_rule.stop_processing);
end$$;

create or replace function financial_app.apply_rules_after_insert_trigger()
returns trigger language plpgsql security definer
set search_path to 'pg_catalog','financial_app'
as $$
declare v_rule record;v_result jsonb;
begin
  for v_rule in select id,created_by,stop_processing from financial_app.transaction_rules where active=true order by priority asc,created_at asc loop
    v_result:=financial_app.apply_rule_to_transaction_internal(v_rule.id,new.id,'rule_auto',v_rule.created_by);
    if coalesce((v_result->>'applied')::boolean,false) and v_rule.stop_processing then exit;end if;
  end loop;
  return new;
end$$;

drop trigger if exists transactions_apply_rules_after_insert on financial_app.transactions;
create trigger transactions_apply_rules_after_insert after insert on financial_app.transactions for each row execute function financial_app.apply_rules_after_insert_trigger();

create or replace function financial_app.rule_field_has_later_user_edit(p_transaction_id uuid,p_field text,p_after timestamptz)
returns boolean language sql stable security definer
set search_path to 'pg_catalog','financial_app'
as $$select exists(select 1 from financial_app.transaction_history h where h.transaction_id=p_transaction_id and h.field_name='app.'||p_field and h.changed_at>p_after and h.change_origin='user_edit')$$;

create or replace function financial_app.rules_overview_core()
returns jsonb language plpgsql stable security definer
set search_path to 'pg_catalog','financial_app','auth'
as $$
declare v_email text:=financial_app.authorized_email();v_rules jsonb;v_accounts jsonb;v_summary jsonb;
begin
  if v_email is null then raise exception 'forbidden' using errcode='42501';end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'name',r.name,'active',r.active,'priority',r.priority,'stopProcessing',r.stop_processing,'conditions',jsonb_build_object('counterparty',r.match_counterparty,'counterpartyOperator',r.counterparty_operator,'concept',r.match_concept,'conceptOperator',r.concept_operator,'type',r.match_type,'category',r.match_category,'accountId',r.match_account_id,'amountMin',r.amount_min,'amountMax',r.amount_max,'direction',r.direction),'actions',jsonb_build_object('category',r.set_category,'subcategory',r.set_subcategory,'addTags',to_jsonb(r.add_tags),'recurring',to_jsonb(r.set_recurring)),'applicationCount',coalesce(a.application_count,0),'activeApplicationCount',coalesce(a.active_application_count,0),'lastAppliedAt',a.last_applied_at,'createdAt',r.created_at,'updatedAt',r.updated_at) order by r.priority asc,r.created_at asc),'[]'::jsonb) into v_rules
  from financial_app.transaction_rules r left join lateral(select count(*)::int application_count,count(*) filter(where x.reverted_at is null)::int active_application_count,max(x.applied_at) last_applied_at from financial_app.transaction_rule_applications x where x.rule_id=r.id)a on true;
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'identifier',external_identifier) order by name),'[]'::jsonb) into v_accounts from financial_app.accounts where active=true;
  select jsonb_build_object('totalRules',count(*),'activeRules',count(*) filter(where active),'totalApplications',coalesce(sum((select count(*) from financial_app.transaction_rule_applications a where a.rule_id=r.id and a.reverted_at is null)),0)) into v_summary from financial_app.transaction_rules r;
  return jsonb_build_object('version',financial_app.current_app_version(),'rules',v_rules,'accounts',v_accounts,'summary',v_summary,'guardrails',jsonb_build_object('sourceUntouched',true,'manualOverridesProtected',true,'duplicatesExcluded',true,'sourceMissingExcluded',true));
end$$;

create or replace function financial_app.upsert_rule_core(p_rule_id uuid,p_rule jsonb)
returns jsonb language plpgsql security definer
set search_path to 'pg_catalog','financial_app','auth'
as $$
declare v_email text:=financial_app.authorized_email();v_def jsonb;v_id uuid;v_before jsonb;v_after jsonb;v_was_active boolean;
begin
  if v_email is null then raise exception 'forbidden' using errcode='42501';end if;v_def:=financial_app.normalize_rule_definition_core(p_rule);
  if p_rule_id is null then
    insert into financial_app.transaction_rules(name,priority,match_counterparty,counterparty_operator,match_concept,concept_operator,match_type,match_category,match_account_id,amount_min,amount_max,direction,set_category,set_subcategory,add_tags,set_recurring,stop_processing,created_by)
    values(v_def->>'name',(v_def->>'priority')::int,v_def->>'match_counterparty',v_def->>'counterparty_operator',v_def->>'match_concept',v_def->>'concept_operator',v_def->>'match_type',v_def->>'match_category',nullif(v_def->>'match_account_id','')::uuid,nullif(v_def->>'amount_min','')::numeric,nullif(v_def->>'amount_max','')::numeric,v_def->>'direction',v_def->>'set_category',v_def->>'set_subcategory',array(select jsonb_array_elements_text(v_def->'add_tags')),case when v_def->'set_recurring'='null'::jsonb then null else (v_def->>'set_recurring')::boolean end,(v_def->>'stop_processing')::boolean,v_email) returning id into v_id;
    select to_jsonb(r) into v_after from financial_app.transaction_rules r where id=v_id;insert into financial_app.transaction_rule_history(rule_id,action,before_state,after_state,changed_by) values(v_id,'created',null,v_after,v_email);
  else
    select to_jsonb(r),r.active into v_before,v_was_active from financial_app.transaction_rules r where id=p_rule_id for update;if v_before is null then raise exception 'rule_not_found' using errcode='P0002';end if;
    update financial_app.transaction_rules set name=v_def->>'name',priority=(v_def->>'priority')::int,match_counterparty=v_def->>'match_counterparty',counterparty_operator=v_def->>'counterparty_operator',match_concept=v_def->>'match_concept',concept_operator=v_def->>'concept_operator',match_type=v_def->>'match_type',match_category=v_def->>'match_category',match_account_id=nullif(v_def->>'match_account_id','')::uuid,amount_min=nullif(v_def->>'amount_min','')::numeric,amount_max=nullif(v_def->>'amount_max','')::numeric,direction=v_def->>'direction',set_category=v_def->>'set_category',set_subcategory=v_def->>'set_subcategory',add_tags=array(select jsonb_array_elements_text(v_def->'add_tags')),set_recurring=case when v_def->'set_recurring'='null'::jsonb then null else (v_def->>'set_recurring')::boolean end,stop_processing=(v_def->>'stop_processing')::boolean,active=coalesce(case when p_rule ? 'active' then (p_rule->>'active')::boolean else null end,active),updated_at=now() where id=p_rule_id;
    v_id:=p_rule_id;select to_jsonb(r) into v_after from financial_app.transaction_rules r where id=v_id;insert into financial_app.transaction_rule_history(rule_id,action,before_state,after_state,changed_by) values(v_id,case when not v_was_active and (v_after->>'active')::boolean then 'reactivated' else 'updated' end,v_before,v_after,v_email);
  end if;
  return jsonb_build_object('ok',true,'id',v_id,'overview',financial_app.rules_overview_core());
end$$;

create or replace function financial_app.preview_rule_core(p_rule jsonb,p_limit integer default 8)
returns jsonb language plpgsql stable security definer
set search_path to 'pg_catalog','financial_app','auth'
as $$
declare v_email text:=financial_app.authorized_email();v_def jsonb;v_count int;v_changeable int;v_samples jsonb;
begin
  if v_email is null then raise exception 'forbidden' using errcode='42501';end if;v_def:=financial_app.normalize_rule_definition_core(p_rule);
  with matches as materialized(select t.*,financial_app.rule_candidate_changes_core(v_def,t) changes from financial_app.transactions t where financial_app.rule_matches_transaction_core(v_def,t))
  select count(*)::int,count(*) filter(where changes<>'{}'::jsonb)::int,coalesce(jsonb_agg(jsonb_build_object('id',id,'date',coalesce(effective_date,source_date),'amount',source_amount,'counterparty',coalesce(counterparty_override,source_counterparty,source_normalized_concept,source_original_concept),'concept',coalesce(normalized_concept_override,source_normalized_concept,source_original_concept),'category',coalesce(category_override,source_category),'subcategory',coalesce(subcategory_override,source_subcategory),'changes',changes) order by coalesce(effective_date,source_date) desc nulls last,id desc) filter(where rn<=greatest(1,least(coalesce(p_limit,8),20))),'[]'::jsonb) into v_count,v_changeable,v_samples
  from(select m.*,row_number() over(order by coalesce(effective_date,source_date) desc nulls last,id desc) rn from matches m where changes<>'{}'::jsonb)s;
  return jsonb_build_object('matched',coalesce(v_count,0),'changeable',coalesce(v_changeable,0),'samples',coalesce(v_samples,'[]'::jsonb),'definition',v_def);
end$$;

create or replace function financial_app.apply_rule_existing_core(p_rule_id uuid)
returns jsonb language plpgsql security definer
set search_path to 'pg_catalog','financial_app','auth'
as $$
declare v_email text:=financial_app.authorized_email();v_rule financial_app.transaction_rules%rowtype;v_def jsonb;v_tx record;v_result jsonb;v_matched int:=0;v_applied int:=0;v_no_changes int:=0;
begin
  if v_email is null then raise exception 'forbidden' using errcode='42501';end if;select * into v_rule from financial_app.transaction_rules where id=p_rule_id;if not found then raise exception 'rule_not_found' using errcode='P0002';end if;
  v_def:=jsonb_build_object('name',v_rule.name,'priority',v_rule.priority,'match_counterparty',v_rule.match_counterparty,'counterparty_operator',v_rule.counterparty_operator,'match_concept',v_rule.match_concept,'concept_operator',v_rule.concept_operator,'match_type',v_rule.match_type,'match_category',v_rule.match_category,'match_account_id',v_rule.match_account_id,'amount_min',v_rule.amount_min,'amount_max',v_rule.amount_max,'direction',v_rule.direction,'set_category',v_rule.set_category,'set_subcategory',v_rule.set_subcategory,'add_tags',to_jsonb(v_rule.add_tags),'set_recurring',to_jsonb(v_rule.set_recurring),'stop_processing',v_rule.stop_processing);
  for v_tx in select t.id from financial_app.transactions t where financial_app.rule_matches_transaction_core(v_def,t) order by coalesce(t.effective_date,t.source_date),t.id limit 5000 loop v_matched:=v_matched+1;v_result:=financial_app.apply_rule_to_transaction_internal(p_rule_id,v_tx.id,'rule_manual',v_email);if coalesce((v_result->>'applied')::boolean,false) then v_applied:=v_applied+1;else v_no_changes:=v_no_changes+1;end if;end loop;
  return jsonb_build_object('ok',true,'matched',v_matched,'applied',v_applied,'unchanged',v_no_changes,'capped',v_matched>=5000,'overview',financial_app.rules_overview_core());
end$$;

create or replace function financial_app.deactivate_rule_core(p_rule_id uuid)
returns jsonb language plpgsql security definer
set search_path to 'pg_catalog','financial_app','auth'
as $$
declare v_email text:=financial_app.authorized_email();v_before jsonb;v_after jsonb;
begin
  if v_email is null then raise exception 'forbidden' using errcode='42501';end if;select to_jsonb(r) into v_before from financial_app.transaction_rules r where id=p_rule_id for update;if v_before is null then raise exception 'rule_not_found' using errcode='P0002';end if;update financial_app.transaction_rules set active=false,updated_at=now() where id=p_rule_id;select to_jsonb(r) into v_after from financial_app.transaction_rules r where id=p_rule_id;if (v_before->>'active')::boolean then insert into financial_app.transaction_rule_history(rule_id,action,before_state,after_state,changed_by) values(p_rule_id,'deactivated',v_before,v_after,v_email);end if;return jsonb_build_object('ok',true,'id',p_rule_id,'overview',financial_app.rules_overview_core());
end$$;

create or replace function financial_app.revert_rule_applications_core(p_rule_id uuid)
returns jsonb language plpgsql security definer
set search_path to 'pg_catalog','financial_app','auth'
as $$
declare v_email text:=financial_app.authorized_email();v_app record;v_tx financial_app.transactions%rowtype;v_entry record;v_reverted jsonb;v_skipped jsonb;v_total int:=0;v_fields int:=0;v_before jsonb;v_after jsonb;v_tags text[];
begin
  if v_email is null then raise exception 'forbidden' using errcode='42501';end if;if not exists(select 1 from financial_app.transaction_rules where id=p_rule_id) then raise exception 'rule_not_found' using errcode='P0002';end if;
  for v_app in select * from financial_app.transaction_rule_applications where rule_id=p_rule_id and reverted_at is null order by applied_at desc,id desc loop
    select * into v_tx from financial_app.transactions where id=v_app.transaction_id for update;if not found then continue;end if;v_total:=v_total+1;v_reverted:='{}'::jsonb;v_skipped:='{}'::jsonb;
    for v_entry in select key,value from jsonb_each(v_app.changes) loop
      if financial_app.rule_field_has_later_user_edit(v_app.transaction_id,v_entry.key,v_app.applied_at) then v_skipped:=v_skipped||jsonb_build_object(v_entry.key,'later_user_edit');continue;end if;v_before:=v_entry.value->'before';v_after:=v_entry.value->'after';
      if v_entry.key='category' then if to_jsonb(v_tx.category_override) is not distinct from v_after then v_tx.category_override:=case when v_before='null'::jsonb then null else v_before#>>'{}' end;v_reverted:=v_reverted||jsonb_build_object(v_entry.key,true);else v_skipped:=v_skipped||jsonb_build_object(v_entry.key,'value_changed');end if;
      elsif v_entry.key='subcategory' then if to_jsonb(v_tx.subcategory_override) is not distinct from v_after then v_tx.subcategory_override:=case when v_before='null'::jsonb then null else v_before#>>'{}' end;v_reverted:=v_reverted||jsonb_build_object(v_entry.key,true);else v_skipped:=v_skipped||jsonb_build_object(v_entry.key,'value_changed');end if;
      elsif v_entry.key='isRecurring' then if to_jsonb(v_tx.is_recurring) is not distinct from v_after then v_tx.is_recurring:=case when v_before='null'::jsonb then null else (v_before#>>'{}')::boolean end;v_reverted:=v_reverted||jsonb_build_object(v_entry.key,true);else v_skipped:=v_skipped||jsonb_build_object(v_entry.key,'value_changed');end if;
      elsif v_entry.key='tags' then if to_jsonb(v_tx.tags) is not distinct from v_after then select array_agg(value order by value) into v_tags from jsonb_array_elements_text(coalesce(v_before,'[]'::jsonb));v_tx.tags:=coalesce(v_tags,array[]::text[]);v_reverted:=v_reverted||jsonb_build_object(v_entry.key,true);else v_skipped:=v_skipped||jsonb_build_object(v_entry.key,'value_changed');end if;end if;
      if v_reverted ? v_entry.key then v_fields:=v_fields+1;insert into financial_app.transaction_history(transaction_id,field_name,value_origin,value_before,value_after,change_origin,changed_by) values(v_app.transaction_id,'app.'||v_entry.key,v_entry.value->'origin',v_after,v_before,'rule_revert',v_email);end if;
    end loop;
    update financial_app.transactions set category_override=v_tx.category_override,subcategory_override=v_tx.subcategory_override,is_recurring=v_tx.is_recurring,tags=v_tx.tags,updated_at=now() where id=v_app.transaction_id;update financial_app.transaction_rule_applications set reverted_at=now(),reverted_by=v_email,revert_result=jsonb_build_object('reverted',v_reverted,'skipped',v_skipped) where id=v_app.id;
  end loop;
  return jsonb_build_object('ok',true,'applicationsReverted',v_total,'fieldsReverted',v_fields,'overview',financial_app.rules_overview_core());
end$$;

create or replace function public.financial_app_rules_overview() returns jsonb language sql security invoker set search_path to 'pg_catalog','financial_app','auth' as $$select financial_app.rules_overview_core()$$;
create or replace function public.financial_app_upsert_rule(p_rule_id uuid,p_rule jsonb) returns jsonb language sql security invoker set search_path to 'pg_catalog','financial_app','auth' as $$select financial_app.upsert_rule_core(p_rule_id,p_rule)$$;
create or replace function public.financial_app_preview_rule(p_rule jsonb) returns jsonb language sql security invoker set search_path to 'pg_catalog','financial_app','auth' as $$select financial_app.preview_rule_core(p_rule,8)$$;
create or replace function public.financial_app_apply_rule(p_rule_id uuid) returns jsonb language sql security invoker set search_path to 'pg_catalog','financial_app','auth' as $$select financial_app.apply_rule_existing_core(p_rule_id)$$;
create or replace function public.financial_app_deactivate_rule(p_rule_id uuid) returns jsonb language sql security invoker set search_path to 'pg_catalog','financial_app','auth' as $$select financial_app.deactivate_rule_core(p_rule_id)$$;
create or replace function public.financial_app_revert_rule(p_rule_id uuid) returns jsonb language sql security invoker set search_path to 'pg_catalog','financial_app','auth' as $$select financial_app.revert_rule_applications_core(p_rule_id)$$;

-- Least privilege: only authenticated wrappers are externally callable; helpers remain internal.
revoke all on function financial_app.rules_overview_core() from public,anon,authenticated;
revoke all on function financial_app.upsert_rule_core(uuid,jsonb) from public,anon,authenticated;
revoke all on function financial_app.preview_rule_core(jsonb,integer) from public,anon,authenticated;
revoke all on function financial_app.apply_rule_existing_core(uuid) from public,anon,authenticated;
revoke all on function financial_app.deactivate_rule_core(uuid) from public,anon,authenticated;
revoke all on function financial_app.revert_rule_applications_core(uuid) from public,anon,authenticated;
grant execute on function financial_app.rules_overview_core() to authenticated;
grant execute on function financial_app.upsert_rule_core(uuid,jsonb) to authenticated;
grant execute on function financial_app.preview_rule_core(jsonb,integer) to authenticated;
grant execute on function financial_app.apply_rule_existing_core(uuid) to authenticated;
grant execute on function financial_app.deactivate_rule_core(uuid) to authenticated;
grant execute on function financial_app.revert_rule_applications_core(uuid) to authenticated;
revoke all on function financial_app.normalize_rule_definition_core(jsonb) from public,anon,authenticated;
revoke all on function financial_app.rule_matches_transaction_core(jsonb,financial_app.transactions) from public,anon,authenticated;
revoke all on function financial_app.rule_candidate_changes_core(jsonb,financial_app.transactions) from public,anon,authenticated;
revoke all on function financial_app.apply_rule_to_transaction_internal(uuid,uuid,text,text) from public,anon,authenticated;
revoke all on function financial_app.rule_field_has_later_user_edit(uuid,text,timestamptz) from public,anon,authenticated;
revoke all on function financial_app.apply_rules_after_insert_trigger() from public,anon,authenticated;
revoke all on function public.financial_app_rules_overview() from public,anon;
revoke all on function public.financial_app_upsert_rule(uuid,jsonb) from public,anon;
revoke all on function public.financial_app_preview_rule(jsonb) from public,anon;
revoke all on function public.financial_app_apply_rule(uuid) from public,anon;
revoke all on function public.financial_app_deactivate_rule(uuid) from public,anon;
revoke all on function public.financial_app_revert_rule(uuid) from public,anon;
grant execute on function public.financial_app_rules_overview() to authenticated;
grant execute on function public.financial_app_upsert_rule(uuid,jsonb) to authenticated;
grant execute on function public.financial_app_preview_rule(jsonb) to authenticated;
grant execute on function public.financial_app_apply_rule(uuid) to authenticated;
grant execute on function public.financial_app_deactivate_rule(uuid) to authenticated;
grant execute on function public.financial_app_revert_rule(uuid) to authenticated;
