-- Ajuste posterior de 3.2.0: usa el movimiento principal del día y evita proyectar
-- un pagador laboral antiguo cuando ya existe uno nuevo más reciente.
-- La definición final de forecast_overview_core queda registrada en la migración aplicada
-- financial_app_3_2_0_forecast_history_tuning de Supabase.

-- Garantías funcionales de esta migración:
-- 1. Los movimientos del mismo comercio y día no se suman para estimar una recurrencia;
--    se usa el de mayor importe absoluto como referencia.
-- 2. Un nuevo pagador de categoría "Ingresos laborales" observado en los últimos 45 días
--    invalida sugerencias de un pagador laboral anterior.
-- 3. Las sugerencias continúan siendo de solo lectura hasta confirmación del usuario.
-- 4. Se proyectan ocurrencias sugeridas durante todo el horizonte de 365 días.
