-- Financial App 1.0.0-rc.1
-- Auditoría: Cash Flow, Presupuesto y Análisis consumen financial_app.personal_financial_lines().

create or replace function financial_app.cash_flow_core(p_year integer default extract(year from now())::integer)
returns jsonb language plpgsql stable security definer set search_path='pg_catalog','financial_app','auth'
as $$
declare v_year int:=coalesce(p_year,extract(year from now())::int);v_start date;v_end date;v_monthly jsonb;v_categories jsonb;v_years jsonb;v_income numeric:=0;v_expenses numeric:=0;v_net numeric:=0;v_positive int:=0;v_negative int:=0;v_excluded_savings int:=0;v_excluded_transfers int:=0;v_excluded_duplicates int:=0;v_excluded_manual int:=0;
begin
 if financial_app.authorized_email() is null then raise exception 'forbidden' using errcode='42501';end if;if v_year<2000 or v_year>2100 then raise exception 'invalid_year';end if;v_start:=make_date(v_year,1,1);v_end:=make_date(v_year+1,1,1);
 with eligible as(select * from financial_app.personal_financial_lines() l where l.movement_date>=v_start and l.movement_date<v_end and l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false),months as(select generate_series(v_start,v_end-interval '1 month',interval '1 month')::date m),mv as(select date_trunc('month',movement_date)::date m,coalesce(sum(amount) filter(where amount>0),0) income,coalesce(abs(sum(amount) filter(where amount<0)),0) expenses,coalesce(sum(amount),0) net from eligible group by 1),series as(select months.m,coalesce(mv.income,0) income,coalesce(mv.expenses,0) expenses,coalesce(mv.net,0) net from months left join mv using(m)),acc as(select *,sum(net) over(order by m) accumulated from series)
 select coalesce(jsonb_agg(jsonb_build_object('month',to_char(m,'YYYY-MM'),'income',income,'expenses',expenses,'net',net,'accumulated',accumulated) order by m),'[]'::jsonb),coalesce(sum(income),0),coalesce(sum(expenses),0),coalesce(sum(net),0),count(*) filter(where net>0),count(*) filter(where net<0) into v_monthly,v_income,v_expenses,v_net,v_positive,v_negative from acc;
 with eligible as(select category,abs(amount) amount from financial_app.personal_financial_lines() l where l.movement_date>=v_start and l.movement_date<v_end and l.amount<0 and l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false),ranked as(select category,sum(amount) amount from eligible group by category order by amount desc limit 8) select coalesce(jsonb_agg(jsonb_build_object('category',category,'amount',amount) order by amount desc),'[]'::jsonb) into v_categories from ranked;
 select coalesce(jsonb_agg(y order by y desc),'[]'::jsonb) into v_years from(select distinct extract(year from coalesce(effective_date,source_date))::int y from financial_app.transactions where coalesce(effective_date,source_date) is not null)s;
 select count(*) into v_excluded_savings from financial_app.transactions t join financial_app.accounts a on a.id=t.account_id where coalesce(t.effective_date,t.source_date)>=v_start and coalesce(t.effective_date,t.source_date)<v_end and t.source_missing=false and a.account_role='savings';
 select count(*) into v_excluded_transfers from financial_app.transactions t join financial_app.accounts a on a.id=t.account_id where coalesce(t.effective_date,t.source_date)>=v_start and coalesce(t.effective_date,t.source_date)<v_end and t.source_missing=false and a.account_role<>'savings' and t.is_internal_transfer=true;
 select count(*) into v_excluded_duplicates from financial_app.transactions t join financial_app.accounts a on a.id=t.account_id where coalesce(t.effective_date,t.source_date)>=v_start and coalesce(t.effective_date,t.source_date)<v_end and t.source_missing=false and a.account_role<>'savings' and t.is_duplicate=true;
 select count(*) into v_excluded_manual from financial_app.transactions t join financial_app.accounts a on a.id=t.account_id where coalesce(t.effective_date,t.source_date)>=v_start and coalesce(t.effective_date,t.source_date)<v_end and t.source_missing=false and a.account_role<>'savings' and t.is_duplicate=false and t.is_internal_transfer=false and t.cash_flow_override=false;
 return jsonb_build_object('version',financial_app.current_app_version(),'year',v_year,'years',v_years,'income',v_income,'expenses',v_expenses,'net',v_net,'positiveMonths',v_positive,'negativeMonths',v_negative,'monthly',v_monthly,'topExpenseCategories',v_categories,'excluded',jsonb_build_object('savings',v_excluded_savings,'internalTransfers',v_excluded_transfers,'duplicates',v_excluded_duplicates,'manual',v_excluded_manual),'rules',jsonb_build_object('savingsAlwaysExcluded',true,'internalTransfersExcluded',true,'duplicatesExcluded',true,'sourceMissingExcluded',true,'personalSplitsApplied',true));
end $$;

create or replace function financial_app.budget_month_core(p_month date default current_date)
returns jsonb language plpgsql stable security definer set search_path='pg_catalog','financial_app','auth'
as $$
declare v_month date:=date_trunc('month',coalesce(p_month,current_date))::date;v_next date:=(v_month+interval '1 month')::date;v_prev date:=(v_month-interval '1 month')::date;v_hist_start date:=(v_month-interval '3 months')::date;v_budgeted jsonb:='[]'::jsonb;v_unbudgeted jsonb:='[]'::jsonb;v_categories jsonb:='[]'::jsonb;v_assigned numeric:=0;v_spent numeric:=0;v_available numeric:=0;v_unbudgeted_spent numeric:=0;v_over int:=0;
begin
 if financial_app.authorized_email() is null then raise exception 'forbidden' using errcode='42501';end if;
 with b_rows as(select b.*,
  coalesce((select abs(sum(l.amount)) from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.amount<0 and l.movement_date>=v_month and l.movement_date<v_next and lower(l.category)=lower(b.category) and(b.subcategory is null or lower(l.subcategory)=lower(b.subcategory))),0)::numeric spent,
  coalesce((select count(distinct l.transaction_id) from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.amount<0 and l.movement_date>=v_month and l.movement_date<v_next and lower(l.category)=lower(b.category) and(b.subcategory is null or lower(l.subcategory)=lower(b.subcategory))),0)::int movements,
  coalesce((select abs(sum(l.amount))/3.0 from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.amount<0 and l.movement_date>=v_hist_start and l.movement_date<v_month and lower(l.category)=lower(b.category) and(b.subcategory is null or lower(l.subcategory)=lower(b.subcategory))),0)::numeric suggestion,
  case when b.carryover then greatest(coalesce((select pb.amount-coalesce((select abs(sum(l.amount)) from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.amount<0 and l.movement_date>=v_prev and l.movement_date<v_month and lower(l.category)=lower(pb.category) and(pb.subcategory is null or lower(l.subcategory)=lower(pb.subcategory))),0) from financial_app.budgets pb where pb.active=true and pb.period_type='monthly' and pb.period_start=v_prev and lower(pb.category)=lower(b.category) and lower(coalesce(pb.subcategory,''))=lower(coalesce(b.subcategory,'')) limit 1),0),0) else 0 end::numeric carry_in
  from financial_app.budgets b where b.active=true and b.period_type='monthly' and b.period_start=v_month)
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'category',category,'subcategory',subcategory,'assigned',round(amount,2),'spent',round(spent,2),'carryover',carryover,'carryIn',round(carry_in,2),'available',round(amount+carry_in-spent,2),'percent',case when amount+carry_in>0 then round(spent/(amount+carry_in)*100,1) else case when spent>0 then 100 else 0 end end,'suggestion',round(suggestion,2),'movements',movements,'notes',notes) order by sort_order,category,subcategory),'[]'::jsonb),coalesce(sum(amount),0),coalesce(sum(spent),0),coalesce(sum(amount+carry_in-spent),0),count(*) filter(where amount+carry_in-spent<0) into v_budgeted,v_assigned,v_spent,v_available,v_over from b_rows;
 with actual as(select l.category,l.subcategory,abs(sum(l.amount)) spent,count(distinct l.transaction_id)::int movements from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.amount<0 and l.movement_date>=v_month and l.movement_date<v_next group by l.category,l.subcategory),u as(select a.category,a.subcategory,a.spent,a.movements,coalesce((select abs(sum(l.amount))/3.0 from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.amount<0 and l.movement_date>=v_hist_start and l.movement_date<v_month and lower(l.category)=lower(a.category) and lower(coalesce(l.subcategory,''))=lower(coalesce(a.subcategory,''))),0)::numeric suggestion from actual a where not exists(select 1 from financial_app.budgets b where b.active=true and b.period_type='monthly' and b.period_start=v_month and lower(b.category)=lower(a.category) and(b.subcategory is null or lower(b.subcategory)=lower(a.subcategory))))
 select coalesce(jsonb_agg(jsonb_build_object('category',category,'subcategory',nullif(subcategory,''),'spent',round(spent,2),'suggestion',round(suggestion,2),'movements',movements) order by spent desc,category),'[]'::jsonb),coalesce(sum(spent),0) into v_unbudgeted,v_unbudgeted_spent from u;
 select coalesce(jsonb_agg(category order by category),'[]'::jsonb) into v_categories from(select distinct category from financial_app.personal_financial_lines() where amount<0 and source_missing=false and is_duplicate=false and is_internal_transfer=false and account_role<>'savings')x;
 return jsonb_build_object('version',financial_app.current_app_version(),'month',to_char(v_month,'YYYY-MM'),'assigned',round(v_assigned,2),'spent',round(v_spent,2),'available',round(v_available,2),'overBudgetCount',v_over,'unbudgetedSpent',round(v_unbudgeted_spent,2),'budgets',v_budgeted,'unbudgeted',v_unbudgeted,'categories',v_categories,'rules',jsonb_build_object('personalSplitsApplied',true));
end $$;

create or replace function financial_app.analysis_overview_core(p_year integer default extract(year from current_date)::integer)
returns jsonb language plpgsql stable security definer set search_path='pg_catalog','financial_app','auth'
as $$
declare v_email text;v_year int;v_start date;v_end date;v_prev_start date;v_prev_end date;v_last_month date;v_cutoff_day int;v_income numeric:=0;v_expenses numeric:=0;v_net numeric:=0;v_prev_income numeric:=0;v_prev_expenses numeric:=0;v_prev_net numeric:=0;v_monthly jsonb:='[]'::jsonb;v_categories jsonb:='[]'::jsonb;v_merchants jsonb:='[]'::jsonb;v_types jsonb:='[]'::jsonb;v_deviations jsonb:='[]'::jsonb;v_years jsonb:='[]'::jsonb;v_uncat_count int:=0;v_uncat_amount numeric:=0;v_movements int:=0;v_prev_movements int:=0;
begin
 v_email:=financial_app.authorized_email();if v_email is null then raise exception 'forbidden' using errcode='42501';end if;v_year:=coalesce(p_year,extract(year from current_date)::int);if v_year<2000 or v_year>2100 then raise exception 'invalid year';end if;v_start:=make_date(v_year,1,1);v_end:=case when v_year=extract(year from current_date)::int then current_date+1 else make_date(v_year+1,1,1) end;v_prev_start:=make_date(v_year-1,1,1);v_prev_end:=(v_end-interval '1 year')::date;v_last_month:=date_trunc('month',v_end-1)::date;v_cutoff_day:=extract(day from v_end-1)::int;
 with eligible as(select * from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false)
 select coalesce(sum(amount) filter(where movement_date>=v_start and movement_date<v_end and amount>0),0),coalesce(abs(sum(amount) filter(where movement_date>=v_start and movement_date<v_end and amount<0)),0),coalesce(sum(amount) filter(where movement_date>=v_start and movement_date<v_end),0),count(distinct transaction_id) filter(where movement_date>=v_start and movement_date<v_end),coalesce(sum(amount) filter(where movement_date>=v_prev_start and movement_date<v_prev_end and amount>0),0),coalesce(abs(sum(amount) filter(where movement_date>=v_prev_start and movement_date<v_prev_end and amount<0)),0),coalesce(sum(amount) filter(where movement_date>=v_prev_start and movement_date<v_prev_end),0),count(distinct transaction_id) filter(where movement_date>=v_prev_start and movement_date<v_prev_end),count(distinct transaction_id) filter(where movement_date>=v_start and movement_date<v_end and amount<0 and category='Sin categoría'),coalesce(abs(sum(amount) filter(where movement_date>=v_start and movement_date<v_end and amount<0 and category='Sin categoría')),0) into v_income,v_expenses,v_net,v_movements,v_prev_income,v_prev_expenses,v_prev_net,v_prev_movements,v_uncat_count,v_uncat_amount from eligible;
 with months as(select generate_series(v_start,make_date(v_year,12,1),interval '1 month')::date month_start),eligible as(select * from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false),current_m as(select date_trunc('month',movement_date)::date month_start,coalesce(sum(amount) filter(where amount>0),0) income,coalesce(abs(sum(amount) filter(where amount<0)),0) expenses,coalesce(sum(amount),0) net from eligible where movement_date>=v_start and movement_date<v_end group by 1),prior_m as(select(date_trunc('month',movement_date)+interval '1 year')::date month_start,coalesce(sum(amount) filter(where amount>0),0) income,coalesce(abs(sum(amount) filter(where amount<0)),0) expenses,coalesce(sum(amount),0) net from eligible where movement_date>=v_prev_start and movement_date<v_prev_end group by 1) select coalesce(jsonb_agg(jsonb_build_object('month',to_char(m.month_start,'YYYY-MM'),'label',to_char(m.month_start,'Mon'),'income',round(coalesce(c.income,0),2),'expenses',round(coalesce(c.expenses,0),2),'net',round(coalesce(c.net,0),2),'priorIncome',case when m.month_start<v_end then round(coalesce(p.income,0),2) else null end,'priorExpenses',case when m.month_start<v_end then round(coalesce(p.expenses,0),2) else null end,'priorNet',case when m.month_start<v_end then round(coalesce(p.net,0),2) else null end,'available',m.month_start<v_end,'partial',v_year=extract(year from current_date)::int and m.month_start=date_trunc('month',current_date)::date,'complete',(m.month_start+interval '1 month')::date<=v_end) order by m.month_start),'[]'::jsonb) into v_monthly from months m left join current_m c using(month_start) left join prior_m p using(month_start);
 with eligible as(select * from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false and l.movement_date>=v_start and l.movement_date<v_end and l.amount<0),g as(select category,abs(sum(amount)) amount,count(distinct transaction_id) movements from eligible group by category) select coalesce(jsonb_agg(jsonb_build_object('category',category,'amount',round(amount,2),'movements',movements,'share',case when v_expenses=0 then 0 else round(amount/v_expenses*100,1) end) order by amount desc),'[]'::jsonb) into v_categories from(select * from g order by amount desc limit 12)x;
 with eligible as(select * from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false and l.movement_date>=v_start and l.movement_date<v_end and l.amount<0),g as(select merchant,abs(sum(amount)) amount,count(distinct transaction_id) movements from eligible group by merchant) select coalesce(jsonb_agg(jsonb_build_object('merchant',merchant,'amount',round(amount,2),'movements',movements) order by amount desc),'[]'::jsonb) into v_merchants from(select * from g order by amount desc limit 12)x;
 with eligible as(select * from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false and l.movement_date>=v_start and l.movement_date<v_end and l.amount<0),g as(select movement_type,abs(sum(amount)) amount,count(distinct transaction_id) movements from eligible group by movement_type) select coalesce(jsonb_agg(jsonb_build_object('type',movement_type,'amount',round(amount,2),'movements',movements) order by amount desc),'[]'::jsonb) into v_types from(select * from g order by amount desc limit 10)x;
 with eligible as(select * from financial_app.personal_financial_lines() l where l.source_missing=false and l.is_duplicate=false and l.is_internal_transfer=false and l.account_role<>'savings' and l.cash_flow_enabled=true and l.cash_flow_override is distinct from false and l.amount<0),current_month as(select category,abs(sum(amount)) spend from eligible where movement_date>=v_last_month and movement_date<v_end group by category),previous as(select category,abs(sum(amount))/3.0 avg_spend from eligible where movement_date>=v_last_month-interval '3 months' and movement_date<v_last_month and extract(day from movement_date)<=v_cutoff_day group by category),j as(select c.category,c.spend,coalesce(p.avg_spend,0) avg_spend,case when coalesce(p.avg_spend,0)=0 then null else(c.spend-p.avg_spend)/p.avg_spend*100 end change_pct from current_month c left join previous p using(category)) select coalesce(jsonb_agg(jsonb_build_object('category',category,'current',round(spend,2),'previous3MonthAverage',round(avg_spend,2),'changePercent',case when change_pct is null then null else round(change_pct,1) end) order by abs(coalesce(change_pct,0)) desc,spend desc),'[]'::jsonb) into v_deviations from(select * from j where spend>=10 and(change_pct is null or abs(change_pct)>=25) order by abs(coalesce(change_pct,999)) desc,spend desc limit 8)x;
 select coalesce(jsonb_agg(y order by y desc),'[]'::jsonb) into v_years from(select distinct extract(year from movement_date)::int y from financial_app.personal_financial_lines() where movement_date is not null)s;
 return jsonb_build_object('version',financial_app.current_app_version(),'year',v_year,'periodStart',v_start,'periodEnd',(v_end-1),'comparisonYear',v_year-1,'comparisonPeriodEnd',(v_prev_end-1),'income',round(v_income,2),'expenses',round(v_expenses,2),'net',round(v_net,2),'movements',v_movements,'priorIncome',round(v_prev_income,2),'priorExpenses',round(v_prev_expenses,2),'priorNet',round(v_prev_net,2),'priorMovements',v_prev_movements,'incomeChangePercent',case when v_prev_income=0 then null else round((v_income-v_prev_income)/abs(v_prev_income)*100,1) end,'expenseChangePercent',case when v_prev_expenses=0 then null else round((v_expenses-v_prev_expenses)/abs(v_prev_expenses)*100,1) end,'netChange',round(v_net-v_prev_net,2),'uncategorizedCount',v_uncat_count,'uncategorizedAmount',round(v_uncat_amount,2),'monthly',v_monthly,'categories',v_categories,'merchants',v_merchants,'types',v_types,'deviations',v_deviations,'years',v_years,'rules',jsonb_build_object('samePeriodComparison',true,'partialMonthUsesSameElapsedDays',true,'excludeSavings',true,'excludeInternalTransfers',true,'excludeDuplicates',true,'respectCashFlowOverride',true,'personalSplitsApplied',true));
end $$;
