"use client";

import { formatEuro, formatInteger } from "@/lib/format/es-es";
import { madridToday } from "@/lib/time/madrid";
import { inferDocumentMetadata, recognizeTicketImage, type DocumentTypeHint } from "@/lib/document/ticket-ocr";
import { FormEvent, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/browser";
import type { ArchiveDetail, ArchiveDocument, ArchiveOverview, ArchiveMovementRef } from "@/lib/financial/archive";

declare global { interface Window { Tesseract?: any; __financialPdfjs?: any } }

type OcrResult={text:string;status:"complete"|"error";data:Record<string,unknown>;reconstruction:Record<string,unknown>|null;documentType:string;documentDate:string|null;amount:number|null;merchant:string|null};
type DetailPayload={ok:true;document:ArchiveDetail;signedUrl:string|null};
type ArchiveEdit={documentType:string;documentDate:string;amount:number|string;merchant:string;notes:string;ocrText:string};
const MAX_FILE=20*1024*1024;
const allowed=new Set(["application/pdf","image/jpeg","image/png","image/webp","image/heic","image/heif"]);

const dates=new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"2-digit",year:"numeric"});

function formatDate(value:string|null){return value?dates.format(new Date(`${value}T12:00:00`)):"—"}
function formatMoney(value:number|null){return value==null?"—":formatEuro(value)}
function safeName(name:string){return name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(0,120)||"documento"}
async function sha256(file:File){const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}
function loadScript(src:string,id:string){return new Promise<void>((resolve,reject)=>{if(document.getElementById(id)){resolve();return}const script=document.createElement("script");script.id=id;script.src=src;script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error("No se pudo cargar el motor OCR"));document.head.appendChild(script)})}
async function loadPdfJs(){if(window.__financialPdfjs)return window.__financialPdfjs;return new Promise<any>((resolve,reject)=>{const existing=document.getElementById("financial-pdfjs-loader");const onReady=()=>{cleanup();window.__financialPdfjs?resolve(window.__financialPdfjs):reject(new Error("PDF.js no disponible"))};const cleanup=()=>window.removeEventListener("financial-pdfjs-ready",onReady);window.addEventListener("financial-pdfjs-ready",onReady,{once:true});if(!existing){const script=document.createElement("script");script.id="financial-pdfjs-loader";script.type="module";script.src="/vendor/pdfjs-loader.mjs";script.onerror=()=>{cleanup();reject(new Error("No se pudo cargar el lector PDF"))};document.head.appendChild(script)}})}
async function makeWorker(onProgress:(value:number,label:string)=>void){await loadScript("/vendor/document-engine/tesseract/tesseract.min.js","financial-tesseract");if(!window.Tesseract)throw new Error("Motor OCR no disponible");return window.Tesseract.createWorker("spa",1,{workerPath:"/vendor/document-engine/tesseract/worker.min.js",corePath:"/vendor/document-engine/tesseract-core",langPath:"/vendor/document-engine/tessdata",logger:(message:any)=>{if(message?.status==="recognizing text")onProgress(Number(message.progress||0),"Reconociendo texto")}})}
async function runOcr(file:File,onProgress:(value:number,label:string)=>void,hint:DocumentTypeHint=null):Promise<OcrResult>{
  onProgress(.03,"Preparando documento");let text="";let layoutText="";let method="image_ocr";let pages=1;let confidence:number|null=null;let passes:Array<{variant:string;confidence:number|null;score:number}>=[];let worker:any=null;
  try{
    if(file.type==="application/pdf"){
      const pdfjs=await loadPdfJs();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;pages=pdf.numPages;const chunks:string[]=[];const scanned:number[]=[];
      for(let i=1;i<=pdf.numPages;i++){onProgress(.05+.3*(i/pdf.numPages),`Leyendo PDF · página ${i}/${pdf.numPages}`);const page=await pdf.getPage(i);const content=await page.getTextContent();const pageText=content.items.map((item:any)=>String(item?.str||"")).join(" ").trim();if(pageText.replace(/\s/g,"").length>=40)chunks.push(pageText);else scanned.push(i)}
      if(scanned.length){method=chunks.length?"pdf_hybrid":"pdf_ocr";worker=await makeWorker(onProgress);const scores:number[]=[];for(let index=0;index<scanned.length;index++){const pageNo=scanned[index];const page=await pdf.getPage(pageNo);const viewport=page.getViewport({scale:1.65});const canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas no disponible");await page.render({canvasContext:ctx,viewport}).promise;onProgress(.4+.55*((index+1)/scanned.length),`OCR · página ${pageNo}/${pdf.numPages}`);const recognized=await worker.recognize(canvas);chunks.push(String(recognized.data?.text||""));if(Number.isFinite(recognized.data?.confidence))scores.push(Number(recognized.data.confidence))}confidence=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null}
      else method="pdf_text";text=chunks.join("\n\n");layoutText=text;
    }else{
      worker=await makeWorker(onProgress);const recognized=await recognizeTicketImage(file,worker,onProgress,hint);text=recognized.text;layoutText=recognized.layoutText;confidence=recognized.confidence;method=recognized.method;passes=recognized.passes;
    }
    if(!text.trim())throw new Error("No se ha podido extraer texto del documento");const meta=inferDocumentMetadata(text,hint);const reconstruction={generated:true,label:"Reconstrucción visual obtenida mediante OCR local. El original es la referencia.",engine:method==="pdf_text"?"PDF.js":"Tesseract.js 7.0.0",method,documentType:meta.documentType,documentDate:meta.documentDate,amount:meta.amount,merchant:meta.merchant,layoutText:layoutText||text};
    onProgress(1,"OCR completado");return{text,status:"complete",data:{engine:method==="pdf_text"?"PDF.js 6.2.108":"Tesseract.js 7.0.0",method,pages,confidence,passes,language:"spa",localProcessing:true,imagePreprocessing:method.startsWith("image_ocr_"),assetOrigin:"same-origin",processedAt:new Date().toISOString()},reconstruction,documentType:meta.documentType,documentDate:meta.documentDate,amount:meta.amount,merchant:meta.merchant};
  }finally{if(worker)await worker.terminate().catch(()=>undefined)}
}

export function ArchiveClient({initialData}:{initialData:ArchiveOverview}){
  const [data,setData]=useState(initialData);const [search,setSearch]=useState("");const [showArchived,setShowArchived]=useState(false);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState(0);const [progressLabel,setProgressLabel]=useState("");const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [detail,setDetail]=useState<ArchiveDetail|null>(null);const [signedUrl,setSignedUrl]=useState<string|null>(null);const [edit,setEdit]=useState<ArchiveEdit|null>(null);const cameraRef=useRef<HTMLInputElement>(null);const galleryRef=useRef<HTMLInputElement>(null);const fileRef=useRef<HTMLInputElement>(null);
  async function refresh(q=search,includeArchived=showArchived){const params=new URLSearchParams();if(q.trim())params.set("search",q.trim());if(includeArchived)params.set("archived","1");const r=await fetch(`/api/archive${params.size?`?${params.toString()}`:""}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo cargar Archivo");setData(body)}
  async function submitSearch(e:FormEvent){e.preventDefault();setError(null);try{await refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Error de búsqueda")}}
  async function openDocument(id:string){setBusy(true);setError(null);try{const r=await fetch(`/api/archive/${id}`,{cache:"no-store"});const body=await r.json() as DetailPayload & {error?:string};if(!r.ok||!body.ok)throw new Error(body.error||"No se pudo abrir el documento");setDetail(body.document);setSignedUrl(body.signedUrl);setEdit({documentType:body.document.documentType,documentDate:body.document.documentDate||"",amount:body.document.amount??"",merchant:body.document.merchant||"",notes:body.document.notes||"",ocrText:body.document.ocrText||""})}catch(cause){setError(cause instanceof Error?cause.message:"Error al abrir documento")}finally{setBusy(false)}}
  async function upload(file:File,hint:DocumentTypeHint=null){setBusy(true);setError(null);setMessage(null);setProgress(0);setProgressLabel("Comprobando archivo");let storagePath:string|null=null;try{
    if(!allowed.has(file.type))throw new Error("Formato no admitido. Usa PDF, JPEG, PNG, WebP, HEIC o HEIF.");if(file.size<=0||file.size>MAX_FILE)throw new Error("El archivo debe ocupar entre 1 byte y 20 MB.");
    const hash=await sha256(file);const supabase=createClient();const {data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user)throw new Error("Sesión no válida");storagePath=`${userData.user.id}/${madridToday()}/${crypto.randomUUID()}-${safeName(file.name)}`;setProgress(.02);setProgressLabel("Guardando original privado");const stored=await supabase.storage.from("financial-app-documents").upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:"3600"});if(stored.error)throw stored.error;
    const registered=await fetch("/api/archive",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileName:file.name,mimeType:file.type,storagePath,fileSize:file.size,contentHash:hash})});const registration=await registered.json();if(!registered.ok){await supabase.storage.from("financial-app-documents").remove([storagePath]);throw new Error(registration.error||"No se pudo registrar el documento")}
    const id=String(registration.id);try{const result=await runOcr(file,(value,label)=>{setProgress(value);setProgressLabel(label)},hint);const patched=await fetch(`/api/archive/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentType:result.documentType,documentDate:result.documentDate,amount:result.amount,merchant:result.merchant,ocrText:result.text,ocrData:result.data,digitalReconstruction:result.reconstruction,ocrStatus:result.status})});if(!patched.ok)throw new Error((await patched.json()).error||"No se pudo guardar el OCR");setMessage("Documento guardado y leído con OCR mejorado. Revisa fecha, importe y comercio antes de vincularlo.")}
    catch(ocrError){await fetch(`/api/archive/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ocrStatus:"error",ocrData:{localProcessing:true,error:ocrError instanceof Error?ocrError.message:"ocr_failed",processedAt:new Date().toISOString()}})});setMessage("El original se ha guardado. El OCR no pudo completarse y queda pendiente de revisión.")}
    await refresh();await openDocument(id);
  }catch(cause){setError(cause instanceof Error?cause.message:"No se pudo subir el documento")}finally{setBusy(false);setProgress(0);setProgressLabel("");if(cameraRef.current)cameraRef.current.value="";if(galleryRef.current)galleryRef.current.value="";if(fileRef.current)fileRef.current.value=""}}
  async function saveDetail(e:FormEvent){e.preventDefault();if(!detail||!edit)return;setBusy(true);setError(null);try{const r=await fetch(`/api/archive/${detail.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentType:edit.documentType,documentDate:edit.documentDate||null,amount:edit.amount===""?null:Number(edit.amount),merchant:edit.merchant||null,notes:edit.notes||null,ocrText:edit.ocrText||null,ocrStatus:edit.ocrText!==(detail.ocrText||"")?"manual":detail.ocrStatus})});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo guardar");setMessage("Documento actualizado con historial.");await refresh();await openDocument(detail.id)}catch(cause){setError(cause instanceof Error?cause.message:"Error al guardar")}finally{setBusy(false)}}
  async function linkMovement(ref:ArchiveMovementRef){if(!detail)return;setBusy(true);try{const r=await fetch(`/api/archive/${detail.id}/links`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceId:ref.sourceId})});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo vincular");await refresh();await openDocument(detail.id)}catch(cause){setError(cause instanceof Error?cause.message:"Error de vinculación")}finally{setBusy(false)}}
  async function unlinkMovement(sourceId:string){if(!detail)return;setBusy(true);try{const r=await fetch(`/api/archive/${detail.id}/links?sourceId=${encodeURIComponent(sourceId)}`,{method:"DELETE"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo desvincular");await refresh();await openDocument(detail.id)}catch(cause){setError(cause instanceof Error?cause.message:"Error al desvincular")}finally{setBusy(false)}}
  async function archiveCurrent(){if(!detail||!confirm("¿Mover este documento a Archivados? Podrás restaurarlo o eliminarlo definitivamente después."))return;setBusy(true);try{const r=await fetch(`/api/archive/${detail.id}`,{method:"DELETE"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo archivar");setDetail(null);setSignedUrl(null);await refresh(search,false);setMessage("Documento movido a Archivados. Puedes verlo en la pestaña Archivados.")}catch(cause){setError(cause instanceof Error?cause.message:"Error al archivar")}finally{setBusy(false)}}
  async function restoreCurrent(){if(!detail)return;setBusy(true);setError(null);try{const r=await fetch(`/api/archive/${detail.id}?action=restore`,{method:"POST"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo restaurar");setDetail(null);setSignedUrl(null);await refresh(search,true);setMessage("Documento restaurado a Activos.")}catch(cause){setError(cause instanceof Error?cause.message:"Error al restaurar")}finally{setBusy(false)}}
  async function deleteCurrent(){if(!detail||!detail.archivedAt)return;const ok=confirm(`¿Eliminar definitivamente "${detail.fileName}"? Se borrarán el original privado, el OCR y sus vínculos. Esta acción no se puede deshacer.`);if(!ok)return;setBusy(true);setError(null);try{const r=await fetch(`/api/archive/${detail.id}?permanent=1`,{method:"DELETE"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo eliminar");setDetail(null);setSignedUrl(null);await refresh(search,true);setMessage("Documento eliminado definitivamente.")}catch(cause){setError(cause instanceof Error?cause.message:"Error al eliminar")}finally{setBusy(false)}}
  async function reprocess(){if(!detail||!signedUrl)return;setBusy(true);setError(null);setProgress(.01);setProgressLabel("Descargando original privado");try{const response=await fetch(signedUrl);if(!response.ok)throw new Error("No se pudo abrir el original");const blob=await response.blob();const file=new File([blob],detail.fileName,{type:detail.mimeType||blob.type});const result=await runOcr(file,(value,label)=>{setProgress(value);setProgressLabel(label)},file.type.startsWith("image/")?"receipt":null);const r=await fetch(`/api/archive/${detail.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentType:result.documentType,documentDate:result.documentDate,amount:result.amount,merchant:result.merchant,ocrText:result.text,ocrData:result.data,digitalReconstruction:result.reconstruction,ocrStatus:"complete"})});if(!r.ok)throw new Error((await r.json()).error||"No se pudo guardar el OCR");setMessage("OCR reprocesado correctamente.");await refresh();await openDocument(detail.id)}catch(cause){setError(cause instanceof Error?cause.message:"Error al reprocesar OCR")}finally{setBusy(false);setProgress(0);setProgressLabel("")}}
  const currentSuggestions:ArchiveMovementRef[] = data.documents.find(d=>d.id===detail?.id)?.suggestions ?? [];
  const visibleDocuments=data.documents.filter(doc=>showArchived?Boolean(doc.archivedAt):!doc.archivedAt);
  const reconstructionLayout=detail?.digitalReconstruction&&typeof detail.digitalReconstruction==="object"?String((detail.digitalReconstruction as Record<string,unknown>).layoutText||detail.ocrText||""):String(detail?.ocrText||"");
  async function changeView(next:boolean){setBusy(true);setError(null);try{await refresh(search,next);setShowArchived(next);setDetail(null);setSignedUrl(null)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo cambiar la vista")}finally{setBusy(false)}}
  return <div className="archive-module">
    <section className="archive-summary"><div><strong>{formatInteger(data.total)}</strong><span>documentos</span></div><div><strong>{formatInteger(data.processed)}</strong><span>procesados</span></div><div><strong>{formatInteger(data.linked)}</strong><span>vinculados</span></div><div><strong>Privado</strong><span>bucket protegido</span></div></section>
    <div className="archive-toolbar"><form onSubmit={submitSearch}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por archivo, comercio, OCR o notas"/><button className="ghost" type="submit">Buscar</button></form><div className="archive-import-actions"><button className="primary-action" type="button" onClick={()=>cameraRef.current?.click()} disabled={busy}>Hacer foto de ticket</button><button className="ghost" type="button" onClick={()=>galleryRef.current?.click()} disabled={busy}>Elegir foto de galería</button><button className="ghost" type="button" onClick={()=>fileRef.current?.click()} disabled={busy}>Añadir documento</button></div><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"receipt")}/><input ref={galleryRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"receipt")}/><input ref={fileRef} hidden type="file" accept=".pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></div>
    {progress>0&&<div className="ocr-progress" role="status"><div><span>{progressLabel}</span><b>{Math.round(progress*100)}%</b></div><progress max={1} value={progress}/><small>El OCR se ejecuta en este dispositivo; el archivo no se envía a un servicio OCR externo.</small></div>}
    {error&&<div className="inline-alert error" role="alert">{error}</div>}{message&&<div className="inline-alert success" role="status">{message}</div>}
    <div className="archive-view-switch" role="tablist" aria-label="Estado de documentos"><button type="button" role="tab" aria-selected={!showArchived} className={!showArchived?"active":""} onClick={()=>changeView(false)} disabled={busy}>Activos</button><button type="button" role="tab" aria-selected={showArchived} className={showArchived?"active":""} onClick={()=>changeView(true)} disabled={busy}>Archivados</button><span>{showArchived?"Aquí están los documentos apartados. Puedes restaurarlos o eliminarlos definitivamente.":"Documentos disponibles para consulta y vinculación."}</span></div>
    <section className="document-grid">{visibleDocuments.map(doc=><button className="document-card" key={doc.id} onClick={()=>openDocument(doc.id)} type="button"><div className="document-kind">{doc.mimeType==="application/pdf"?"PDF":"IMG"}</div><div><strong>{doc.fileName}</strong><span>{doc.merchant||doc.documentType} · {formatDate(doc.documentDate)}</span><small>{formatMoney(doc.amount)} · {doc.ocrStatus==="complete"?"OCR completo":doc.ocrStatus==="manual"?"OCR corregido":doc.ocrStatus==="error"?"OCR pendiente":doc.ocrStatus}</small></div>{doc.links.length>0&&<em>{formatInteger(doc.links.length)} vínculo{doc.links.length===1?"":"s"}</em>}</button>)}</section>
    {!visibleDocuments.length&&<div className="empty-state"><strong>{showArchived?"No hay documentos archivados":"Archivo vacío"}</strong><span>{showArchived?"Los documentos que archives aparecerán aquí.":"Añade una factura, ticket, contrato o justificante para empezar."}</span></div>}
    {detail&&edit&&<div className="drawer-backdrop" onMouseDown={()=>!busy&&setDetail(null)}><aside className="archive-drawer" role="dialog" aria-modal="true" aria-labelledby="archive-title" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><p className="eyebrow">ORIGINAL PRIVADO</p><h2 id="archive-title">{detail.fileName}</h2><p>{detail.contentHash?.slice(0,16)}… · {detail.fileSize?`${(detail.fileSize/1024).toFixed(0)} KB`:""}</p></div><button className="icon-button" type="button" onClick={()=>setDetail(null)} aria-label="Cerrar">×</button></header>
      <div className="archive-actions">{signedUrl&&<a className="ghost button-link" href={signedUrl} target="_blank" rel="noreferrer">Abrir original</a>}{!detail.archivedAt&&<button className="ghost" type="button" onClick={reprocess} disabled={busy||!signedUrl}>Reprocesar OCR mejorado</button>}{detail.archivedAt?<><button className="ghost" type="button" onClick={restoreCurrent} disabled={busy}>Restaurar a Activos</button><button className="danger-action" type="button" onClick={deleteCurrent} disabled={busy}>Eliminar definitivamente</button></>:<button className="danger-action" type="button" onClick={archiveCurrent} disabled={busy}>Mover a Archivados</button>}</div>
      <form className="archive-editor" onSubmit={saveDetail}><div className="editor-grid"><label><span>Tipo</span><select value={edit.documentType} onChange={e=>setEdit({...edit,documentType:e.target.value})}><option value="invoice">Factura</option><option value="receipt">Ticket / recibo</option><option value="contract">Contrato</option><option value="statement">Extracto</option><option value="tax">Impuestos</option><option value="other">Otro</option></select></label><label><span>Fecha</span><input type="date" value={edit.documentDate} onChange={e=>setEdit({...edit,documentDate:e.target.value})}/></label><label><span>Importe</span><input type="number" step="0.01" value={edit.amount} onChange={e=>setEdit({...edit,amount:e.target.value})}/></label><label><span>Comercio / emisor</span><input value={edit.merchant} onChange={e=>setEdit({...edit,merchant:e.target.value})}/></label><label className="wide"><span>Notas</span><textarea rows={2} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><label className="wide"><span>Texto OCR <small>puedes corregir errores</small></span><textarea className="ocr-text-editor" rows={12} value={edit.ocrText} onChange={e=>setEdit({...edit,ocrText:e.target.value})}/></label></div><div className="editor-actions"><button className="primary-action" type="submit" disabled={busy}>Guardar cambios</button></div></form>
      {detail.digitalReconstruction&&<details className="trace-panel" open><summary>Vista reconstruida del ticket</summary><div className="ocr-warning"><strong>Reconstrucción OCR</strong><span>Se intenta conservar saltos, columnas y espacios del ticket. El original sigue siendo la referencia.</span></div><div className="receipt-preview"><div className="receipt-paper"><pre>{reconstructionLayout}</pre></div><dl className="receipt-extracted"><div><dt>Comercio</dt><dd>{detail.merchant||"—"}</dd></div><div><dt>Fecha</dt><dd>{formatDate(detail.documentDate)}</dd></div><div><dt>Total</dt><dd>{formatMoney(detail.amount)}</dd></div></dl></div></details>}
      <details className="trace-panel" open><summary>Movimientos vinculados · {formatInteger(detail.links.length)}</summary><div className="link-list">{detail.links.map(link=><div key={link.sourceId}><span><strong>{link.counterparty||link.concept||link.sourceId}</strong><small>{formatDate(link.date)} · {formatMoney(link.amount)} · {link.sourceId}</small></span><button className="ghost" type="button" onClick={()=>unlinkMovement(link.sourceId)}>Desvincular</button></div>)}{!detail.links.length&&<p className="muted-copy">Aún no hay movimientos vinculados.</p>}</div></details>
      {currentSuggestions.length>0&&<details className="trace-panel" open><summary>Sugerencias de vinculación</summary><div className="link-list">{currentSuggestions.map(s=><div key={s.sourceId}><span><strong>{s.counterparty||s.concept||s.sourceId}</strong><small>{formatDate(s.date)} · {formatMoney(s.amount)} · coincidencia {Math.max(0,Math.min(100,Number(s.score||0))).toFixed(0)}%</small></span><button className="ghost" type="button" onClick={()=>linkMovement(s)}>Vincular</button></div>)}</div></details>}
      <details className="trace-panel"><summary>Historial · {formatInteger(detail.history.length)}</summary><ol className="history-list">{detail.history.map((h,index)=><li key={`${h.changedAt}-${index}`}><div><strong>{h.action}</strong><time>{new Date(h.changedAt).toLocaleString("es-ES")}</time></div><small>{h.changedBy||"sistema"}</small></li>)}</ol></details>
    </aside></div>}
  </div>
}