"use client";

import { formatEuro, formatInteger } from "@/lib/format/es-es";
import { madridToday } from "@/lib/time/madrid";
import { inferDocumentMetadata, type DocumentMetadata, type DocumentTypeHint } from "@/lib/document/ticket-ocr-metadata";
import { RECEIPT_OCR_METHOD_PREFIX } from "@/lib/document/receipt-ocr-revision";
import { parseReceiptLayout, type ReceiptLayout } from "@/lib/document/receipt-layout";
import { FormEvent, useMemo, useRef, useState } from "react";
import {useRouter} from "next/navigation";
import { createClient } from "@/lib/supabase/browser";
import type { ArchiveDetail, ArchiveOverview, ArchiveMovementRef } from "@/lib/financial/archive";
import { ArchiveMovementPicker } from "./archive-movement-picker";
import { isReceiptVisualLayout, ReceiptGeometryPreview } from "./receipt-geometry-preview";

declare global { interface Window { __financialPaddleOCR?: { PaddleOCR: any }; __financialPdfjs?: any } }

type OcrStatus="complete"|"needs_review"|"failed"|"error";
type OcrResult={text:string;status:OcrStatus;data:Record<string,unknown>;reconstruction:Record<string,unknown>|null;documentType:string;documentDate:string|null;amount:number|null;merchant:string|null};
type DetailPayload={ok:true;document:ArchiveDetail;signedUrl:string|null};
type UpdatedDetailPayload={ok:true;document:ArchiveDetail;error?:string};
type ArchiveEdit={documentType:string;documentDate:string;amount:number|string;merchant:string;notes:string;ocrText:string};
type ActionKind="search"|"open"|"upload"|"ocr-upgrade"|"save"|"link"|"unlink"|"archive"|"delete"|"more";
type ActionState={kind:ActionKind;target?:string}|null;
const MAX_FILE=20*1024*1024;
const PAGE_SIZE=200;
const allowed=new Set(["application/pdf","image/jpeg","image/png","image/webp","image/heic","image/heif"]);
const dates=new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"2-digit",year:"numeric"});
let sharedWorkerPromise:Promise<any>|null=null;

function formatDate(value:string|null){return value?dates.format(new Date(`${value}T12:00:00`)):"—"}
function formatMoney(value:number|null){return value==null?"—":formatEuro(value)}
function safeName(name:string){return name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(0,120)||"documento"}
function editFromDocument(document:ArchiveDetail):ArchiveEdit{return{documentType:document.documentType,documentDate:document.documentDate||"",amount:document.amount??"",merchant:document.merchant||"",notes:document.notes||"",ocrText:document.ocrText||""}}
function receiptValue(value:string){return value.replace(/\bEUR\b/gi,"€").replace(/(\d)\.(\d{2})(?!\d)/g,"$1,$2")}
function reconstructionReceiptLayout(document:ArchiveDetail|null){if(!document?.digitalReconstruction||typeof document.digitalReconstruction!=="object")return null;const raw=(document.digitalReconstruction as Record<string,unknown>).receiptLayout;if(!raw||typeof raw!=="object")return null;const value=raw as Partial<ReceiptLayout>;return Array.isArray(value.header)&&Array.isArray(value.items)&&Array.isArray(value.summary)&&Array.isArray(value.footer)?value as ReceiptLayout:null;}
function reconstructionVisualLayout(document:ArchiveDetail|null){if(!document?.digitalReconstruction||typeof document.digitalReconstruction!=="object")return null;const raw=(document.digitalReconstruction as Record<string,unknown>).visualLayout;return isReceiptVisualLayout(raw)?raw:null;}
function ocrMethod(document:ArchiveDetail){return document.ocrData&&typeof document.ocrData==="object"?String((document.ocrData as Record<string,unknown>).method||""):""}
function ocrValidation(document:ArchiveDetail|null){if(!document?.ocrData||typeof document.ocrData!=="object")return null;const value=(document.ocrData as Record<string,unknown>).validation;return value&&typeof value==="object"?value as Record<string,unknown>:null;}
function needsOcrUpgrade(document:ArchiveDetail){return Boolean(document.mimeType?.startsWith("image/")&&document.ocrStatus!=="manual"&&!ocrMethod(document).startsWith(RECEIPT_OCR_METHOD_PREFIX));}
function ocrStatusLabel(status:string){if(status==="complete")return"OCR validado";if(status==="needs_review")return"Revisar OCR";if(status==="failed"||status==="error")return"OCR pendiente";if(status==="manual")return"OCR corregido";return status;}
function needsDocumentReview(document:ArchiveDetail){return document.lifecycleState==="pending"}
async function sha256(file:File){const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}
async function loadPdfJs(){if(window.__financialPdfjs)return window.__financialPdfjs;return new Promise<any>((resolve,reject)=>{const existing=document.getElementById("financial-pdfjs-loader");const onReady=()=>{cleanup();window.__financialPdfjs?resolve(window.__financialPdfjs):reject(new Error("PDF.js no disponible"))};const cleanup=()=>window.removeEventListener("financial-pdfjs-ready",onReady);window.addEventListener("financial-pdfjs-ready",onReady,{once:true});if(!existing){const script=document.createElement("script");script.id="financial-pdfjs-loader";script.type="module";script.src="/vendor/pdfjs-loader.mjs";script.onerror=()=>{cleanup();reject(new Error("No se pudo cargar el lector PDF"))};document.head.appendChild(script)}})}
async function loadPaddleOcr(){if(window.__financialPaddleOCR)return window.__financialPaddleOCR;return new Promise<{PaddleOCR:any}>((resolve,reject)=>{const existing=document.getElementById("financial-paddleocr-loader");const onReady=()=>{cleanup();window.__financialPaddleOCR?resolve(window.__financialPaddleOCR):reject(new Error("OCR de tickets no disponible"))};const cleanup=()=>window.removeEventListener("financial-paddleocr-ready",onReady);window.addEventListener("financial-paddleocr-ready",onReady,{once:true});if(!existing){const script=document.createElement("script");script.id="financial-paddleocr-loader";script.type="module";script.src="/vendor/paddleocr-loader.mjs";script.onerror=()=>{cleanup();reject(new Error("No se pudo cargar el OCR de tickets"))};document.head.appendChild(script)}})}
function paddleText(result:any){const items=Array.isArray(result?.items)?result.items:[];return items.map((item:any)=>String(item?.text||"").trim()).filter(Boolean).join("\n")}
function paddleConfidence(result:any){const items=Array.isArray(result?.items)?result.items:[];const scores=items.map((item:any)=>Number(item?.score)).filter(Number.isFinite).map((score:number)=>score<=1?score*100:score);return scores.length?scores.reduce((sum:number,score:number)=>sum+score,0)/scores.length:null}
async function makeWorker(onProgress:(value:number,label:string)=>void){
  if(!sharedWorkerPromise){
    sharedWorkerPromise=(async()=>{onProgress(.04,"Cargando OCR de tickets");const module=await loadPaddleOcr();const ocr=await module.PaddleOCR.create({lang:"es",ocrVersion:"PP-OCRv6",ortOptions:{backend:"wasm",wasmPaths:"https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/",numThreads:1,simd:true}});return{predict:(input:Blob|HTMLCanvasElement,params?:Record<string,unknown>)=>ocr.predict(input,params),recognize:async(input:Blob|HTMLCanvasElement)=>{const results=await ocr.predict(input,{textRecScoreThresh:0,textDetMaxSideLimit:4000});const result=results?.[0];return{data:{text:paddleText(result),confidence:paddleConfidence(result)}}}}})().catch(error=>{sharedWorkerPromise=null;throw error});
  }
  return sharedWorkerPromise;
}

async function runOcr(file:File,onProgress:(value:number,label:string)=>void,hint:DocumentTypeHint=null):Promise<OcrResult>{
  onProgress(.03,"Preparando documento");let text="";let layoutText="";let method="image_ocr";let pages=1;let confidence:number|null=null;let passes:Array<Record<string,unknown>>=[];let imageMetadata:DocumentMetadata|null=null;let structuredLayout:ReceiptLayout|null=null;let status:OcrStatus="complete";let evidence:Record<string,unknown>={};let visualLayout:unknown=null;
  if(file.type==="application/pdf"){
    const pdfjs=await loadPdfJs();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;pages=pdf.numPages;const chunks:string[]=[];const scanned:number[]=[];
    for(let i=1;i<=pdf.numPages;i++){onProgress(.05+.3*(i/pdf.numPages),`Leyendo PDF · página ${i}/${pdf.numPages}`);const page=await pdf.getPage(i);const content=await page.getTextContent();const pageText=content.items.map((item:any)=>String(item?.str||"")).join(" ").trim();if(pageText.replace(/\s/g,"").length>=40)chunks.push(pageText);else scanned.push(i)}
    if(scanned.length){method=chunks.length?"pdf_hybrid_ppocrv6":"pdf_ocr_ppocrv6";const worker=await makeWorker(onProgress);const scores:number[]=[];for(let index=0;index<scanned.length;index++){const pageNo=scanned[index];const page=await pdf.getPage(pageNo);const viewport=page.getViewport({scale:1.65});const canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas no disponible");await page.render({canvasContext:ctx,viewport}).promise;onProgress(.4+.55*((index+1)/scanned.length),`OCR · página ${pageNo}/${pdf.numPages}`);const recognized=await worker.recognize(canvas);chunks.push(String(recognized.data?.text||""));if(Number.isFinite(recognized.data?.confidence))scores.push(Number(recognized.data.confidence))}confidence=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null}
    else method="pdf_text";text=chunks.join("\n\n");layoutText=text;
  }else{
    const [{recognizeTicketImage},worker]=await Promise.all([import("@/lib/document/ticket-ocr"),makeWorker(onProgress)]);const recognized=await recognizeTicketImage(file,worker,onProgress,hint);text=recognized.text;layoutText=recognized.layoutText;confidence=recognized.confidence;method=recognized.method;passes=recognized.passes as Array<Record<string,unknown>>;imageMetadata=recognized.metadata||null;structuredLayout=recognized.receiptLayout||null;status=recognized.validation?.status||"needs_review";visualLayout=passes[0]?.visualLayout||null;evidence={rawText:recognized.rawText,normalizedText:recognized.normalizedText,tsv:recognized.tsv,validation:recognized.validation,metrics:recognized.metrics,visualLayout,deskewAngle:recognized.deskewAngle,perspectiveCorrected:recognized.perspectiveCorrected};
  }
  if(!text.trim())throw new Error("No se ha podido extraer texto del documento");const meta=imageMetadata||inferDocumentMetadata(text,hint);const engineLabel=method==="pdf_text"?"PDF.js":"OCR de tickets · servidor";const reconstruction={generated:true,label:status==="complete"?"Reconstrucción visual validada desde las coordenadas OCR. El original sigue siendo la referencia.":"Reconstrucción geométrica pendiente de revisión. El original y las líneas OCR siguen siendo la referencia.",engine:engineLabel,method,documentType:meta.documentType,documentDate:meta.documentDate,amount:meta.amount,merchant:meta.merchant,layoutText:layoutText||text,receiptLayout:structuredLayout,visualLayout};
  onProgress(1,status==="complete"?"OCR validado":"OCR pendiente de revisión");return{text,status,data:{engine:method==="pdf_text"?"PDF.js 6.2.108":"OCR de tickets · servidor",method,pages,confidence,passes,language:"es",localProcessing:false,automaticOnImport:true,imagePreprocessing:Boolean(passes[0]?.paperDetected),geometryLayout:Boolean(visualLayout||structuredLayout),workerReuse:true,assetOrigin:"server-bundled",processedAt:new Date().toISOString(),...evidence},reconstruction,documentType:meta.documentType,documentDate:meta.documentDate,amount:meta.amount,merchant:meta.merchant};
}

export function ArchiveClient({initialData}:{initialData:ArchiveOverview}){
  const router=useRouter();
  const [data,setData]=useState(initialData);const [search,setSearch]=useState("");const [action,setAction]=useState<ActionState>(null);const [progress,setProgress]=useState(0);const [progressLabel,setProgressLabel]=useState("");const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [detail,setDetail]=useState<ArchiveDetail|null>(null);const [signedUrl,setSignedUrl]=useState<string|null>(null);const [edit,setEdit]=useState<ArchiveEdit|null>(null);const cameraRef=useRef<HTMLInputElement>(null);const galleryRef=useRef<HTMLInputElement>(null);const fileRef=useRef<HTMLInputElement>(null);
  const isAction=(kind:ActionKind,target?:string)=>action?.kind===kind&&(target===undefined||action.target===target);
  const drawerLocked=isAction("save")||isAction("archive")||isAction("delete")||isAction("ocr-upgrade");

  function applyDetail(document:ArchiveDetail,nextSignedUrl?:string|null){setDetail(document);setEdit(editFromDocument(document));if(nextSignedUrl!==undefined)setSignedUrl(nextSignedUrl);setData(current=>{const found=current.documents.some(item=>item.id===document.id);const documents=found?current.documents.map(item=>item.id===document.id?document:item):[document,...current.documents];return{...current,documents}})}
  function removeDocument(id:string){setData(current=>({...current,documents:current.documents.filter(item=>item.id!==id),total:Math.max(0,current.total-1)}))}
  async function refresh(q=search){const params=new URLSearchParams({limit:String(PAGE_SIZE),offset:"0"});if(q.trim())params.set("search",q.trim());const r=await fetch(`/api/archive?${params.toString()}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo cargar Archivo");setData(body as ArchiveOverview);return body as ArchiveOverview}
  async function loadMore(){if(isAction("more"))return;setAction({kind:"more"});setError(null);try{const params=new URLSearchParams({limit:String(PAGE_SIZE),offset:String(data.documents.length)});if(search.trim())params.set("search",search.trim());const r=await fetch(`/api/archive?${params.toString()}`,{cache:"no-store"});const body=await r.json() as ArchiveOverview&{error?:string};if(!r.ok)throw new Error(body.error||"No se pudieron cargar más documentos");setData(current=>{const seen=new Set(current.documents.map(item=>item.id));const documents=[...current.documents,...body.documents.filter(item=>!seen.has(item.id))];return{...body,documents}})}catch(cause){setError(cause instanceof Error?cause.message:"Error al cargar más documentos")}finally{setAction(null)}}
  async function submitSearch(e:FormEvent){e.preventDefault();setAction({kind:"search"});setError(null);try{await refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Error de búsqueda")}finally{setAction(null)}}
  async function upgradeExistingOcr(document:ArchiveDetail,url:string,force=false){
    if(!force&&!needsOcrUpgrade(document))return;setAction({kind:"ocr-upgrade",target:document.id});setProgress(.02);setProgressLabel("Reconstruyendo el ticket desde el original");setError(null);setMessage(null);
    try{const original=await fetch(url,{cache:"no-store"});if(!original.ok)throw new Error("original_unavailable");const blob=await original.blob();const file=new File([blob],document.fileName,{type:document.mimeType||blob.type,lastModified:Date.now()});const result=await runOcr(file,(value,label)=>{setProgress(value);setProgressLabel(label)},"receipt");const patched=await fetch(`/api/archive/${document.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentType:result.documentType,documentDate:result.documentDate,amount:result.amount,merchant:result.merchant,ocrText:result.text,ocrData:result.data,digitalReconstruction:result.reconstruction,ocrStatus:result.status})});const body=await patched.json() as UpdatedDetailPayload;if(!patched.ok||!body.document)throw new Error(body.error||"ocr_upgrade_failed");applyDetail(body.document,url);setMessage(result.status==="complete"?"OCR actualizado y validado.":"OCR actualizado; las líneas dudosas permanecen visibles para revisión.");}catch{setError("El OCR no ha podido reconstruir el ticket en este intento. El original y la revisión anterior se conservan sin cambios.");}finally{setProgress(0);setProgressLabel("");setAction(null)}
  }
  async function openDocument(id:string){if(isAction("open",id))return;setAction({kind:"open",target:id});setError(null);try{const r=await fetch(`/api/archive/${id}`,{cache:"no-store"});const body=await r.json() as DetailPayload & {error?:string};if(!r.ok||!body.ok)throw new Error(body.error||"No se pudo abrir el documento");applyDetail(body.document,body.signedUrl);if(body.signedUrl&&needsOcrUpgrade(body.document))await upgradeExistingOcr(body.document,body.signedUrl)}catch(cause){setError(cause instanceof Error?cause.message:"Error al abrir documento")}finally{setAction(null)}}

  async function upload(file:File,hint:DocumentTypeHint=null){
    if(isAction("upload"))return;setAction({kind:"upload"});setError(null);setMessage(null);setProgress(0);setProgressLabel("Comprobando archivo");let storagePath:string|null=null;
    try{
      if(!allowed.has(file.type))throw new Error("Formato no admitido. Usa PDF, JPEG, PNG, WebP, HEIC o HEIF.");if(file.size<=0||file.size>MAX_FILE)throw new Error("El archivo debe ocupar entre 1 byte y 20 MB.");
      const hash=await sha256(file);const supabase=createClient();const {data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user)throw new Error("Sesión no válida");storagePath=`${userData.user.id}/${madridToday()}/${crypto.randomUUID()}-${safeName(file.name)}`;
      setProgress(.02);setProgressLabel("Guardando original privado");const stored=await supabase.storage.from("financial-app-documents").upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:"3600"});if(stored.error)throw stored.error;
      const registered=await fetch("/api/archive",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileName:file.name,mimeType:file.type,storagePath,fileSize:file.size,contentHash:hash})});const registration=await registered.json();if(!registered.ok){await supabase.storage.from("financial-app-documents").remove([storagePath]);throw new Error(registration.error||"No se pudo registrar el documento")}
      const id=String(registration.id);
      try{
        const result=await runOcr(file,(value,label)=>{setProgress(value);setProgressLabel(label)},hint);
        const patched=await fetch(`/api/archive/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentType:result.documentType,documentDate:result.documentDate,amount:result.amount,merchant:result.merchant,ocrText:result.text,ocrData:result.data,digitalReconstruction:result.reconstruction,ocrStatus:result.status})});
        const patchedBody=await patched.json() as UpdatedDetailPayload;if(!patched.ok||!patchedBody.document)throw new Error(patchedBody.error||"No se pudo guardar el OCR");
        const signed=await supabase.storage.from("financial-app-documents").createSignedUrl(storagePath,300);applyDetail(patchedBody.document,signed.data?.signedUrl||null);
        setMessage(result.status==="complete"?"Documento guardado y OCR validado.":"Documento guardado. Las líneas OCR y su posición se conservan, pero el ticket requiere revisión antes de declararse completo.");
      }catch(ocrError){
        const failed=await fetch(`/api/archive/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ocrStatus:"failed",ocrData:{localProcessing:false,automaticOnImport:true,error:ocrError instanceof Error?ocrError.message:"ocr_failed",processedAt:new Date().toISOString()}})});
        const failedBody=await failed.json().catch(()=>null) as UpdatedDetailPayload|null;
        const signed=await supabase.storage.from("financial-app-documents").createSignedUrl(storagePath,300);
        if(failed.ok&&failedBody?.document){applyDetail(failedBody.document,signed.data?.signedUrl||null)}else{const detailResponse=await fetch(`/api/archive/${id}`,{cache:"no-store"});const detailBody=await detailResponse.json().catch(()=>null) as DetailPayload|null;if(detailResponse.ok&&detailBody?.ok)applyDetail(detailBody.document,detailBody.signedUrl||signed.data?.signedUrl||null)}
        setError("El original se ha guardado, pero el OCR no ha podido leer este ticket. El documento queda abierto para revisar el original o volver a intentarlo.");
      }
      void refresh(search).catch(()=>undefined);
    }catch(cause){setError(cause instanceof Error?cause.message:"No se pudo subir el documento")}finally{setAction(null);setProgress(0);setProgressLabel("");if(cameraRef.current)cameraRef.current.value="";if(galleryRef.current)galleryRef.current.value="";if(fileRef.current)fileRef.current.value=""}
  }

  async function saveDetail(e:FormEvent){
    e.preventDefault();if(!detail||!edit||isAction("save"))return;setAction({kind:"save",target:detail.id});setError(null);setMessage(null);
    try{
      const r=await fetch(`/api/archive/${detail.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({documentType:edit.documentType,documentDate:edit.documentDate||null,amount:edit.amount===""?null:Number(edit.amount),merchant:edit.merchant||null,notes:edit.notes||null,ocrText:edit.ocrText||null,ocrStatus:edit.ocrText!==(detail.ocrText||"")?"manual":detail.ocrStatus})});
      const body=await r.json() as UpdatedDetailPayload;if(!r.ok||!body.document)throw new Error(body.error||"No se pudo guardar");applyDetail(body.document);setMessage("Cambios guardados. La evidencia geométrica original del OCR permanece en la trazabilidad del motor.");
    }catch(cause){setError(cause instanceof Error?cause.message:"Error al guardar")}finally{setAction(null)}
  }

  async function linkMovement(ref:ArchiveMovementRef){if(!detail||isAction("link",ref.sourceId))return;setAction({kind:"link",target:ref.sourceId});setError(null);try{const r=await fetch(`/api/archive/${detail.id}/links`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceId:ref.sourceId})});const body=await r.json() as UpdatedDetailPayload;if(!r.ok)throw new Error(body.error||"No se pudo vincular");if(body.document)applyDetail(body.document);else await openDocument(detail.id)}catch(cause){setError(cause instanceof Error?cause.message:"Error de vinculación")}finally{setAction(null)}}
  async function unlinkMovement(sourceId:string){if(!detail||isAction("unlink",sourceId))return;setAction({kind:"unlink",target:sourceId});setError(null);try{const r=await fetch(`/api/archive/${detail.id}/links?sourceId=${encodeURIComponent(sourceId)}`,{method:"DELETE"});const body=await r.json() as UpdatedDetailPayload;if(!r.ok)throw new Error(body.error||"No se pudo desvincular");if(body.document)applyDetail(body.document);else await openDocument(detail.id)}catch(cause){setError(cause instanceof Error?cause.message:"Error al desvincular")}finally{setAction(null)}}
  async function archiveCurrent(){if(!detail||needsDocumentReview(detail)||isAction("archive"))return;const id=detail.id;setAction({kind:"archive",target:id});setError(null);try{const r=await fetch(`/api/archive/${id}?action=archive`,{method:"POST"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo archivar");removeDocument(id);setDetail(null);setSignedUrl(null);setEdit(null);setMessage("Documento archivado. Puedes recuperarlo desde Archivadas.");router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Error al archivar")}finally{setAction(null)}}
  async function deleteCurrent(){if(!detail||isAction("delete"))return;const id=detail.id;const ok=confirm(`¿Eliminar "${detail.fileName}"? Se borrarán el original privado, el OCR y sus vínculos. Esta acción no se puede deshacer.`);if(!ok)return;setAction({kind:"delete",target:id});setError(null);try{const r=await fetch(`/api/archive/${id}`,{method:"DELETE"});const body=await r.json();if(!r.ok)throw new Error(body.error||"No se pudo eliminar");removeDocument(id);setDetail(null);setSignedUrl(null);setEdit(null);setMessage("Documento eliminado.");void refresh(search).catch(()=>undefined)}catch(cause){setError(cause instanceof Error?cause.message:"Error al eliminar")}finally{setAction(null)}}

  const currentSuggestions:ArchiveMovementRef[]=detail?.suggestions??[];
  const visibleDocuments=data.documents;
  const hasMore=Boolean(data.hasMore);
  const reconstructionLayout=detail?.digitalReconstruction&&typeof detail.digitalReconstruction==="object"?String((detail.digitalReconstruction as Record<string,unknown>).layoutText||detail.ocrText||""):String(detail?.ocrText||"");
  const receiptLayout=useMemo(()=>detail?reconstructionReceiptLayout(detail)||parseReceiptLayout(reconstructionLayout):null,[detail,reconstructionLayout]);
  const visualLayout=useMemo(()=>reconstructionVisualLayout(detail),[detail]);
  const validation=useMemo(()=>ocrValidation(detail),[detail]);
  const contradictions=Array.isArray(validation?.contradictions)?validation.contradictions as Array<Record<string,unknown>>:[];
  const canRetryOcr=Boolean(detail&&signedUrl&&detail.mimeType?.startsWith("image/")&&["needs_review","failed","error"].includes(detail.ocrStatus));

  return <div className="archive-module">
    <section className="archive-summary"><div><strong>{formatInteger(data.total)}</strong><span>documentos</span></div><div><strong>{formatInteger(data.processed)}</strong><span>procesados</span></div><div><strong>{formatInteger(data.linked)}</strong><span>vinculados</span></div><div><strong>Privado</strong><span>bucket protegido</span></div></section>
    <div className="archive-toolbar"><form onSubmit={submitSearch}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por archivo, comercio, OCR o notas"/><button className="ghost" type="submit" disabled={isAction("search")} aria-busy={isAction("search")||undefined}>{isAction("search")?"Buscando…":"Buscar"}</button></form><div className="archive-import-actions"><button className="primary-action" type="button" onClick={()=>cameraRef.current?.click()} disabled={isAction("upload")} aria-busy={isAction("upload")||undefined}>{isAction("upload")?"Procesando ticket…":"Hacer foto de ticket"}</button><button className="ghost" type="button" onClick={()=>galleryRef.current?.click()} disabled={isAction("upload")}>Elegir foto de galería</button><button className="ghost" type="button" onClick={()=>fileRef.current?.click()} disabled={isAction("upload")}>Añadir documento</button></div><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"receipt")}/><input ref={galleryRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"receipt")}/><input ref={fileRef} hidden type="file" accept=".pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></div>
    {progress>0&&<div className="ocr-progress" role="status"><div><span>{progressLabel}</span><b>{Math.round(progress*100)}%</b></div><progress max={1} value={progress}/><small>{isAction("ocr-upgrade")?"El ticket se está leyendo otra vez desde el original privado. No necesitas volver a subir la foto.":"La foto se envía al OCR privado de Financial App y el original permanece protegido."}</small></div>}
    {error&&<div className="inline-alert error" role="alert">{error}</div>}{message&&<div className="inline-alert success" role="status">{message}</div>}
    <div className="archive-library-note"><strong>Gestión documental activa</strong><span>Aquí puedes abrir, corregir, vincular y archivar los documentos que aún no están en el histórico. Los que requieren revisión permanecen identificados como pendientes.</span></div>
    <section className="document-grid">{visibleDocuments.map(doc=><button className="document-card" key={doc.id} onClick={()=>openDocument(doc.id)} type="button" disabled={isAction("open",doc.id)} aria-busy={isAction("open",doc.id)||undefined}><div className="document-kind">{doc.mimeType==="application/pdf"?"PDF":"IMG"}</div><div><strong>{doc.fileName}</strong><span>{doc.merchant||doc.documentType} · {formatDate(doc.documentDate)}</span><small>{formatMoney(doc.amount)} · {isAction("open",doc.id)?"Abriendo…":ocrStatusLabel(doc.ocrStatus)}</small></div>{doc.links.length>0&&<em>{formatInteger(doc.links.length)} vínculo{doc.links.length===1?"":"s"}</em>}</button>)}</section>
    {hasMore&&<div className="archive-library-note"><strong>Hay más documentos</strong><button className="ghost" type="button" onClick={loadMore} disabled={isAction("more")} aria-busy={isAction("more")||undefined}>{isAction("more")?"Cargando…":"Cargar más"}</button></div>}
    {!visibleDocuments.length&&<div className="empty-state"><strong>Sin documentos activos</strong><span>Añade una factura, ticket, contrato o justificante para empezar.</span></div>}
    {detail&&edit&&<div className="drawer-backdrop" onMouseDown={()=>!drawerLocked&&(setDetail(null),setEdit(null),setSignedUrl(null))}><aside className="archive-drawer" role="dialog" aria-modal="true" aria-labelledby="archive-title" onMouseDown={e=>e.stopPropagation()}><header className="drawer-head"><div><p className="eyebrow">ORIGINAL PRIVADO</p><h2 id="archive-title">{detail.fileName}</h2><p>{detail.contentHash?.slice(0,16)}… · {detail.fileSize?`${(detail.fileSize/1024).toFixed(0)} KB`:""}</p></div><button className="icon-button" type="button" disabled={drawerLocked} onClick={()=>{setDetail(null);setEdit(null);setSignedUrl(null)}} aria-label="Cerrar">×</button></header>
      <div className="archive-actions">{signedUrl&&<a className="ghost button-link" href={signedUrl} target="_blank" rel="noreferrer">Abrir original</a>}{canRetryOcr&&<button className="secondary-action" type="button" onClick={()=>signedUrl&&upgradeExistingOcr(detail,signedUrl,true)} disabled={isAction("ocr-upgrade")||isAction("delete")||isAction("archive")} aria-busy={isAction("ocr-upgrade")||undefined}>{isAction("ocr-upgrade")?"Reintentando OCR…":"Volver a intentar OCR"}</button>}{!needsDocumentReview(detail)&&<button className="secondary-action" type="button" onClick={archiveCurrent} disabled={isAction("archive")||isAction("delete")||isAction("ocr-upgrade")} aria-busy={isAction("archive")||undefined}>{isAction("archive")?"Archivando…":"Archivar"}</button>}<button className="danger-action" type="button" onClick={deleteCurrent} disabled={isAction("delete")||isAction("archive")||isAction("ocr-upgrade")} aria-busy={isAction("delete")||undefined}>{isAction("delete")?"Eliminando…":"Eliminar documento"}</button></div>
      {(detail.ocrStatus==="failed"||detail.ocrStatus==="error")&&<div className="ocr-warning" role="alert"><strong>El ticket está guardado, pero el OCR no ha podido leerlo</strong><span>El original permanece disponible. Puedes revisarlo y volver a intentar el reconocimiento sin perder la foto.</span></div>}
      <ArchiveMovementPicker documentId={detail.id} linkedSourceIds={detail.links.map(link=>link.sourceId)} onChanged={()=>openDocument(detail.id)}/>
      <form className="archive-editor" onSubmit={saveDetail}><div className="editor-grid"><label><span>Tipo</span><select value={edit.documentType} onChange={e=>setEdit({...edit,documentType:e.target.value})}><option value="invoice">Factura</option><option value="receipt">Ticket / recibo</option><option value="contract">Contrato</option><option value="statement">Extracto</option><option value="tax">Impuestos</option><option value="other">Otro</option></select></label><label><span>Fecha</span><input type="date" value={edit.documentDate} onChange={e=>setEdit({...edit,documentDate:e.target.value})}/></label><label><span>Importe</span><input type="number" step="0.01" value={edit.amount} onChange={e=>setEdit({...edit,amount:e.target.value})}/></label><label><span>Comercio / emisor</span><input value={edit.merchant} onChange={e=>setEdit({...edit,merchant:e.target.value})}/></label><label className="wide"><span>Notas</span><textarea rows={2} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label><label className="wide"><span>Texto OCR <small>editable; las líneas y coordenadas RAW permanecen conservadas en la evidencia OCR</small></span><textarea className="ocr-text-editor" rows={12} value={edit.ocrText} onChange={e=>setEdit({...edit,ocrText:e.target.value})}/></label></div><div className="editor-actions"><button className="primary-action" type="submit" disabled={isAction("save")||isAction("ocr-upgrade")} aria-busy={isAction("save")||undefined} data-loading={isAction("save")?"true":undefined}>{isAction("ocr-upgrade")?"Actualizando OCR…":isAction("save")?"Guardando…":"Guardar cambios"}</button></div></form>
      {detail.digitalReconstruction&&receiptLayout&&<details className="trace-panel" open><summary>Vista reconstruida del ticket</summary><div className="ocr-warning"><strong>{detail.ocrStatus==="complete"?"Reconstrucción validada del ticket":"Reconstrucción pendiente de revisión"}</strong><span>{detail.ocrStatus==="complete"?"La vista conserva la posición de las líneas detectadas y la validación matemática no encuentra contradicciones críticas.":contradictions.length?contradictions.map(item=>String(item.message||item.code||"")).join(" · "):"Las líneas reconocidas se mantienen en su posición aunque todavía no puedan interpretarse con seguridad."}</span></div><div className="receipt-preview"><div className={`receipt-paper ${receiptLayout.items.length?"receipt-paper-structured":""}`}>{visualLayout?<ReceiptGeometryPreview layout={visualLayout}/>:receiptLayout.items.length||receiptLayout.unparsedBody?.length?<><div className="receipt-header-lines">{receiptLayout.header.map((line,index)=><div key={`${line}-${index}`}>{receiptValue(line)}</div>)}</div><div className="receipt-table-wrap"><table className="receipt-table"><thead><tr><th>Descripción</th><th>Ud.</th><th>Precio</th><th>Importe</th></tr></thead><tbody>{receiptLayout.items.map((item,index)=><tr key={`${item.description}-${index}`}><td>{item.description}</td><td>{item.quantity}</td><td>{item.unitPrice} €</td><td>{item.total} €</td></tr>)}</tbody></table></div>{Boolean(receiptLayout.unparsedBody?.length)&&<div className="receipt-unparsed-lines"><strong>Líneas OCR pendientes de interpretar</strong>{receiptLayout.unparsedBody?.map((row,index)=><div key={`${row.text}-${index}`}>{receiptValue(row.text)}</div>)}</div>}{receiptLayout.summary.length>0&&<dl className="receipt-summary-lines">{receiptLayout.summary.map((line,index)=><div key={`${line.label}-${index}`}><dt>{line.label}</dt><dd>{receiptValue(line.value)}{/[0-9]$/.test(line.value)?" €":""}</dd></div>)}</dl>}{receiptLayout.footer.length>0&&<div className="receipt-footer-lines">{receiptLayout.footer.map((line,index)=><div key={`${line}-${index}`}>{receiptValue(line)}</div>)}</div>}</>:<pre>{reconstructionLayout}</pre>}</div><dl className="receipt-extracted"><div><dt>Comercio</dt><dd>{detail.merchant||"—"}</dd></div><div><dt>Fecha</dt><dd>{formatDate(detail.documentDate)}</dd></div><div><dt>Total</dt><dd>{formatMoney(detail.amount)}</dd></div></dl></div></details>}
      <details className="trace-panel" open><summary>Movimientos vinculados · {formatInteger(detail.links.length)}</summary><div className="link-list">{detail.links.map(link=><div key={link.sourceId}><span><strong>{link.counterparty||link.concept||link.sourceId}</strong><small>{formatDate(link.date)} · {formatMoney(link.amount)} · {link.sourceId}</small></span><button className="ghost" type="button" onClick={()=>unlinkMovement(link.sourceId)} disabled={isAction("unlink",link.sourceId)}>{isAction("unlink",link.sourceId)?"Desvinculando…":"Desvincular"}</button></div>)}{!detail.links.length&&<p className="muted-copy">Aún no hay movimientos vinculados.</p>}</div></details>
      {currentSuggestions.length>0&&<details className="trace-panel" open><summary>Sugerencias de vinculación</summary><div className="link-list">{currentSuggestions.map(s=><div key={s.sourceId}><span><strong>{s.counterparty||s.concept||s.sourceId}</strong><small>{formatDate(s.date)} · {formatMoney(s.amount)} · coincidencia {Math.max(0,Math.min(100,Number(s.score||0))).toFixed(0)}%</small></span><button className="ghost" type="button" onClick={()=>linkMovement(s)} disabled={isAction("link",s.sourceId)}>{isAction("link",s.sourceId)?"Vinculando…":"Vincular"}</button></div>)}</div></details>}
      <details className="trace-panel"><summary>Historial · {formatInteger(detail.history.length)}</summary><ol className="history-list">{detail.history.map((h,index)=><li key={`${h.changedAt}-${index}`}><div><strong>{h.action}</strong><time>{new Date(h.changedAt).toLocaleString("es-ES")}</time></div><small>{h.changedBy||"sistema"}</small></li>)}</ol></details>
    </aside></div>}
  </div>
}
