const FALLBACK_SUPABASE_URL = "https://ulxsvuksrghjgcjfuegv.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yBzX2dQRhZYKGfBY_8te7Q_C3D2eLTv";

export const SUPABASE_URL = (process.env.NEXT_PUBLIC_SUPABASE_URL || FALLBACK_SUPABASE_URL).trim();
export const SUPABASE_PUBLISHABLE_KEY = (process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY).trim();
export const SUPABASE_PUBLIC_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
